### ISSUE TITLE
CKEditor asks for non-existent CSS resource

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1009]
When loading the backend, there's a request to
```
/_Resources/Static/Packages/Neos.Neos.Ui/Plugins/ckeditor/skins/minimalist/editor.css
```
that originates from CKEditor. The Resource cannot be found.

We can fix this by just creating an empty CSS file at that location, but it might be sensible nonetheless to find out, why CKEditor is asking for the file.

**Comment by dimaip** [comment]
I still wonder, why we don't use CKE from npm?
https://www.npmjs.com/package/ckeditor
