### ISSUE TITLE
Simplify the installation process of the package

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#101]
Let's get rid of the manual installation process and move to a `composer require` one instead. @aertmann offered help here, @skurfuerst was also interested I think. Anyway, any help is reeeally appreciated here! :100: (AIRHORN)

**Comment by skurfuerst** [comment]
I currently don't yet see how we can work with a *composer require* way of installing without adding the compiled assets to Git. This can be of course done by e.g. a Jenkins job.

What do you think about this? Basically it would pollute the history some more, but on the other hand it would work with pull requests etc...

That's what we do with Neos -- and there it works fine.

All the best,
Sebastian

**Comment by Inkdpixels** [comment]
Is this solved due to #135?

**Comment by RafaelKa** [comment]
@Inkdpixels, no, its not done on#135. 

We can push(deploy) directly after successfull build from travis back to the repo and adding [ci skip] to commit message to avoid infinite loops.

see [travis docs for customizing the build](https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build)
