### ISSUE TITLE
Improve performance of initial load by parallelizing fetch calls and iframe load

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1020]
![screenshot_2017-09-25_17-01-21](https://user-images.githubusercontent.com/2522299/30815473-9f4ead2a-a213-11e7-95d7-192740173643.png)

As you can see, this is currently pretty bad. We could improve the initial load performance by parallelizing those first fetch calls. We should also find a way to render the iframe earlier while everything else is still loading.

**Comment by dimaip** [comment]
Should have been fixed.
