### ISSUE TITLE
Page Tree doesn't allow to select node, without loading it

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1028]
In the old UI, it is possible to select a node by clicking aside its label (a click directly on the label would trigger a page load). This behavior is important to perform operations like copy/cut and delete, without having to wait for a page load.

**Comment by dimaip** [comment]
Wow, never knew of this behavior in the old ui :see_no_evil:

**Comment by kitsunet** [comment]
IMHO not a planned feature but rather a "useful" bug?

I guess it would be cool to actually have a way to do that. But not something we urgently need to do?
