### ISSUE TITLE
Dimension switcher should close after selection

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1040]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

![screenshot_2017-09-27_09-54-35](https://user-images.githubusercontent.com/2522299/30903021-ac537090-a36d-11e7-8b6b-de2b215c7f92.png)

Currently, if you switch to another dimension, the dimension switcher stays open.

**Comment by dimaip** [comment]
Can reproduce, will fix
