### ISSUE TITLE
New API for registries and more unplanned extensibillity

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1044]
Currently the registries are flat key/value stores.
There are many cases where it makes sense to have them nested.

Take for example the topic of unplanned extensibility. Currently it's only possible to replace certain parts of the UI. But it would be cool to be able to insert new custom components anywhere between them.

We could take this syntax:
```js
containerRegistry.add('PrimaryToolbar/UserDropDown', UserDropDown);
containerRegistry.add('PrimaryToolbar/PublishDropDown', PublishDropDown);
...
```
But so that `containerRegistry.get('PrimaryToolbar')` would return a map of its inner keys, e.g.
```js
{
  UserDropDown: UserDropDown,
  PublishDropDown: PublishDropDown
}
```
Then we can just map over it and render all of the related components together.

But to support inserting more components later into the right position, we should support sorting.

It could work like this: 
```js
containerRegistry.add('PrimaryToolbar/MyCustomButton', MyCustomButton, 'after PublishDropDown');
```
We could use the positioning syntax from Fusion for example.

Should be relatively easy to implement, but would allow to do really crazy stuff extensibility-wise.

Would be also needed for things like registering multiple feedback handlers onto one feedback.

**Comment by skurfuerst** [comment]
- Decision: we'll make it return an array here
- rename "add" to "set"
- getOrderedSubElements
