### ISSUE TITLE
editorOptions in DateTimeEditor does not work

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#1048]
If you have a `DateTimeEditor` with `editorOptions`, for example `format:`, the editor should reduce his interface to the corresponding format and settings. https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-datetime-datetimeeditor-date-time-selection-editor

**Comment by dimaip** [comment]
Indeed, our editors were complaining about the 12h format and other stuff, I think it's important to take care of it before 1.0, will do it.
