### ISSUE TITLE
Select default inspector tab when switching nodes with different configurations

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1052]
If you are selecting a new node that has a node type configuration that doesn't include the previously selected inspector tab, the UI currently doesn't fall back to a meaningful default.

Steps to reproduce (on the demo site):

1. On the home page switch to the "SEO" Tab
2. Go to document "Shortcut to selected target"

You end up with an empty inspector with no tab selected.

**Comment by dimaip** [comment]
Hmm it appears this fix wasn't enough: https://github.com/neos/neos-ui/pull/873
Will try to do smth better.
