### ISSUE TITLE
UI should indicate editable elements

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1064]
In the old UI this is done via dashed borders. Currently it's a bit hard to distinguish editable from non-editable text.

**Comment by Duske** [comment]
I would like to tackle this issue if that's okay :)

**Comment by mstruebing** [comment]
@Duske Yep sure, go ahead :)

**Comment by Duske** [comment]
In the PR I used the `neos-inline-editable:hover`-pseudoclass to add a dashed outline border around inline editable elements.
