### ISSUE TITLE
Table dialog is broken

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1067]
![screenshot_2017-09-28_17-49-54](https://user-images.githubusercontent.com/2522299/30976610-855a4c62-a475-11e7-8881-2a21aabb00a3.png)

**Comment by skurfuerst** [comment]
I'll look into this

**Comment by dimaip** [comment]
Also currently it's not possible to delete rows/columns, merge cells etc.
Probably we need smth like this? https://ckeditor.com/cke4/addon/tabletools

**Comment by dimaip** [comment]
Sorry, I accidentally fixed it while working on smth else.
