### ISSUE TITLE
loading indicator sometimes keeps spinning after clearing the search

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#1074]
![sep-29-2017 13-18-58](https://user-images.githubusercontent.com/683773/31013962-ce591314-a518-11e7-8660-c45aace7e762.gif)

Use the search bar of the page tree typing, removing chars, typing again removing again. Sometimes completely clearing the input field sometimes just removing a couple of chars. At a certain point the spinner will keep spinning although the input is empty. 

Behaviour found on Demosite and on https://github.com/konglomerat/konglomerat-website

**Comment by mstruebing** [comment]
Can't reproduce, feel free to open if it is happening again.
