### ISSUE TITLE
discard is not doing anything after removing an image from a node

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#1077]
![sep-29-2017 13-40-10](https://user-images.githubusercontent.com/683773/31014563-ce7773ec-a51b-11e7-90b6-989e037ce35b.gif)

I removed an image from a custom node (content collection), which renders some kind of icon in the corner of a section. After hitting apply the publish button turns organge (which is correct). If I hit discard or discard all nothing happens. No reaction of the ui, no reloading of the iframe. Nothing. The button stays orange. Sometimes this is accompanied by an error message.

![screen shot 2017-09-29 at 13 44 35](https://user-images.githubusercontent.com/683773/31014671-66cfe782-a51c-11e7-9e52-ae8b40f7597c.png)

**Comment by grebaldi** [comment]
The error message is addressed in https://github.com/neos/neos-development-collection/pull/1711

**Comment by crazydrecksack** [comment]
ok

**Comment by dimaip** [comment]
So is this fixed? Anyways, can't reproduce it myself.

**Comment by kitsunet** [comment]
Also can't reproduce.
