### ISSUE TITLE
discard is taking very long to reload the iframe compared to a click in the page tree

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#1078]
![sep-29-2017 13-47-09](https://user-images.githubusercontent.com/683773/31014751-deacd832-a51c-11e7-8078-f7e0c617d9a6.gif)

takes about 13 seconds

**Comment by skurfuerst** [comment]
@grebaldi was this fixed by one of your recent changes? or not?

**Comment by dimaip** [comment]
I think this should have been fixed, reopen if not
