### ISSUE TITLE
double click to rename node in tree not working

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#1101]
used to work in old UI, no clue how to do this in new ui???

**Comment by dimaip** [comment]
Nothing too difficult, but do we need to do it really? @skurfuerst @grebaldi  your thoughts?

**Comment by kitsunet** [comment]
I would _love_ to get rid of that. It is sometimes convenient but overall feels like not exactly great UX.

**Comment by skurfuerst** [comment]
I'd *not* implement it in the new UI :) Closing ticket as we seem to agree
