### ISSUE TITLE
horizontal scrollbar not aligned to bottom for minimal vertical height of parent

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#1102]
![screen shot 2017-10-04 at 18 15 23](https://user-images.githubusercontent.com/683773/31186824-14e37822-a930-11e7-8b59-7678387f58d9.png)

Should not move up with the content but stay attachted to its parents bottom bounds.

**Comment by mstruebing** [comment]
@crazydrecksack for me it looks correct:

![screenshot_2017-10-06_05-37-42](https://user-images.githubusercontent.com/12071529/31262031-82029586-aa58-11e7-8efd-2004f9639356.png)

**Comment by mstruebing** [comment]
I'm closing now. If it is the case in the current state feel free to open again.
