### ISSUE TITLE
Metadata in Inline Link Editor is not legible on hover

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1104]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

![screenshot_2017-10-05_08-32-41](https://user-images.githubusercontent.com/2522299/31213667-04de735a-a9a8-11e7-985e-5b4cbcf63335.png)

**Comment by thefifthisa** [comment]
Hi! Can I take this?

**Comment by dimaip** [comment]
Hi @thefifthisa! Of course, you don't need to ask, just assign it to yourself and give it a shot!

**Comment by mstruebing** [comment]
Hey great to see someone new around here! 
@dimaip I think anyone who isn't in the neos-organization isn't able to assign a issue to themself.

@thefifthisa but go ahead, we are all able to read that you will tackle this issue :+1:

**Comment by dimaip** [comment]
Oh you are right, just go for it!

**Comment by mstruebing** [comment]
hey @thefifthisa, do you still want to tackle this issue?
