### ISSUE TITLE
Node creation dialog should be submittable by return key

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1108]

**Comment by thujeevan** [comment]
Wish to check on this one. Would you mind to point out where should I be looking into?

**Comment by dimaip** [comment]
@thujeevan hey this sounds really great, give it a shot!
This is a similar PR, perhaps you could learn something from how it was implemented? https://github.com/neos/neos-ui/pull/1099/files

**Comment by mstruebing** [comment]
Hey @thujeevan, do you still want to tackle this issue?

**Comment by thujeevan** [comment]
@mstruebing Sorry, I couldn't have time to work on it. Feel free to take it.
