### ISSUE TITLE
Only the module content is shown in left sidebar menu

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1109]
Having the role administrator, only the content module is shown in the left sidebar.

Neos: 3.2
UI: #ead7a6f

**Comment by dimaip** [comment]
Yes, can verify, seen this for a long time just didn't get to fix it.

**Comment by dimaip** [comment]
I'm on it. Seems to be related to http://neos.readthedocs.io/en/stable/Appendixes/ReleaseNotes/320.html#add-moduleprivilege-to-protect-neos-backend-modules
