### ISSUE TITLE
Multiselect/reference editor ignores nodeTypes if only one letter is entered

### ISSUE THREAD

**Issue by kabarakh** [neos/neos-ui#1126]
When we use a Multiselect/reference element, it starts searching after typing one letter (should be two letters) and during this search it ignores the nodeTypes setting restricting the reference type, but searches for something else

**Comment by skurfuerst** [comment]
I'll fix this / check this.

**Comment by dimaip** [comment]
Is it fixed now?

**Comment by skurfuerst** [comment]
fixed by now. Was an implementation error
