### ISSUE TITLE
Node creation dialog should start empty

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1128]
# How to reproduce
- Create a new documentNode
- Enter a title
- Hit cancel
- Create a new documentNode
- The title from before is still there

**Comment by dimaip** [comment]
Are you sure you are running the latest master? Can't reproduce it.

**Comment by daniellienert** [comment]
Pretty sure, will check again tomorrow

**Comment by dimaip** [comment]
Could you double-check by hard-reloading Chrome's cache? (https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.Wd8h-HWGOCg)
Just debugged a similar bug that was solved by hard cache flush.

**Comment by johannessteu** [comment]
Can't reproduce as well

**Comment by mstruebing** [comment]
I can reproduce it and it is only occuring if you go back and hit cancel in the previous dialog. If you hit the `x` the name is discarded
