### ISSUE TITLE
Errors of type "Unexpected Token < in JSON  at position 0"

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1129]
While working wit the new UI, I frequently get the error 
`Unexpected Token < in JSON  at position 0` displayed.
Seems that these are caused by backend exceptions. 

The Exceptions should be interpretable / interpreted by the UI and a more meaningful error message should be shown.

**Comment by skurfuerst** [comment]
That's solved by https://github.com/neos/neos-ui/pull/1125
