### ISSUE TITLE
When navigating through inline navigation, cannot go back to previous page

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#1151]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

- Go to page A in document tree
- navigate to page B in content area
- select page A in document tree again
- expected: selection to page A works
- actual: no navigation is triggered to PageA

**Comment by dimaip** [comment]
Can reproduce. When fixing please add TestCafe test to cover the case.

**Comment by skurfuerst** [comment]
will try testcafe tests :)

**Comment by dimaip** [comment]
@skurfuerst I think you have fixed it already, haven't you?

**Comment by kitsunet** [comment]
Can't reproduce anymore.

**Comment by skurfuerst** [comment]
fixed <3
