### ISSUE TITLE
Text overlaps chevron in SelectBox

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1166]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

![image](https://user-images.githubusercontent.com/837032/31827899-795193a0-b5c1-11e7-96be-9f758c042014.png)

**Comment by dimaip** [comment]
@crazydrecksack hey, do you still want to take care of things like these?

**Comment by dimaip** [comment]
![image](https://user-images.githubusercontent.com/837032/31950920-66fef86a-b8e5-11e7-8dc9-6d3d027ebb5d.png)

**Comment by mstruebing** [comment]
The issue of the second screenshot still exists

**Comment by dimaip** [comment]
Yes, I just closed by accident and the re-opened.
