### ISSUE TITLE
Update to Webpack 2

### ISSUE THREAD

**Issue by ryzy** [neos/neos-ui#118]
https://gist.github.com/sokra/27b24881210b56bbaff7

One of the main new features is:
- webpack 2 brings native support ES6 Modules. This means webpack now understands import and export without them being transformed to CommonJS
- The ES6 Loader spec defines System.import as method to load ES6 Modules dynamically on runtime.

I believe that would allow us to tackle **Loading custom inspector editors #106** in an right/elegant way.

**Comment by dimaip** [comment]
The biggest benefit for us would be the improved build speed. Really looking forward to it.

**Comment by Inkdpixels** [comment]
FYI I would see this as a task which _could_ be solved at the upcoming nuremberg sprint

**Comment by skurfuerst** [comment]
would be nice, but if it does not happen, no blocker.
