### ISSUE TITLE
Fix border-radius for Chrome 62 on MacOS

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#1180]
Chrome 62 on MacOS will render some elements like buttons with a default border-radius wich affects our UI. Therefore we need to set a default border-radius:none in our css

![bildschirmfoto 2017-10-25 um 12 35 18](https://user-images.githubusercontent.com/769789/31995427-9b3ecade-b984-11e7-8f62-30af4ab6d686.png)

Google-Changelog:
https://www.chromestatus.com/features/5743649186906112

**Comment by Bobeta** [comment]
I'll help you with this 👍

**Comment by dimaip** [comment]
Thanks @Bobeta! Might make sense to check if newer version of normalize.css would fix it: https://github.com/neos/neos-ui/blob/master/packages/neos-ui/src/styleHostOnly.css#L1

**Comment by Bobeta** [comment]
@dimaip An issue exists, but no update has been made on Normalize since the release of v7 in may

**Comment by mstruebing** [comment]
This can be closed, already fixed.
