### ISSUE TITLE
Find out why react-keydown doesn't trigger update for searchable selectbox

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#1181]
As figured out in #1165 `react-keydown` doesn't trigger an update when arrow keys are pressed, this is why we had to set `onKeyDown` explicitly. 
It would be good to figure out why this is happening as we plan to add more keyboard support to the UI

**Comment by dimaip** [comment]
@mstruebing is this issue still a valuable reminder to you?

**Comment by mstruebing** [comment]
I think it can be closed for now, if this issue reoccurs I will reopen it.
