### ISSUE TITLE
Disable CKEditor context menu

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#1193]
![bildschirmfoto 2017-10-26 um 15 06 58](https://user-images.githubusercontent.com/769789/32054662-7de360ae-ba5f-11e7-81a7-9c15824e2ed8.png)

**Comment by dimaip** [comment]
Can't be disabled without disabling tabletools plugin, which breaks most functionality for editing pages... The proper way to fix it is to migrate to CKE5.

**Comment by johannessteu** [comment]
Can we then style the dialog?

**Comment by dimaip** [comment]
Which dialog?

**Comment by dimaip** [comment]
Seems it's easily solvable: https://codepen.io/mlewand/pen/bYNqzq
Anyone wants to take care?
