### ISSUE TITLE
Update normalize when button-reset state is merged/released

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#1202]
The issue described in #1180 and fixed in #1185 should be removed when normalize is updated.

An issue exists here https://github.com/necolas/normalize.css/issues/706
And open PR: https://github.com/necolas/normalize.css/pull/697

Sadly there din't happen anything since May.

**Comment by johannessteu** [comment]
The issue #1180 is actually back?!
<img width="349" alt="bildschirmfoto 2017-11-15 um 10 07 03" src="https://user-images.githubusercontent.com/769789/32828269-e80f4ce2-c9ee-11e7-8ef3-b710af573a6f.png">

**Comment by dimaip** [comment]
AFAIK, Chrome team recognized it as a bug and they will revert it.
