### ISSUE TITLE
Support recent changes for the Asset Editor

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#1208]
See https://github.com/neos/neos-development-collection/pull/1727

This should be supported in 1.0 https://github.com/neos/neos-ui/issues/687

**Comment by dfeyer** [comment]
In relation with https://github.com/neos/neos-ui/issues/1390

**Comment by dimaip** [comment]
So this is a duplicate of #1390 basically? Will leave that one open.
Re-open if I'm wrong.
