### ISSUE TITLE
Options of the select box editor in the node creation dialog should visible

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1214]
(Needs to be said first: The adjustable node creation dialog is a really great feature of the new UI!)

If the selectbox editor is expanded, the options are hidden in the frame - and one need to scroll down. This needs a better solution.

![image](https://user-images.githubusercontent.com/642226/32407613-14f7f1ac-c18c-11e7-91ab-04dae0ca7e73.png)

**Comment by dimaip** [comment]
Yep, been hit by it too.
But in general, I have no idea of how the looks of this node creation dialog could be improved. E.g. now it's obviously too wide. Make it more narrow? Allow to layouts elements inside it in a grid? And do all of this while not over-engineering...

Perhaps good first step would be to make it more narrow and fix this z-index issue.

**Comment by dimaip** [comment]
It's easy to make selectbox jump out of the modal, but then it may be a problem that tall selectboxes would be chopped of by the screen height. So I have no idea how to solve it so far.

**Comment by markusguenther** [comment]
After reverting the last change we need another try ;)

**Comment by Nikdro** [comment]
Reverted?! What was the problem?

**Comment by markusguenther** [comment]
I changed the overflow and that lead to an issue with lot of node-types in the dialog
