### ISSUE TITLE
Don't replace dot with underscore in i18n id

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#1216]
Like mentioned in #1215 it is currently not possible to use translation id's with `.` in their name.

https://github.com/neos/neos-ui/blob/master/packages/neos-ui-i18n/src/registry/I18nRegistry.js#L75 replaces every `.` with an `_`.

Edit: It's not just replacing, in the translations are both cases, with an underscore and with a dot. So we need a different approach here.

**Comment by samuelhauser** [comment]
I'll have a look at this issue

**Comment by dimaip** [comment]
For some reason this can be closed, so closing....
