### ISSUE TITLE
Make source maps working again

### ISSUE THREAD

**Issue by ryzy** [neos/neos-ui#122]
Seems like it was done in #72, but it doesn't work currently.

**Comment by dimaip** [comment]
Do you refer to JS sourcemaps or CSS sourcemaps? That change should have enabled JS sourcemaps.

**Comment by dimaip** [comment]
I think source maps *are* working already? @ryzy can you confirm?

**Comment by grebaldi** [comment]
I'll close this one. Source maps seem to work.
