### ISSUE TITLE
Using refresh button on ContentCollection refreshes with wrong translation

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#1224]
I switched the neos ui to German in my User Settings. As expected, "ContentCollection" is named by its i18n-name for German (which is "Inhaltssammlung") in the structure tree for ContentNodeTypes. However: When pushing the refresh button (with the two arrows) of this part of the ui the name is switched back to it's untranslated english version "ContentCollection".

When refreshing the browser window, the German translation becomes visible again.

**Comment by johannessteu** [comment]
Can't reproduce. When i reload the structure tree it is still _Inhaltssammlung_ . Can someone else reproduce this one?
