### ISSUE TITLE
Error-throwing because of click on link to anchor in same page (created in old UI)

### ISSUE THREAD

**Issue by mad99** [neos/neos-ui#1231]
Have changed as an experiment from «old» to «reactUI». **Great experience!**
_Found only one little problem with anchor to the same page._

Maybe it is a wrong doing from my side. Because I wrote for the old UI nodeTypes and fusion code for define «classes» and «ID» for any text or headline nodeType. The fusion code pregReplace-ed this in the relevant «htmlTag». Worked great, but as Christian Müller said in Slack (https://neos-project.slack.com/archives/C0U0KEGDQ/p1510238549000742) 

> «interestingly I thought we never supported anchros»

## BUG-Report: Possible problem
So maybe this is the problem for reactUI:
I use for link-value «#mobile-first-content-first» -> only this. The old UI has translate this absolute right and output-ed clean Link-with-right-anchor. The linked anchor where set into sourcecode from my fusion pregReplace-function.

I saw, reactUI has the possibility define «anchor in same page» when I doubleClick on a link. But there is also a message «there are no anchors on the current page».

So maybe I have define first anchor's in new currently required style, then all would work without errors and also without my pregReplace stuff...

But a possible existing bug remains. So Christian suggested to open a bug ticket.
Below the relevant pictures ( more on slack https://neos-project.slack.com/archives/C0U0KEGDQ/p1510238549000742)

## BUG-Report: Steps that trigger the error
1. Click on the text with link created in old UI (filled formfield for target in old UI with #mobile-first-content-first)
-> in old UI (/neos) no problem can edit and save the values (text and link-target)
-> in «reactUI» (neos!) error Throwing

## BUG-Report: Own Bug-hunt/knowledge
in Chrome-Dev a error 500 clicked on link and «open in new Tab» there is an gray error box (see below)
The link in URL-Browser-field is:
http://my.website.react/neos/service/nodes?workspaceName=user-martin&contextNode=%2Fsites%2Fsitename%40user-martin%3Blanguage%3Dde_CH&dimensions%5Blanguage%5D%5B%5D=de_CH&nodeIdentifiers%5B%5D=%23mobile-first-content-first

Obvious a nodeIdentifiers that never were create or store in this manner: «mobile-first-content-first»

Hope will help to make reactUI even better than it already is. **_Thank you all!_**

<img width="324" alt="bildschirmfoto 2017-11-09 um 16 06 31" src="https://user-images.githubusercontent.com/6169308/32615526-5429f860-c570-11e7-864e-8ceccefb90ce.png">
<img width="814" alt="bildschirmfoto 2017-11-09 um 16 07 05" src="https://user-images.githubusercontent.com/6169308/32615535-585cc58e-c570-11e7-8db8-d96851927c52.png">

![bildschirmfoto 2017-11-09 um 16 09 31](https://user-images.githubusercontent.com/6169308/32616131-debf420e-c571-11e7-8277-8e96571dd823.png)

<img width="478" alt="bildschirmfoto 2017-11-09 um 16 21 35" src="https://user-images.githubusercontent.com/6169308/32615567-6424832a-c570-11e7-8abb-5c5c0e7f298c.png">

**Comment by dimaip** [comment]
Should no longer be the case. With CKE5 it's even possible to edit the anchor nicely.
