### ISSUE TITLE
Newline in inline text variable adds <p> tag that is never removed

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#1232]
When entering text inline in the neos-backend, the entered text is saved in the property as plaintext, e.g.:
`The text`

However, it is also possible to enter a linebreak, introducing a new paragraph. This results in the wrapping of the text in <p> tags, e.g.:
`<p>The text</p><p> </p>`

When the linebreak is removed afterwards, the p around "The text" is not stripped, even if the editor would expect it to be like in the first example. E.g.:
`<p>The text</p>`

This paragraph tag changes the appearance of the text after publishing without the editors intention to do so.

**Comment by klfman** [comment]
One could argue, that empty lines at the beginning and end of the entered text should be trimmed (and thus the generated <p>-tags should be omitted to avoid unintended behavior)

**Comment by mstruebing** [comment]
When I remove the line break the `<p>` tag gets removed too.
I will close this issue for now.
If this issue persists for you feel free to open it again.
