### ISSUE TITLE
Handling of backend exceptions (when uploading an image)

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1233]
At least some exception from the backend are not delivered correctly to the new UI / are not handled in a way that a meaningful error occurs. I don't know if this is a general problem or depends on the controller action called. 

If an image is uploaded, which cannot be validated you get the message:

![image](https://user-images.githubusercontent.com/642226/32714870-0d007f76-c850-11e7-80e7-4724f35e4189.png)

as the backend response is just 

`Validation failed while trying to call Neos\Neos\Controller\Backend\ContentController->uploadAssetAction().
`

**Comment by dimaip** [comment]
That should no longer be the case, please reopen if you see the problem again.
