### ISSUE TITLE
Switching to prettier

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#1237]
Hey pal's,

I've been using [prettier](https://github.com/prettier/prettier) in recent times more and more and found it to be a great enhancement for the developer experience. For those who don't know prettier, it is a automatic code-formater, in combination with a git-pre-commit-hook we can say goodbye to the all-to-common "TASK: Satisfy linter" commits / breaking builds due to ESLint.

Prettier's "no-discussion-just-do-it™"-strategy will of course cause situations where we might not be 100% satisfied with the way it formats the code, but I think that is the case with any code-style. The benefit of it in my opinion is that it reduces the entry-barrier for newcomers and reduces the stress for contributors a lot, they don' t need to take care of how the code is written since prettier will re-format it anyway.

ESLint will still be integrated, but all rules regarding code-style will be turned off and it will only be used for specific rules e.g. code-performance, best-practices, accessibility and so on.

**Comment by dimaip** [comment]
100% support this

**Comment by mstruebing** [comment]
If no one is against it I would do it and propose a concrete setup for this. 
Any objections?

**Comment by kitsunet** [comment]
I am super opinionated about git hooks, so 👎 from my side. I a) don't want anything touch my code without me seeing it (eg. separate commit that I can check) and b) don't want to run something any time I commit. b) will obviously be a much bigger thing if the ui is added ot the collection at some point.

Also can those rules be configured or is it a "one size fits it all"?

**Comment by mstruebing** [comment]
They can be configured a bit but I don't think it's possible to configure every rule.

I see your point regarding touching the code but that would mean we have to run prettier manually every time and this destroys the whole point of it. 
In this case we can stick to our current setup I think.

**Comment by dimaip** [comment]
In general I'd be in favor of it, but on the other hand I never had problems with linting as long as I had eslint plugin in my editor... So let's close this issue for now, if we are not all comfortable with it.
