### ISSUE TITLE
Improve the tests of the UI

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#1239]
During the sprint in Vienna I took the time to shift through the codebase and I think that we should really invest more time in the quality of the code and even more in testing.

By the time of writing this the whole codebase was 20-30% covered by unit tests, which makes it a big risk to refactor or even just change stuff. I do understand that we had to set some priorities to get to the 1.0.0, but in my opinion right after we push out the 1.0.0 we should really take our time to increase the quality, otherwise I fear that we end up roughly in the same spot as with the old UI codebase (messy code, not-that-well/non-tested and hard to get newcomers started in the codebase).  

I would propose to do the following:

**Unit tests**
- [ ] (unit tests) Use unit tests as the basis
- [ ] (unit tests) Set a coverage threshold of at least 70%
- [ ] (unit tests) Use snapshot tests as much as possible
- [ ] (unit tests) Use the `describe` / `it` style to have more flexibility in regards to setting and cleaning up tests
- [x] (unit tests)  Switch from sinon to jest's internal mock built-ins (Done in PR #1240 )

**Integration tests**
For sagas I would propose to use a combination of integration tests and snapshot testing, since the generator functions are mostly pretty modular/simple and are just a list of `select X, dispatch Y, do Z`. An example is provided in PR #1240 

**E2E tests**
I really do like the direction where we are heading and the tests introduced by dimaip, especially regarding the complexity of the current UI I really like to see stuff happening here! :100: 

**Examples (todo)**
* [Snapshot testing of action creators]()
* [Snapshot testing of reducers]()
* [Snapshot testing of selectors]()
* [Snapshot testing of redux-saga]()
* [Snapshot testing of React components]()

**Comment by grebaldi** [comment]
Closing this, because it's not really actionable. (Though tests can of course always be improved :slightly_smiling_face:)
