### ISSUE TITLE
Login page leads to "Page not found" after reload

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1245]
If your session times out and you reload the entire UI, you will land on the default login screen. After logging in, you currently won't be redirected back to the UI, but get stuck on a 404 page.

The error is most likely related to a missing default format in the Routes.yaml of the UI.

**Comment by markusguenther** [comment]
Could reproduce this but did not find the right point in the Routes or Routes.Backend.yaml
Tried to find out how the regular neos handles it. But think I need a little hint.

Log out put is something like this:
```
Router resolve(): Could not resolve a route for building an URI for the given route values.
    node => /sites/neosdemo@user-mguenther;language=en_US
    @action => index
    @controller => backend
    @package => neos.neos.ui
    @format => html
```

**Comment by grebaldi** [comment]
@kitsunet I found a fix for this, so I'd like to take over, if you don't mind

**Comment by kitsunet** [comment]
👍 Yep saw it
