### ISSUE TITLE
Enhance the babel preset for a better developer expirience

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#1247]
Just as the `create-react-app` babel preset does, we could enhance the developer experience by adding the `plugin-transform-react-jsx-source` and `plugin-transform-react-jsx-self` babel plugins, both add more valuable debug information to Reacts internal errors and should only be enabled in development environments.

Reference: 
https://github.com/facebookincubator/create-react-app/blob/master/packages/babel-preset-react-app/index.js#L56

**Comment by mhsdesign** [comment]
Thanks for the suggestion, I guess we forgot about that and esbuild has now overtaken this. #3200
