### ISSUE TITLE
UI doesn't handle uriPathSegment change correctly

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1248]
Currently, if you change the uriPathSegment of the current document, you cannot navigate to any pages beneath that anymore, see:

https://drive.google.com/file/d/15usMRYk2ZphsmzVuaA2sfjKF4Il-tAvb/view

**Comment by samuelhauser** [comment]
@grebaldi unfortunately, I can't reproduce that.

**Comment by dimaip** [comment]
Can not reproduce it either. Knowing the code it should handle those kind of changes just fine.
Please reopen if you can confirm that the issue is still there.
