### ISSUE TITLE
Revert the premature optimization of usage of React.PureComponent

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#1250]
Currently the codebase makes heavy use of `React.PureComponent`, as far as I can remember this was a premature optimization, and we should revisit this as soon as possible and only use the `PureComponent` class where it is necessary.

**Comment by skurfuerst** [comment]
I personally disagree on this one... However let's please discuss this in person / via a hangout :) :)

**Comment by dimaip** [comment]
Could @Inkdpixels provide more info and also @skurfuerst what do you disagree on exactly?

When PureComponents is bad?
If you pass an object as a prop (which we do quite often), it would always fail the strict equality check of shouldComponentUpdate of PureComponent, so it would first waste time on comparing props which would always result in the need of re-rendering a component. So if we just skipped this check, the things would be a tad faster.

So when is PureComponent a good idea? -- When your props are primitive values.

@Inkdpixels did you mean this or something else?

**Comment by Inkdpixels** [comment]
@dimaip is right, the point I was trying to make is, that currently most of the code relies on PureComponent and therefore additional computation happening on each re-render while we don't even know if we need it. 

This basically results in a optimization before we even knew if we had a problem and in fact this leads to slower applications most of the time.

**Comment by dimaip** [comment]
Since we have immutable data structures that are cheap to compare, I doubt this is really an issue for us currently.
In any case, do to something practical about this discussion we need measurements and some demonstration of potential performance loss.
Closing the issue for now, please re-open with new data.
