### ISSUE TITLE
After typing "<!--" in the editor, the backend breaks

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#1257]
If I type `<!--` in an inline editor and I reload the bckend, I cannot change the node anymore.

**Comment by kitsunet** [comment]
Can confirm, this bug exists.

**Comment by kitsunet** [comment]
we set config.basicEntities to `false` which is strongly discouraged by CK, don't know if that is on purpose, will try if something obviously breaks if I re-enable it.

**Comment by skurfuerst** [comment]
thanks <3 maybe check via git blame when it was set to False :) @kitsunet

**Comment by kitsunet** [comment]
Yep ofc, waiting for @dimaip because he set it but the reasons are unclear to me. Will check with him. Definitely fixes the issues though, so much I can say already.

**Comment by skurfuerst** [comment]
Thanks <3
