### ISSUE TITLE
User Interface glitches with MultiSelectboxes

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1270]
The component MultiSelectBox renders a text field for the search, some icons and an result dropdown for the search. In the ReactUI the leading icon is not in the same line like the other icon.

<img width="322" alt="bildschirmfoto 2017-11-15 um 16 01 27" src="https://user-images.githubusercontent.com/1014126/32843022-f5909ab2-ca1e-11e7-85d2-273fb98ef8b8.png">

The regular icons has a 10 pixel indention, but the dropdown for the result define a padding left of 16 pixels. Therefore everything is a bit shifted.

In the old UI the search looks a bit different and therefore it was no problem in the past I guess.

_Old UI:_
<img width="322" alt="bildschirmfoto 2017-11-15 um 16 04 39" src="https://user-images.githubusercontent.com/1014126/32843021-f56da3fe-ca1e-11e7-8f44-8895ad8909f5.png">

**Comment by markusguenther** [comment]
At the moment I don't want to change just the dropdown indention. Don't know the real impact and would discuss it first.

**Comment by skurfuerst** [comment]
@markusguenther we completely re-wrote the SelectBox and MultiSelectBox - could you please re-check the status in 1.0.0 and re-create/re-open the ticket if needed? That would be awesome :)
