### ISSUE TITLE
Clear search value on select item

### ISSUE THREAD

**Issue by samuelhauser** [neos/neos-ui#1273]
The search value should be removed, after select an item in the MultiSelect

<img width="302" alt="bildschirmfoto 2017-11-15 um 19 13 02" src="https://user-images.githubusercontent.com/1894064/32852701-108468f2-ca39-11e7-9a59-f2319b02a831.png">

**Comment by samuelhauser** [comment]
There is an other related bug. If you search in a searchable selectbox and choose a value, this value is not selected (the searchvalue remains standing)

**Comment by dimaip** [comment]
Both fixed.
