### ISSUE TITLE
More flexible NodeToolbar configuration

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#1274]
Currently the configuration of the NodeToolbar is static. More flexibility is required when you compose a page with different document (in this case the add button will ask the user to create a document, but in this case the use does not even know where this document is stored, ...)

I discuss the topic shortly with @grebaldi and I think more configuration option in the `ContentElementWrapping` prototype can be a nice addition, like bellow:

```
expression = Neos.Neos:ContentElementWrapping {
	nodeToolbar = true
	nodeToolbarOptions {
		create = true
		toggleVisibility = true
		copy = true
		paste = true
		cut = true
		delete = true
	}
}
```

With this option you can completly disable the NodeToolbar, or configure witch button is visible for the current path.

This missing piece code wise, is how to transport this configuration ... and here ... I can not really help ;)

**Comment by dfeyer** [comment]
A first good step, should be to disable the NodeToolbar from the inline editing if the property comes from a Document node type, it just don't make sense. 

And make it more configurable in second iteration, when it's a Content type

**Comment by dimaip** [comment]
I think this topic would need a further discussion and thinking through. @dfeyer could you please convert it into a discuss post or maybe even bring it up at the next code sprint?
Will close this issue for now.
