### ISSUE TITLE
Reset an value in SelectBoxEditor

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#1279]
Right now there is no way to reset the value set in a select box editor. We had a x-button in our old ui:
<img width="308" alt="bildschirmfoto 2017-11-16 um 12 51 51" src="https://user-images.githubusercontent.com/769789/32889919-091690ce-cacd-11e7-86b5-aed27677870e.png">
<img width="307" alt="bildschirmfoto 2017-11-16 um 12 51 37" src="https://user-images.githubusercontent.com/769789/32889920-0931f2ba-cacd-11e7-893f-d361716fdb10.png">

**Comment by samuelhauser** [comment]
I'll try this

**Comment by gerhard-boden** [comment]
Is somebody already taking care of that?

**Comment by samuelhauser** [comment]
@gerhard-boden I don't think so

**Comment by markusguenther** [comment]
Not sure but guess this already fixed it.

https://github.com/neos/neos-ui/pull/1295

**Comment by markusguenther** [comment]
The button was always there when the property is set. But was hidden caused it was laying under the chevron.

**Comment by markusguenther** [comment]
<img width="321" alt="bildschirmfoto 2017-11-20 um 21 44 25" src="https://user-images.githubusercontent.com/1014126/33040674-1490d1fe-ce3c-11e7-8dd3-7575bd590e88.png">

Fixed in current master

**Comment by gerhard-boden** [comment]
fixed https://github.com/neos/neos-ui/pull/1295
