### ISSUE TITLE
Switch to husky to manage git-hooks and write them in Node

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#1280]
I think we can simplify stuff a lot regarding the git-hooks right now by using [husky](https://github.com/typicode/husky) to manage / link our git-hooks as well as writing them in plain Node to keep them simpler since most developers don't know bash that good enough to keep them maintained.

**Comment by mstruebing** [comment]
As we are currently not using git hooks I close this issue for now.
