### ISSUE TITLE
Switch to yarn workspaces

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#1281]
I think we could simplify a lot of stuff if we would switch to yarn workspaces. Basically it offers first-class citizen support for mono-repos in the yarn package manager. While the feature is still marked as experimental I've used it in projects in the past months and found it to be really stable.

Benefits of the switch:
* Lerna does not create intermediate `package.json` files in the root / packages which can cause malformed / modified package.json files if the bootstrap process crashes unexpectedly
* The mono-repo holds a single `yarn.lock` file in the root
* You can use `yarn add` or `yarn remove` in sub-packages and the root `yarn.lock` will be adjusted/updated
* Yarn will automatically hoist/link dependencies
* We might could evaluate a change from `lerna` to `oao`

**Comment by mstruebing** [comment]
We are already switched
