### ISSUE TITLE
When no options are found in select box, there should be a message saying that

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1286]
See old UI

![image](https://user-images.githubusercontent.com/837032/32906826-6ebc4870-cafe-11e7-8a6f-4d6b1a527acd.png)

**Comment by markusguenther** [comment]
The selectbox component is under refactoring at the moment. So before starting this issue better ask in slack #project-ui-rewrite ...

**Comment by dimaip** [comment]
Blocked by #1362

**Comment by dimaip** [comment]
Done
