### ISSUE TITLE
Storybook mess up the styling

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1299]
The storybook override some styles like the button styling with browser defaults.
In neos we use normalize for getting rid of such influence. 

So it would be nice to have this also in the storybook. Then the components look like in the backend.

As example the selectbox reset button has rounded corners in Chrome.

<img width="178" alt="bildschirmfoto 2017-11-17 um 10 30 49" src="https://user-images.githubusercontent.com/1014126/32940383-cd5521d4-cb82-11e7-988b-a99b51430a7f.png">

**Comment by dimaip** [comment]
Fixed
