### ISSUE TITLE
Asset list does not support identical assets inserted multiple times

### ISSUE THREAD

**Issue by gerhard-boden** [neos/neos-ui#1317]
Since the identical keys are used for assets added multiple times, a javascript error occurs

**Comment by dimaip** [comment]
Blocked by #1362

**Comment by dimaip** [comment]
It works now. There's react warning about duplicate keys, but I guess it's ok for such exotic usecase. I don't think we should spend any more time on this. Feel free to reopen if you feel otherwise.
