### ISSUE TITLE
SelectBox unneeded separator

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1319]
The separator should only be shown when there are both cross and chevron visible:

![image](https://user-images.githubusercontent.com/837032/33009098-fad0960c-cdd5-11e7-9664-0b70d29b87fc.png)

**Comment by dimaip** [comment]
And even: 
![image](https://user-images.githubusercontent.com/837032/33010967-b42cee4c-cddc-11e7-8558-b0e3f40158a3.png)

**Comment by markusguenther** [comment]
In the old UI you have the separator on the chevron and the reset button ;)
So it was more or less a regression by me to just add this to the chevron

**Comment by dimaip** [comment]
So I guess you can just move it to the reset button and all would be fixed, right?

**Comment by markusguenther** [comment]
Try to adjust that ... hopefully soon ;)
