### ISSUE TITLE
Loading Backend in iFrame

### ISSUE THREAD

**Issue by samuelhauser** [neos/neos-ui#1332]
If you have an error in your page (e.g. missing fusion configuration for a nodetype), the backend is loadet multiple times in the iframe.

**Comment by klfman** [comment]
See https://github.com/neos/neos-ui/issues/1225 where I reported a similar issue

**Comment by mstruebing** [comment]
Can't reproduce but I remember this error.
Anyone else?

**Comment by skurfuerst** [comment]
Hey @samuelhauser,
we believe this is fixed with the stable 1.0.0 release together with Neos 3.3.

Please re-open as soon as the error appears again.
Thanks <3
Sebastian

**Comment by samuelhauser** [comment]
Hey @skurfuerst ,
Yesterday I had the same error again (release 1.0.3). I can't tell you exactly what I was doing. Could not reproduce the error, but it doesn't seem to be fixed yet.

**Comment by samuelhauser** [comment]
PS: It was not the same behaviour as #1225
