### ISSUE TITLE
Adjust style for loading icon

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1336]
Before #1319 the separator was attached to the chevron button and now I know again why I put the separator to the chevron.

For the reset button it is OK to have the separator as after element. But the loading icon uses same base and rotates. Therefore the loading icon has now again also a rotating separator.

<img width="315" alt="bildschirmfoto 2017-11-22 um 20 57 49" src="https://user-images.githubusercontent.com/1014126/33147669-dc14430e-cfc8-11e7-96ad-1fecd9bc0b1b.png">

**Comment by dimaip** [comment]
Thanks for spotting it, was about to open the same issue.
