### ISSUE TITLE
AssetEditor: icon and chevron for single asset mode

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1337]
- [ ] icon
- [ ] chevron shouldn't be shown when value selected

![image](https://user-images.githubusercontent.com/837032/33138427-c10ee23a-cfaa-11e7-996d-3301083e935a.png)

**Comment by markusguenther** [comment]
![bildschirmfoto 2017-11-29 um 23 13 50](https://user-images.githubusercontent.com/1014126/33401853-08e08982-d55b-11e7-9a24-29177818cb8a.png)

Had the plan to fix that, but can not reproduce it ;)

**Comment by dimaip** [comment]
Blocked by #1362

**Comment by dimaip** [comment]
@markusguenther I was referring to single asset mode, your editor supports uploading multiple assets

**Comment by dimaip** [comment]
Fixed
