### ISSUE TITLE
Subtree-toggle is always "open"

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-ui#1338]
Regardless, of whether a node in the tree is toggled to show subnodes, or not – the toggle-icon doesn't change. 
Hidden subnodes (closed folder):
![closed-folder](https://user-images.githubusercontent.com/6552092/33161968-2ca9dca8-d027-11e7-82b6-e8ffc9b338de.png)
Displayed subnodes (opened folder):
![open-folder](https://user-images.githubusercontent.com/6552092/33161969-2d97d66a-d027-11e7-8682-ff08b3d2efe2.png)

**Comment by dimaip** [comment]
Can confirm, thanks!

**Comment by dimaip** [comment]
fixed
