### ISSUE TITLE
Validation error message in inspector isn't translated

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-ui#1339]
The validation error message displays the translation key, rather than the translation:

![validation-error](https://user-images.githubusercontent.com/6552092/33166752-a0aeb236-d03b-11e7-8bfd-58da748271a3.png)

Also, due to the length of the text, the tooltip is cut off. The whole output is "content.inspector.validators.integerValidator.aValidIntegerNumberIsExpected"

**Comment by mstruebing** [comment]
I think this is the case for every inspector validator currently.
