### ISSUE TITLE
Switch workspaces throws an error

### ISSUE THREAD

**Issue by mirkokaufmann** [neos/neos-ui#1341]
If you want to switch workspaces the following error occurs:

<img width="138" alt="image" src="https://user-images.githubusercontent.com/2813269/33177434-de1d29aa-d062-11e7-92d4-08f04a42e536.png">

![image](https://user-images.githubusercontent.com/2813269/33177285-5b2e370a-d062-11e7-82e0-a52a50bf3a5a.png)

**Comment by dimaip** [comment]
Thanks, can confirm!

**Comment by dimaip** [comment]
Fixed
