### ISSUE TITLE
Add helper for style constants

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1355]
The brand constants in the build-essentials using a function called generateCssVarsObject to create the constant object.

The issue #801 and #793 also using this function but provide the function in the own file.
So maybe it would be better to have a helper in the build essentials that contains the function and we only use this helper for it.

**Comment by markusguenther** [comment]
After we merged the transitions and the zIndexes to one file I am not sure if we still need that. Depends a bit on how much the styleConstants.js is growing. Think when we come to the point that we spit up the constants file, we should use a helper.

Now it is more boilerplate like.

**Comment by dimaip** [comment]
I'd say we should dump all constants into one file for now, no need to over-engineer it at this point.

**Comment by markusguenther** [comment]
After having the constants at one place we skip the helper class ;)
