### ISSUE TITLE
Simplify tree rendering

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#136]
I just had a discussion with @grebaldi about the performance of the page-tree (and soon content-tree as well). Basically the current implementation lacks performance greatly in bigger projects, this is due to the fact that we describe and render the tree recursively. This makes the job of react pretty hardin regards to performance-optimization.

@grebaldi explained that he had a concept in mind which would solve this issue with rendering a flat hierarchy instead of deep lists which are recursive. This issue was already discussed on the last sprint by @mgoldbeck and @grebaldi but both saw other problems arise with this approach since a flat DOM structure won't describe the parent/child relationship in a good accessibility-friendly way.

I just did some research, since I was sure I've read something about some `aria-*` attributes which definitely can describe the relationship to other elements. My proposal would include using the `aria-owns` property to describe the relationships, as well as some other standardized attributes like `role` for semantics and `tabindex` for navigating through the tree with the keyboard.

```html
<div id="pageTree" role="tree" tabindex="-1">
    <a id="pageTree__1-1" href="/my/page" role="treeitem" aria-owns="pageTree__1-1-0" tabindex="0">Page 1</a>

     /* Groups */
    <div id="pageTree__1-1-0" role="group" aria-expanded="false">
        <a href="/my/page" role="treeitem" aria-owns="pageTree__1-1-1-0" tabindex="0">Page 1.1</a>
    </div>
    <div id="pageTree__1-1-1-0" role="group" aria-expanded="false">
        <a href="/my/page" role="treeitem" tabindex="0">Page 1.1.1</a>
    </div>

    <a id="pageTree__1-2" href="/my/page" role="treeitem" aria-owns="pageTree__1-2-0" tabindex="1">Page 2</a>
    <a id="pageTree__1-3" href="/my/page" role="treeitem" aria-owns="pageTree__1-3-0" tabindex="2">Page 3</a>
</div>
```

In constrast to the current approach, this would not incorporate recursive render operations. Instead the top most level will be rendered and is followed by groups of child nodes which are described by the id including the depth of the group.  This way we could create a better performance through the use of `shouldComponentUpdate` without using recursive equality checks and we also keep the DOM depth pretty low(3 layers max.), which is also good for performance. 

I am sure the example I've just written down has some errors, but it certainly gives you an idea that it is totally possible to go with a more flatter structure.

CC @dimaip @skurfuerst @ryzy

**Comment by dimaip** [comment]
So what are our plans regarding the tree? Do we implement it ourselves from scratch? Use some existing component?
What features do we need from the tree? Would we need multi-select?
/cc @mgoldbeck

**Comment by dimaip** [comment]
Just not to forget, this tree component looks full-featured and interesting: http://react-component.github.io/tree/
Performance seems pretty good too: http://react-component.github.io/tree/examples/big-data.html

**Comment by Inkdpixels** [comment]
Shall we close this one? @dimaip @mgoldbeck
