### ISSUE TITLE
Missing translation in Creation Dialog

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-ui#1363]
Translation key displayed in creation dialog. "Neos.Neos.Ui:Main:insertMode:" instead of "Insert mode:"

![missing-translation](https://user-images.githubusercontent.com/6552092/33367866-418664f2-d4f0-11e7-9f2a-25fe25dfa646.png)

**Comment by markusguenther** [comment]
Hmm in the master it is defined.

```
<I18n id="Neos.Neos.Ui:Main:insertMode"/>:&nbsp;
```

![bildschirmfoto 2017-11-29 um 15 14 19](https://user-images.githubusercontent.com/1014126/33379426-5ffa3b48-d518-11e7-86fe-6d027d447227.png)

If you are on the current master please provide more information where you get the broken dialog

**Comment by dimaip** [comment]
Can't reproduce either, will close for now, feel free to re-open.
