### ISSUE TITLE
Inline editable property triggers page reload on each change

### ISSUE THREAD

**Issue by soee** [neos/neos-ui#1366]
Having NodeType (in my case Page) property that is configured to reload page on change and is also inline editable, triggers page reload each time we change it's value while inline editing it. I think page reload should be triggered only if we press button to apply changes,.

**Comment by skurfuerst** [comment]
confirmed, quite annoying ;)

**Comment by skurfuerst** [comment]
That's something which would be nice to fix. Happens e.g. on neos.io when changing a blog post title inline.
