### ISSUE TITLE
German umlauts are broken in asset list 

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1367]
When you create a new asset lists and assign assets with umlauts like ü in the file name, then the listing in the asset editor is fine but in the page the umlauts are broken.

**Comment by markusguenther** [comment]
![bildschirmfoto 2017-11-29 um 23 16 21](https://user-images.githubusercontent.com/1014126/33420682-c7382968-d5af-11e7-8a9f-0e9908858bd0.png)

Maybe a screen is nice ;)

**Comment by dimaip** [comment]
Are you sure it's related to the new UI?

**Comment by markusguenther** [comment]
Ok you are right ... it also broken in the old UI.
Should I move the issue the Neos?

**Comment by kitsunet** [comment]
I think this was even a problem with this specific asset.

**Comment by markusguenther** [comment]
![bildschirmfoto 2017-11-30 um 12 36 45](https://user-images.githubusercontent.com/1014126/33428950-2b1d433a-d5cb-11e7-885b-f6540166adb0.png)

Nope otherwise I also created such a special asset ;)

**Comment by kitsunet** [comment]
Then yeah, probaly more of a general neos issue

**Comment by markusguenther** [comment]
And if you rename a file and upload the "new" file the flash message has the correct file name but the whole other components uses the "old" one. Seems that you check the image with a hash.

Also in the old UI.

**Comment by markusguenther** [comment]
Created an issue in the neos repository.
So I close this because the AssetEditor is not effected.
