### ISSUE TITLE
Drag and drop in asset editor does not work in FF and sluggish overall

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1368]
The asset editor suggests to reorder the assets by drag and drop, but the dropping does not work.

If this is just not implemented the drag should be disabled atm. Otherwise it seems to be a bug.

**Comment by dimaip** [comment]
Works for me. Though it feels a bit sluggish, compared to how it works in the references editor.

**Comment by markusguenther** [comment]
![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/1014126/33428610-bbde3624-d5c9-11e7-84a6-6a0189c8c956.gif)

**Comment by markusguenther** [comment]
And I am on the current master and used yarn build.

**Comment by dimaip** [comment]
I think you need to drag a bit higher, above next block. It works badly, but works.

**Comment by dimaip** [comment]
![peek 2017-11-30 15-15](https://user-images.githubusercontent.com/837032/33430370-5fae78ba-d5e1-11e7-987d-552e8b02b1c0.gif)

**Comment by markusguenther** [comment]
![assetlistneos2](https://user-images.githubusercontent.com/1014126/33430343-813c3b4a-d5d0-11e7-9485-153827941f6d.gif)

Hmm strange ... first gif was cropped obviously :/
I used the latest FF. Will test this later in other browsers.

**Comment by dimaip** [comment]
I can confirm it to be broken in FF. Also laggy in Chrome.

**Comment by dimaip** [comment]
Blocked by #1362

**Comment by dimaip** [comment]
Just checked, seems to work now. Could you test @markusguenther and re-open if the issues is still there?
