### ISSUE TITLE
LinkEditor doesn't accept external link

### ISSUE THREAD

**Issue by siggj** [neos/neos-ui#1376]
Internal link like node or asset work but external link (http://....) doesn't work anymore ?

**Comment by mstruebing** [comment]
I sounds like something related to the the `SelectBox` implementation and is currently reworked completely.

**Comment by dimaip** [comment]
Still relevant. Anyone wants to take care?

**Comment by dimaip** [comment]
Should have been fixed by now. Reopen if not.
