### ISSUE TITLE
Fix handling of CSS modules in jest tests

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1384]
https://github.com/justinsisley/Jest-CSS-Modules

Currently we have warnings like this, which are quite annoying:

![image](https://user-images.githubusercontent.com/837032/33596806-2d843c96-d9ae-11e7-9a27-9d86f01b4787.png)

**Comment by mstruebing** [comment]
As far as I can see, this isn't the case anymore. So I'm closing this for now.
