### ISSUE TITLE
"Discard" and "Discard all" should ask for confirmation

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#1387]
Recently I made a missclick where I hit "Discard" in the publish dropdown in the top right in the neos backend. Because "publish all" and "discard" are just next to each other, discarding should ask the user for confirmation before deleting changes.

**Comment by kdambekalns** [comment]
Coming from the "old" UI this will be missed, and it's just to easy to mis-click and hose a days' work. Or more.

**Comment by skurfuerst** [comment]
Ack, would be really useful! Let's try to plan this for the next milestone release.

**Comment by lorenzulrich** [comment]
Discard (without all) had no confirmation in the old ui. Are we adding it anyway?

**Comment by dimaip** [comment]
Don't know. If you don't have strong opinions that we should, I'd then fallback to doing it exactly how we did it before in the old UI.

**Comment by lorenzulrich** [comment]
In the case reported, the "Discard" button was accidentially hit because it is next to "Publish all". That case wouldn't be improved with having it in line with the old UI.

BTW, the old UI also has a confirmation dialog for "Publish all" (which can also lead to a disaster if accidentially clicked).

**Comment by klfman** [comment]
I would strongly argue for adding it.

It shouldn't be a lot of work to add a confirmation dialog, it's not in the way, and it's not an unneeded feature leading to a feature creep. And the standard use case would be "publish" anyways, so it's not in the way of the normal workflow.

However, destroying a days work is terrible.

**Comment by dimaip** [comment]
Anyone taking care of it? If not then I will.

**Comment by mstruebing** [comment]
I would want to do this if you not already started :)

**Comment by dimaip** [comment]
Ah sorry I just implemented it on my train ride :( Will push soon.

**Comment by mstruebing** [comment]
No problem, and great that you are back! :)

**Comment by klfman** [comment]
Thanks for taking care about it! :)
