### ISSUE TITLE
Allow Upload / MediaBrowser buttons to be hidden in Image/Asset editors

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-ui#1390]
https://github.com/neos/neos-development-collection/pull/1727 introduces the two flags `upload` and `mediaBrowser` that allow to hide the respective buttons in `Image` and `Asset` property editors.
This feature should be migrated to the new UI, too.

And I probably need a little help with this ;)

**Comment by dimaip** [comment]
Done
