### ISSUE TITLE
Strange behaviour of formatting drop down

### ISSUE THREAD

**Issue by fabiantschoek** [neos/neos-ui#1396]
"X" should probably not open and close the formatting drop down.

![dec-07-2017 10-13-58](https://user-images.githubusercontent.com/32840810/33707473-c0c5afb4-db37-11e7-8bea-76eb9897c922.gif)

**Comment by dimaip** [comment]
Hey, should be fixed here: https://github.com/neos/neos-ui/pull/1395
My PR got merged too soon yesterday I think.

**Comment by skurfuerst** [comment]
THX <3

**Comment by dimaip** [comment]
Could you guys test the PR? I think it's all good now, but any time you touch SelectBox it breaks in some unexpected place...

**Comment by skurfuerst** [comment]
I will :)

**Comment by dimaip** [comment]
Should be resolved now
