### ISSUE TITLE
Default Image in Asset List is missing

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1402]
In the Neos demo package the example asset list has one image that is missing.
In the old UI that was no problem. In the new UI we can have rendering issues in some browsers.

In the Firefox we get the alt tag rendered which looks broken ;)
In Safari we just get an empty box.

**Safari**
<img width="1806" alt="bildschirmfoto 2017-12-07 um 19 59 21" src="https://user-images.githubusercontent.com/1014126/33733266-91b19ace-db89-11e7-9e3c-3d3183977abf.png">

**Firefox**
<img width="1826" alt="bildschirmfoto 2017-12-07 um 19 59 08" src="https://user-images.githubusercontent.com/1014126/33733267-91dd7a90-db89-11e7-9ddc-f0fc082cc59b.png">

I guess a default Image/Icon would be nice when we can not render a asset preview.

**Comment by markusguenther** [comment]
After some investigation ... it is when you have asset where you can not create previews or when the file is missing. So no preview for an pdf for instance. So if we have no image type assest we should render render a icon or so.

 Whats you meaning?

**Comment by markusguenther** [comment]
This is also a issue in the "old" neos ui.

https://github.com/neos/neos-development-collection/issues/1791

**Comment by dimaip** [comment]
This is still rather an edge-case bug. Why isn't there a preview image? There should always be one, no?

**Comment by dimaip** [comment]
Actually I'd just close this. If there's broken link to an asset preview than something is broken with your system, and I don't think we should try to mask it.
If I'm wrong and there can be legitimate reasons for asset preview url to be missing, please re-open.
