### ISSUE TITLE
Searchfield in AssetList Editor is broken in Safari

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1403]
The Safari 11 does not render the search field like you would expect it.

<img width="318" alt="bildschirmfoto 2017-12-07 um 20 49 55" src="https://user-images.githubusercontent.com/1014126/33735737-796f14da-db90-11e7-9e06-87b92a65ca7b.png">

The old UI has no search here right?

**Comment by dimaip** [comment]
I think it's good to leave the search field there.
If it's broken there, it could be broken anywhere, so we need to fix it (shouldn't be hard).
