### ISSUE TITLE
Various tiny visual regressions

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1408]
- [ ] No border
![image](https://user-images.githubusercontent.com/837032/33755931-26740a64-dc04-11e7-9e30-e3521dfea3a0.png)

- [ ] Weird gap
![image](https://user-images.githubusercontent.com/837032/33755963-52888f9e-dc04-11e7-8a7e-5921d0aed66d.png)

- [ ] No separator "stick", looks boring
![image](https://user-images.githubusercontent.com/837032/33755989-67e37b24-dc04-11e7-9cba-f6a7374d6896.png)

**Comment by mstruebing** [comment]
Regarind the first point(No border): When I zoom to 110% within chrome I can see the border. In Firefox I can see the border already at 100%.
