### ISSUE TITLE
formatting panel isn't always displayed

### ISSUE THREAD

**Issue by fabiantschoek** [neos/neos-ui#1409]
Selecting text with the cursor beyond the displayed text results in a not shown formatting panel

![dec-08-2017 10-55-52](https://user-images.githubusercontent.com/32840810/33760667-b5794ff6-dc06-11e7-86b3-a1f39b38eef1.gif)

**Comment by dimaip** [comment]
So it seems the CKE editor is not even focused when you select text this way. Could be hard to fix, not even sure if we should.
Would say we can release 1.0 without fixing this.
@skurfuerst thoughts?

**Comment by dimaip** [comment]
@skurfuerst ping

**Comment by skurfuerst** [comment]
Hey,

I also think we cannot fix it currently properly. Let's see how many others have this issue.

Sorry @fabiantschoek  - thank you so much for the detailed bug report; unfortunately it's just very hard to fix!

Allt he best,
Sebastian
