### ISSUE TITLE
Move constants into one single place

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#1416]
Currently our constants are all over the place.

Some are in the `neos-ui-constants` package, some are in some post-css-config-file and others are coming from an external source (brandcolors), this is currently unmaintainable and unintuitive.

They should get merged into one single place to easier get found and used.

**Comment by dimaip** [comment]
💯

**Comment by markusguenther** [comment]
The brandcolors are just a dependency of the build essentials package. But it would be easier to understand when you have just one place and don't need to debug it to know all keys of the object.

**Comment by dimaip** [comment]
The problem with keeping all color constants in an external, independently versioned package is that it becomes really hard to add/adjust new colors.
I think it's fine to drop that dependency and just define it in-place, alongside other constants.
If our brand color ever changes, I would be the one responsible to update it :laughing:
