### ISSUE TITLE
Translations for "Enter 2 characters .. " in selctobox missing

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1417]
Seems that the translations for the Selectbox hint got lost with the latest refactoring.

![image](https://user-images.githubusercontent.com/642226/33832961-41bb894c-de7e-11e7-9a51-4f2866f623cc.png)

**Comment by dimaip** [comment]
What language is that?
In English it is translated. But not in any other language, as it is a new label.
In the old UI it wasn't localized at all.
