### ISSUE TITLE
Provide fallbacks for all I18n labels and make sure I18n looks good

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1422]
- move all of the I18n labels to the main Neos.Neos package, so they could be managed from one place
- add fallbacks for all labels

**Comment by dimaip** [comment]
For some obscure reason all labels in i18n registry are automatically fallen back to English if no national translation is available...

**Comment by kitsunet** [comment]
I think this is new in Flow to fallback

**Comment by skurfuerst** [comment]
OK, so we do not need to do anything, do we @dimaip @kitsunet ?

**Comment by dimaip** [comment]
@skurfuerst no, but I'd still move all labels to Neos.Neos. The question is to what version: 3.3 or 3.0 and upmerge?

**Comment by mstruebing** [comment]
As we agreed to be 3.3. compatible I would think 3.3 it is?

**Comment by skurfuerst** [comment]
hm, good question... I tend to have them starting in 3.0; as it just maximizes compatibility for users during the transitional period

**Comment by lorenzulrich** [comment]
So, if I understand this correctly:

* If a label is not localized to a (non-english) locale in Neos/Flow, it falls back to the English label anyway.
* Therefore it's sufficient not to have fallbacks within i18n usage inside the Neos UI

So the only question remaining here seems to be:

Should this commit https://github.com/neos/neos-development-collection/pull/1829 also be integrated to Neos 3.0/3.1/3.2 pre LTS-releases can also use the new Neos UI without missing labels?

**Comment by kitsunet** [comment]
I thought the 1.0 version of the new UI only works with 3.3 anyway?

**Comment by lorenzulrich** [comment]
Ah, you're right, according to `composer.json`, Neos 3.3 is needed. So I don't understand what would be left here.

**Comment by dimaip** [comment]
It would only fallback to English if English is in your fallback chain.

**Comment by lorenzulrich** [comment]
So the conclusion is to add fallbacks for all labels used?

**Comment by dimaip** [comment]
Yup.

**Comment by dimaip** [comment]
I think this is now fixed, reopen if not
