### ISSUE TITLE
Tooltips for validation and help messages have messed-up z-index

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1426]
This PR added a better tooltip component: https://github.com/neos/neos-ui/pull/997

While we don't want to use it for all the tooltips (for performance and other reasons), it makes sense to extract the updated tooltip component from there and use it for validation and help messages.

**Comment by dimaip** [comment]
Minimal thing that should be done is to fix the z-index of tooltips:

![image](https://user-images.githubusercontent.com/837032/34303445-6d094d7a-e746-11e7-8941-e34f58db8771.png)

**Comment by mstruebing** [comment]
Is this still the case?

**Comment by mstruebing** [comment]
Closed by #1937
