### ISSUE TITLE
No padding and not readable description in ListPreviewElement 

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#1429]
![selectbox](https://user-images.githubusercontent.com/12071529/33923780-562a38d2-dfd3-11e7-8b57-5581945c4525.png)

**Comment by dimaip** [comment]
My fault, will fix

**Comment by dimaip** [comment]
Hmm but I can't reproduce it:

![image](https://user-images.githubusercontent.com/837032/33924216-1638cbf4-dfe6-11e7-813c-aa09d9b9f266.png)

**Comment by mstruebing** [comment]
I've tested it again after rebuilding and it happens to me on chromium, chrome and firefox
I will test it at work later in case it's something with my setup

**Comment by dimaip** [comment]
Is that a references editor? Are you sure you are on latest master?

**Comment by dimaip** [comment]
As wait, I link editor I have that problem too. Thank! Will fix.
