### ISSUE TITLE
Double click on link opens ckeditor link window

### ISSUE THREAD

**Issue by darmstaedter** [neos/neos-ui#1437]
<img width="797" alt="bildschirmfoto 2017-12-13 um 15 24 31" src="https://user-images.githubusercontent.com/873002/33943553-c64181ca-e019-11e7-8c9b-3f16098107db.png">

**Comment by johannessteu** [comment]
@darmstaedter what would you expect instead?

**Comment by dimaip** [comment]
IMO we should remove that dialog completely, it's a leftover from CKE.

**Comment by johannessteu** [comment]
Our editors like it btw :D

**Comment by dimaip** [comment]
Duh, I just want CKE5 itegration asap.
@johannessteu what do your editors love about it over our native link editor?

**Comment by johannessteu** [comment]
It's for them just easier to have this little form to "configure" the link at one place. Linktext, url, (maybe no-follow/no-index as well etc .) For some it's also just easier to select the "type" e-mail as they don't know that you can do this my linking `mailto:...` and so on

**Comment by dimaip** [comment]
@johannessteu would be nice to learn from it and improve our solution

**Comment by dimaip** [comment]
Fixed in the CKE5 integration
