### ISSUE TITLE
Inline editable text shows "undefined" when empty

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#1443]
When I delete the contents of an inline editable text property it simply shows "undefined". This is a very technical word for editors.

Ideas:
* show a not so technical sounding empty-string-placeholder 
* create another attribute to be used in NodeType definitions alongside defaultValue, type, ui and validation that defines the empty-placeholder

**Comment by dimaip** [comment]
Thanks, fixed.
Are you aware of `aloha.placeholder` config? I think it does just what you ask for.
