### ISSUE TITLE
Make the initial screen Loading label translatable

### ISSUE THREAD

**Issue by soee** [neos/neos-ui#1459]
It would be great if the initial screen/overlay layer with `Loading` text could be tranlsatable.

**Comment by lorenzulrich** [comment]
As far as I can see from reading the code, "Loading..." is displayed at a very early stage of initializing the React application. Therefore the i18n labels are not fetched yet.

I suggest (and will push a PR) to use a spinner of the already existing `<Icon>` component.

![image](https://user-images.githubusercontent.com/1816023/35508350-595f82fe-04f0-11e8-9283-d3d82900a385.png)
