### ISSUE TITLE
Url parameters are not retained in the new UI

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1461]
It's not possible to navigate any urls that have parameters in the new UI (e.g. pagination) as the only thing that is transferred is the node context path. 

This is a pretty serious issue for editors when they want to navigate e.g. news archives.

**Comment by skurfuerst** [comment]
I do not really understand this one yet...

**Comment by soee** [comment]
I would like to see some workaround for it. When using a lot page pagination in backend, with new UI we have to use page tee to navigate and in many cases it is not as easy and quick as using pagination.

**Comment by dimaip** [comment]
@skurfuerst I have no idea how to solve it currently, and it's pretty important to fix it I think. See #1637 as an illustration of the problem.

**Comment by dimaip** [comment]
Basically the only solution that I see is to transfer the full page url in addition to node context path...
