### ISSUE TITLE
Missing hover states

### ISSUE THREAD

**Issue by danielkestler** [neos/neos-ui#1471]
A lot of hover states are missing, especially on buttons like "Apply" or "Publish". Maybe even more hover states should be introduced to enhance usability, e.g. on dropdowns, input fields or in the page tree.

**Comment by mstruebing** [comment]
It's not missing as the old UI doesn't have this too.

But I agree that would be enhance the UX

**Comment by kabarakh** [comment]
were you thinking about a mixin, an additional class, some scss-extendable-thingy with % or adding filter: brightness to every element with a hover?

**Comment by mstruebing** [comment]
Yes this was my thought but I didn't know how it would work out if we do it.

**Comment by dimaip** [comment]
I'd rather keep CSS as simple as possible and try to use SASS as less as possible. Instead I'd try to achieve reusability at React component level. In practice just using css variables is usually enough to get a DRY-enough code.
