### ISSUE TITLE
Empty select box offset in editor toolbar

### ISSUE THREAD

**Issue by danielkestler** [neos/neos-ui#1473]
If the paragraph style dropdown is empty, it is offset.

![bildschirmfoto 2017-12-21 um 12 13 05](https://user-images.githubusercontent.com/3976405/34253558-6d73c578-e648-11e7-8cab-d4c0b541e4cd.png)

**Comment by dimaip** [comment]
Can no longer reproduce (in Chrome, on latest master). If you can, please reopen.

![image](https://user-images.githubusercontent.com/837032/35790746-fef4a51e-0a54-11e8-8b16-2b5f3c82121c.png)

**Comment by darmstaedter** [comment]
The problem persists in Safari 12.1.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/873002/57644196-e0a8be00-75bb-11e9-8ef2-a3abaf103c0d.png">
