### ISSUE TITLE
Different fonts / mix of fonts in UI

### ISSUE THREAD

**Issue by danielkestler** [neos/neos-ui#1474]
As I understand, only the Content Module is rewritten in ReactJS, right? There seems to be different fonts in use (I know we talked about that topic before on Slack, and definitely, there have been adjustments and improvements regarding font rendering, but I think it is still not the right font in the new UI).

Look for the "g" letters.

Menu in Content Module:
![bildschirmfoto 2017-12-21 um 12 20 57](https://user-images.githubusercontent.com/3976405/34253818-789cc73c-e649-11e7-9ca7-548deeba26d7.png)

Menu in the rest of the UI:
![bildschirmfoto 2017-12-21 um 12 20 50](https://user-images.githubusercontent.com/3976405/34253825-7eeed6ac-e649-11e7-8c5e-7ddb697743c5.png)

I like the "old" font a lot more!

**Comment by mstruebing** [comment]
We are using Open Sans now, in the old UI Noto Sans was used.
I'm not entirely sure why we switched but I remember that there were some disscussion about that.

**Comment by danielkestler** [comment]
I think Noto Sans has a better readability.
But no matter the font: it should be identical throughout the UI.

**Comment by danielkestler** [comment]
It is not only the fonts, the UI is not consistent between the different (old and new) modules. Look at the arrow:

![bildschirmfoto 2017-12-21 um 15 40 27](https://user-images.githubusercontent.com/3976405/34260203-5d18f8fc-e665-11e7-87e3-598b8976a7a6.png)
![bildschirmfoto 2017-12-21 um 15 40 17](https://user-images.githubusercontent.com/3976405/34260204-5d2f4f8a-e665-11e7-93e9-e7031903a55d.png)

**Comment by dfeyer** [comment]
@danielkestler Media module is not powered by react ... currently

Aggre the we need to choose a new font ;) But please don't switch now, need some UX consideration.

**Comment by danielkestler** [comment]
My two cents: the new UI should not have switched the font from the start. Now we have an inconsistent UI for our users. So the easiest way would be to just go back to the look that all users know and is present in all other modules.

**Comment by dimaip** [comment]
I agree, I think we should revert the new UI font to NotoSans, before the UX guys decide on a new font.
Regarding arrows, I could live with that inconsistency.

**Comment by danielkestler** [comment]
This is still an “issue”... and while I am already working on the UI, I could make this change if you agree. What do you think?

**Comment by dimaip** [comment]
@danielkestler go for it!
