### ISSUE TITLE
Preview Central break is there is only one mode

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#1480]
We should simple hide the Preview Central if only one mode is available.

**Comment by skurfuerst** [comment]
@dfeyer is it broken when there is only one mode? Can you provide a screenshot? :)

**Comment by mstruebing** [comment]
I think it's not broken anymore.

![screenshot_2018-02-26_22-25-30](https://user-images.githubusercontent.com/12071529/36720263-cc961f26-1ba7-11e8-996a-5d3678248019.png)
