### ISSUE TITLE
Inline NodeToolbar on inline Editable fields on document nodes

### ISSUE THREAD

**Issue by samuelhauser** [neos/neos-ui#1481]
If you have an inline editable field on a document node, the NodeToolbar shows up (it shouldn't be)

**Comment by skurfuerst** [comment]
Hey,

Thanks for your report!
@samuelhauser could you please provide more detail on how to reproduce the issue? maybe with screenshots etc?

Thanks ❤️ 
Sebastian

**Comment by samuelhauser** [comment]
Hey @skurfuerst 

If you have a property on a documentNode as inline editable field, the toolbar appears, but it shouldn't

![documentnode](https://user-images.githubusercontent.com/1894064/34296243-fc4040fa-e711-11e7-8622-79dd5e81c4e7.png)

**Comment by DrillSergeant** [comment]
I can confirm this behaviour. This blocks me from activating the new UI in production projects as we have a lot of inline editable properties.

**Comment by dimaip** [comment]
Can confirm, will take care.
