### ISSUE TITLE
Missing the handle of LinkEditor to create an anchor link on same page 

### ISSUE THREAD

**Issue by mad99** [neos/neos-ui#1485]
### Problem
If I double-click on a new created Link there appears a popUp with Link-Editor with Title «Link».
within section Lin-Type there is a dropDown with
- URL (url)
- Anker in dieser Seite (anchor on this page)
- E-Mail (email)

Choose «Select the Anker in dieser Seite», there is an information about «(Keine Anker im Dokument vorhanden)» > «no anchor in document»

But There is no button or some other solution (what I can figure out) to create/define anchor in the current document.

### Detail
According to Dimitri Pisarev (https://neos-project.slack.com/archives/C0U0KEGDQ/p1513853812000255)
Neos' LinkEditor should handle creation of anchor links.

Guess there is some hidden or hard to find handling for create new anchor on the page.

### System
neos/neos 3.3.1
neos/neos-ui 1.0.3
neos/neos-ui-compiled 1.0.3
Browser: chrome, firefox, opera

### More information
Maybe there is also some problem with CKeditor dialog:
Dimitri wrote: « IMO it (the Popup) should be disabled as it's a duplicate of our LinkEditor basically.»
But I can't figure out whether this has a connection. (Maybe Dimitri knows more about how it is and had to be?)

### Hope issue is not pointless
Maybe I overlook the solution to create new anchor in page to connect with a link.
If that's the case, I'd appreciate any information on how to proceed.

**Comment by mad99** [comment]
### Problem
If I double-click on a new created Link there appears a popUp with Link-Editor with Title «Link».
within section Lin-Type there is a dropDown with
URL  (url)
Anker in dieser Seite (anchor on this page)
E-Mail (email)

Select the Anker in dieser Seite there is an information about «(Keine Anker im Dokument vorhanden)» > «no anchor in document»

But There is no button or some other solution (what I can figure out) to create/define anchor in the current document.

### Detail
According to Dimitri Pisarev (https://neos-project.slack.com/archives/C0U0KEGDQ/p1513853812000255) 
Neos' LinkEditor should handle creation of anchor links.

Guess there is some hidden or hard to find handling for create new anchor on the page.

### System
neos/neos 3.3.1
neos/neos-ui 1.0.3
neos/neos-ui-compiled 1.0.3
Browser: chrome, firefox, opera

### More information
Maybe there is also some problem with CKeditor dialog: 
Dimitri wrote: « IMO it (the Popup) should be disabled as it's a duplicate of our LinkEditor basically.»
But I can't figure out whether this has a connection. (Maybe Dimitri knows more about how it is and had to be?) 

### Hope issue is not pointless
Maybe I overlook the solution to create new anchor in page to connect with a link.
If that's the case, I'd appreciate any information on how to proceed.

**Comment by dimaip** [comment]
See https://github.com/neos/neos-ui/issues/1484#issuecomment-353434346

**Comment by dimaip** [comment]
Fixed with CKE5 integration
