### ISSUE TITLE
24 hour Format in DateTime-Picker

### ISSUE THREAD

**Issue by drlimbo** [neos/neos-ui#1502]
I can't find a way to change the DateTime-Picker to 24 hour format. 
`format: 'd-m-Y H:i'`

![datepicker](https://user-images.githubusercontent.com/1118783/34411357-6a9ccde8-ebd6-11e7-9b93-7802e7a7ac92.jpg)

**Comment by dimaip** [comment]
Missed this ticket. Closing in favor of #1503 as there are some more technical details.
