### ISSUE TITLE
Removing the target of a link does not remove the link itself

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1526]
## How to reproduce
* Mark a text
* Set a link
* Select the text
* Remove the link in the topbar
* Click somewehere else
* The link tag is still there

## Environment
Chrome / Mac
UI Version 1.0.4

**Comment by dimaip** [comment]
If you just erase the link and click away, it won't get removed, but will stay with an empty href, that was the behavior in the old UI too.
However you click on the link icon again, it would completely remove the link.
Closing for now, if you meant something different please reopen.
