### ISSUE TITLE
External Links are not possible

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1527]
## How to reproduce
* Select a text
* Enter an url, eg "https://neos.io"
* An empty link is rendered instead of the external link

Tested on Chrome / Mac
Version 1.0.4

**Comment by bwaidelich** [comment]
@daniellienert you'll have to click the suggestion for the link to be accepted:
![image](https://user-images.githubusercontent.com/307571/34769976-cb39b908-f5ff-11e7-806e-eda1563331c0.png)

But that one tricked me, too, and I think hitting [Enter] should work as well

**Comment by daniellienert** [comment]
@bwaidelich: Which version di you use? We are testing with 1.0.4 - and I see no relevant changes to master.

**Comment by bwaidelich** [comment]
Latest Neos, 3.3.3. But I recall that sometimes the suggestion was not there and only worked with http*s*.. very weird

**Comment by dimaip** [comment]
Yep, clicking outside would work too, but [Enter] just erases it. Hopefully it would not be hard to fix, but won't have time earlier than February.

**Comment by bwaidelich** [comment]
@mstruebing I didn't check, but are you sure that #1599 fixes the issue of the *LinkEditor*? it seems to me it only addresses the CKEditor, but that might be related of course

**Comment by mstruebing** [comment]
It is indeed related. External links are possible, but the enter problem still exists.
