### ISSUE TITLE
Unable to login if the default dimension has fallback

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#1529]
This happend with empts caches and empty user sessions only. If the default dimension use fallback the redirect to show the backend if wrong. The screen in white with a exception in the JS console (see https://gist.github.com/anonymous/fe508d55d0b2b0b51eb82a6195f8f591)

In my case the default dimension is english (en) with fallback to a single dimension (fr), so the link to the backend is:

https://localhost:8180/neos/content?node=/sites/references@user-dfeyer;language=en

But must be:

https://localhost:8180/neos/content?node=/sites/references@user-dfeyer;language=en,fr

An other report the same problem, see https://neos-project.slack.com/archives/C050C8FEK/p1515530890000368

**Comment by DavidSporer** [comment]
I have the exact same problem.
I've tried various language settings but default is de and fallback en in my case.

**Comment by dfeyer** [comment]
A new one https://discuss.neos.io/t/backend-whitescreen-after-upgrade-to-3-3/2987

**Comment by dimaip** [comment]
Could you guys try #1607? Could help to circumvent this issue.
@dfeyer @DavidSporer

**Comment by MCStreetguy** [comment]
I got the same error.
@dimaip I tried out your pr on my problematic installation but it did not solve the problem

**Comment by dimaip** [comment]
@MCStreetguy that's weird? Did you follow the steps written here? https://github.com/neos/neos-ui#contributing

**Comment by MCStreetguy** [comment]
@dimaip Ok maybe I missed something. I retried It now with your changes merged to the master branch and it works out just fine. Thus thanks a lot, you solved my problem which made me suffer for 2 weeks now since it happened in a production system of a customer.

**Comment by dimaip** [comment]
Cool! Please write if you notice something spooky about it.

**Comment by dimaip** [comment]
In that case I'll close the issue for now, please reopen if needed.
