### ISSUE TITLE
UI slick slider element overwriting frontend elements...

### ISSUE THREAD

**Issue by gsirin** [neos/neos-ui#1538]
Updated to 3.3 LTS today and realized that in UI 1.0.4 the slick slider component is interfering with slick sliders used in the frontend.

Could someone wrap the UI slick slider? Or am I missing a point and this issue is something related on my side?

![slick](https://user-images.githubusercontent.com/3208391/35000750-7e1507b4-fae5-11e7-9763-404e6b72959a.png)

**Comment by gsirin** [comment]
Hi,
any news on this? I am still experiencing the described problem with NEOS version 4.0.4 ... :/

**Comment by dimaip** [comment]
Hi! Sorry, no action so far. Hope someone is able to take over (I personally now in the middle of a bigger change).

**Comment by gerhard-boden** [comment]
@gsirin Sorry for the long waiting time, please retest after this is merged and a new UI bugfix release is out: https://github.com/neos/neos-ui/pull/1964

**Comment by gsirin** [comment]
@gerhard-boden Thank you for the fix - but unfortunately it did not work.
I am still experiencing the same issue with Neos 4.0.6.

![2018-07-24 09_53_05-window](https://user-images.githubusercontent.com/3208391/43124423-709a5cd4-8f27-11e8-8cbd-fdf86c08132a.png)

If I can do anything to help solving this, please let me know!

**Comment by dimaip** [comment]
Hey @gsirin, sorry for the slow feedback cycle...
I just re-tested on the latest version of the neos-ui, and I can not reproduce it: the slick slider styles are loaded for host only, can can not in any way influence the user site.
It's not enough to update Neos, you also need to update `neos/neos-ui` to the latest version.
![image](https://user-images.githubusercontent.com/837032/45265224-74842200-b450-11e8-9714-bf467cd2a4c1.png)

**Comment by dimaip** [comment]
Closing for now, will re-open on additional feedback how to reproduce it.
