### ISSUE TITLE
An node with unknown node type is not listed in the content tree

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#1540]
If a node type was not configured (e.g. the name of a nodeType changed), this nodetype is rendered as "Unknown NodeType", but it is not shown in the content tree.

**Comment by klfman** [comment]
can confirm this behaviour and I found it annoying when updating a test server with breaking changes that need manual repairs. It would be enough to log in, check the invalid nodes, recreate them and copy over the content (for example move the items from the contentCollection of the old to the contentCollection to the new node)
