### ISSUE TITLE
Update semantic-release

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1560]
## Description
The react-ui-components package uses semantic-releasein the travis configuration.
We are way behind the latest version and should update the package.

The current version uses node > 8 and we are actually on 6.10.
So we should follow the migration instructions for the update.

##Migration Guide

Install travis-deploy-once:

```
$ npm install --save-dev travis-deploy-once
```

Add thetravis-deploy-once script in your package.json:

```
"scripts": {
    "semantic-release": "semantic-release",
    "travis-deploy-once": "travis-deploy-once"
  }
```

Modify your .travis.yml to use travis-deploy-once.
Replace:

```
after_success:
  - npm run semantic-release
```

by:
Replace

```
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
```

For Yarn users or any project with a yarn.lock file, adds the --ignore-engines option to yarn install.
If the install is not defined you have to define it with:

install:
  - ```yarn install --ignore-engines```

Tried to remove it first #1558

**Comment by dimaip** [comment]
@markusguenther is this issue still relevant? I think you've been updating a lot of stuff lately.
