### ISSUE TITLE
React UI content dimensions selector wrong behaviour with 2+ dimensions

### ISSUE THREAD

**Issue by DrNik** [neos/neos-ui#1565]
Trying the new react UI  I noticed that the content dimensions selector menu does not wrok properly in 2+ dimensions context.

**Main issue:** choosing either of the dimensions leads to the next step in which you can choose what kind of copy to make (former "apply" button behaviour, now gone). This basically makes it impossible to choose combinations of dimensions and it even ignores constraints among dimensions.

**Secondary issue:** the order of choosing dimensions and the way of defining constraints feels some how odd. 
In the previous version we were defining constraints on the first dimension against the second (i.e. language -> country) and this resulted in choosing a language would filter allowed (choosable) countries. 
Now, on the contrary, the same exact dimesions configuration starts with filtered first dimension(language) therefore the order of choosing goes in the opposite way: I would choose country before language; but this could be solvable rewriting the constraints on the second dimension against the first.

Tried versions:
Neos: 3.3.3
React UI: 1.0.4

If any further info is needed please let me know and I'll be happy to give as much help as possible.

Thanks,
Nicola

**Comment by kdambekalns** [comment]
This is clearly a regression, switching dimensions when more than one dimension is configured is basically broken with the UI not waiting for (or veen having) an "OK" button in the switcher like before.

**Comment by dimaip** [comment]
@DrNik could you please test my PR trying to fix this issue?

**Comment by dimaip** [comment]
So I think the main critical issue is resolved. I've opened a separate issue for constraints: https://github.com/neos/neos-ui/issues/1611

**Comment by DrNik** [comment]
@dimaip I'll check it out right away, about the constraints it's not a big issue in my opinion, i just reported iit cause i did not know it was a consequence, a cause or just a coincident behaviour.

Thanks,
Nicola

**Comment by dimaip** [comment]
Yep, not that it's merged you can just test latest master.

**Comment by DrNik** [comment]
@dimaipI just made a quick check and the main functionality is back in place, unfortunately there's no reload on change therefore combining dimensions according to the constraints making it stiil unusable.
Anyways a good step forward thanks, I'll monitor the other issue.

Thanks,
Nicola

**Comment by dimaip** [comment]
@DrNik Hey, what do you mean by reload on change?

**Comment by dimaip** [comment]
@DrNik could you retest this? https://github.com/neos/neos-ui/pull/1615
Don't forget to build it locally.

**Comment by DrNik** [comment]
@dimap sorry I missed your previous comments.
Yes I meant "reload of constraints": the dropdowns would not change according to user choice, but you pointed it already out in #1611 (it was just a confirmation).

With "buld it locally" you mean I should follow "contributors guidelines" as in the README on github repo, right?!

Thanks,
Nicola

**Comment by dimaip** [comment]
> With "buld it locally" you mean I should follow "contributors guidelines" as in the README on github repo, right?!

Yes. But it's already merged, so you can just pull latest master to test.

**Comment by DrNik** [comment]
Ok I'll try it out right away, thanks again.

**Comment by DrNik** [comment]
@dimaip Great news, it seems to work correctly, obviously only on Neos >= 3.3.4.
On previous versions I receive a malformed json error, I believe due to the response is in "html-only".

Thanks
