### ISSUE TITLE
ckeditor indent/outdent is not configurable

### ISSUE THREAD

**Issue by paintsmultimedia** [neos/neos-ui#1566]
When activating the list elements for the ckeditor an indent and outdent button appear.
These buttons force p-tags to be indented by 40px, by adding a style property to the p-tag.
Therefore there is no way to manipulate indentions with pure css. For responsive websites it is necessary to have different indentions on the different breakpoints. Perhaps adding a class could be the better way. 
On the other hand there is no possibility to deactivate these buttons in node configuration There should be something like this:
ui:
    aloha:
        'list':
            'ul': true
            'indent': false
            'outdent': false

**Comment by dimaip** [comment]
How did it work in the old UI?

**Comment by grebaldi** [comment]
I'm closing this, because it is no longer reproducible in Neos UI >= 7.3. The Indent/Outdent buttons now respectively increase or decrease the nesting level of the list item under the current cursor position:

https://github.com/neos/neos-ui/assets/2522299/6c5ee183-0e74-4cb3-8ca1-193ee5de2d78
