### ISSUE TITLE
Group configured as collpased remains uncollapsed

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-ui#1567]
Custom groups in the node type selection list aren't collapsed, despite the configuration
Even if I manually collapse it, reload and open the node type selection list, it is again uncollapsed.

**Comment by maya-shines** [comment]
My project is on 1.0.11 and I'm still seeing this issue. Does the issue remain, or am I holding it wrong?
This is (more or less) the config in my project:
```    nodeTypes:
      groups:
        collapsedGroup:
          position: 500
          label: 'Don't use these'
          collapsed: true
```
The group remains uncollapsed and keeps opening up on reload, even if I manually collapse it...

Also, is it relevant that I'm observing this in the node type selection dialog and not the inspector?

**Comment by dimaip** [comment]
I think this is fixed. Please reopen if not.
