### ISSUE TITLE
Setting mediabrowser to false in File Selection Editor still enables search for existing files

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-ui#1571]
The upload form still allows to search through the existing assets, even though the configuration is set to mediabrowser:false. The actual Media Browser button is no longer there, but the functionality essentially remains, if the editor can still pick from the pool of assets by searching for them. 

Or... Did I misunderstand the feature?

**Comment by grebaldi** [comment]
Should be fixed with: https://github.com/neos/neos-ui/pull/3536
