### ISSUE TITLE
Custom Icon Classnames

### ISSUE THREAD

**Issue by lisakampert** [neos/neos-ui#1572]
### Description

There is another issue related to the SelectBoxEditor: We have an own IconFont, which is set based upon the `dataSourceIdentifier`. The JSON looks like this:
```
[{
    "value": "ai ai-500px", 
  "label": "500px  (brand ,social ,brand35)", 
    "icon": "ai ai-500px"
},
{
    "value": "ai ai-IE",
  "label": "IE  (browser ,internet-explorer ,brand ,browser3)", 
  "icon": "ai ai-IE"
}]
```
But in the Frontend, there are any Icons rendered in the SelectBoxEditor. It seems, that it is because of our custom names and that we don't use the FontAwesome names. Changing our JSON to a valid FontAwesome Icon, the Icon gets rendered properly.
Inspecting the Option in the SelectBox, it seems, that the ClassName does not get rendered, instead there is an "undefined"-class: `<i role="img" class="style__icon___3acxC reset__reset___2e25U undefined style__listPreviewElement__icon___3qFLa reset__reset___2e25U"></i>`

The CSS file is loaded in the UI, i added it to the Settings.yaml with:
```
Neos:
  Neos:
    Ui:
      resources:
        stylesheets: 
          ...
```
When adding the class name manually to the page, the icon gets rendered. So the problem is, that the class name does not get added to the SelectBox automatically.

#### Expected behavior

The icon's class gets rendered correctly. The Icon is shown in the Frontend

#### Actual behavior

Any icon gets rendered.
![selectboxeditor](https://user-images.githubusercontent.com/31652404/35282510-f843e9a4-0055-11e8-8e08-a10b1bcb92f0.png)

### Affected Versions

Neos: 3.3.3

UI: 1.0.4

**Comment by dimaip** [comment]
Thanks! Renamed, as this issue is not specific to SelectBox, but to any component using <Icon/>

**Comment by gerdemann** [comment]
Resolved in https://github.com/neos/neos-ui/pull/1580
