### ISSUE TITLE
Include "disable"-function for other Property Types in Inspector

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-ui#1577]
I saw that it's possible to set the boolean and textfield property editors to disabled. That's really convenient and I'd love to be able to apply it to the reference/references editors too.

**Comment by dimaip** [comment]
Hi @maya-shines! I'm not really aware of this feature? Was it implemented in the old UI? What's the usecase and how does it work? Could you provide some sample NodeTypes.yaml snippet?

**Comment by maya-shines** [comment]
Hey @dimaip,
welllll, according to the documentation, it's a feature? 😁 
As far as I understand it, it just implements the HTML property:

>Property Type: boolean BooleanEditor – Checkbox editor
>A boolean value is rendered using a checkbox in the inspector:
>
>'isActive'
>  type: boolean
>  ui:
>    label: 'is active'
>    inspector:
>      group: 'document'
>Options Reference:
>
>disabled (boolean)
>HTML disabled property. If TRUE, disable this checkbox.

Essentially, I want to set a property on node creation and then disallow the editors from changing it to prevent them from breaking things.

**Comment by dimaip** [comment]
@maya-shines thanks for explaining, needs to be implemented.

But in your case, why don't you just hide it from inspector? Or do you want them still to be able to see it?

**Comment by maya-shines** [comment]
@dimaip, that's what I ended up doing. But it feels odd that the "sibling"-nodetypes (they all inherit from the same nodetype) all have that property and this one appears not to. Even if the editors can't change it, I thought it would feel more transparent to show that it's there. ¯\_(ツ)_/¯

**Comment by dimaip** [comment]
@maya-shines makes sense, thanks for explaining!
