### ISSUE TITLE
Unable to create content when the content of a content collection are fetched from an other site

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#1578]
Tricky question, we have some document that show content from a content collection stored in an other document and from an other site. 

The editing work perfectly on the Ember UI. But for the new UI ... impossible to create content (the + button is disabled). Any clue on what can cause this issue ? Editing existing contents works, even creating conten bellow by ex. an two columns content element work fine. But creating content inside the content collection is disallowed

**Comment by dimaip** [comment]
Might be a silly question, but how do you actually render content from a different site in Neos? Custom Eel helper?

**Comment by markusguenther** [comment]
@dfeyer Bet this is still and Issue. Could you describe the problem a bit? Or could you provide code snippets to reproduce that :)

Thanks for your feedback :)
