### ISSUE TITLE
Initial load much slower than with legacy UI

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-ui#1579]
### Description

On a site (I am working on) with a lot of nodes, the initial load of the React UI delivers a document of more than 1.75 MB - which takes 80 seconds to render (don't mind the absolute value, but keep it in mind for comparison.)

#### Expected behavior

The React UI should not load slower than before, especially because everyone claims it is so mch faster.

#### Actual behavior

<img width="594" alt="neos_content_node____" src="https://user-images.githubusercontent.com/95873/35434737-74e8950c-0288-11e8-82e5-19fd37572e74.png">

The old UI (with a `loadingDepth` of 4!) loads in 430kB and 2.5 seconds and then fetchs the tree in 320kB taking 4 seconds (but since the UI is alerady visible it feels much faster, perceived performance and all.)

So even when combined (750kB and 6.5 seconds) the old UI loads 12 times faster and produces only 42% the amount of data (give and take a little.)

### Affected Versions

Neos: 3.3.3
UI: 1.0.4

### Workaround

When lowering the `loadingDepth` of the node tree to 2 (from the default value of 4), the site goes down to 230 kB (and takes 8 seconds to produce.)

But that cannot be the solution we want our customers to be using, eh?

**Comment by dimaip** [comment]
The issue here is not JS size. The PHP code to render nodes for the UI is super slow.
This is related: https://github.com/neos/neos-ui/issues/1508

**Comment by kdambekalns** [comment]
Ok, no wonder… this is coming from
```      initialState:
        changes:
          pending: {  }
          processing: {  }
          failed: {  }
        cr:
          nodes:
            byContextPath: '${Neos.Ui.NodeInfo.defaultNodesForBackend(site, documentNode, controllerContext)}'
            siteNode: '${q(site).property(''_contextPath'')}'
```
calling

```    public function defaultNodesForBackend(NodeInterface $site, NodeInterface $documentNode, ControllerContext $controllerContext)
    {
        $flowQuery = new FlowQuery([$site, $documentNode]);
        $nodes = $flowQuery->neosUiDefaultNodes($this->baseNodeType, $this->loadingDepth)->get();

        $result = [];
        foreach ($nodes as $node) {
            $this->renderNodeToList($result, $node, $controllerContext);
        }

        return $result;
    }
```

which in turn… 🙈

**Comment by dimaip** [comment]
See my analysis in the issue linked

**Comment by dimaip** [comment]
I have an idea, I'll give this issue a try @kitsunet

**Comment by kitsunet** [comment]
Add me if you have soemthing to review.

**Comment by kitsunet** [comment]
More a Backend thing, but an idea could be (looking at the aspect) to not check privileges that the current user has a grant for anyway, because why check if the node falls under that privilege if it's granted. That could be a low hanging fruit speed improvement.

**Comment by skurfuerst** [comment]
@kitsunet we can close this issue now; can't we? :-)
