### ISSUE TITLE
Switch to seamless-immutable

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#159]
The larger the code base gets, the more evident I find, that all this `toJS()` back and forth conversion we're forced to do with Immutable.js becomes an issue. Especially when we're thinking about exposing such data structures as API.

Luckily, there are some guys who have experienced the same kind of friction with Immutable.js and developed a pretty nice solution to get around that.

Here's the article: http://tech.noredink.com/post/107617838018/switching-from-immutablejs-to-seamless-immutable

Here's the code: https://github.com/rtfeldman/seamless-immutable

I think that `seamless-immutable` would be a great solution for us.

**Comment by skurfuerst** [comment]
we won't probably doing this for 1.0.0. For us immutable.js now works well.
