### ISSUE TITLE
Unable to change a picture or text after copying an element on neos.io

### ISSUE THREAD

**Issue by lisaguenther** [neos/neos-ui#1590]
### Description

Unable to change a picture or text after copying an element on neos.io https://www.neos.io/events/neos-conference-hamburg-2018.html

### Steps to Reproduce

1.  I copied a two column content 
2.  tried to select the picture (also in the tree) 
3.  When I try to click in the element it always links me to somewhere.

#### Expected behavior

By trying to select the element I wanted to change the picture and text in the right general content change column.

#### Actual behavior

I get to a blank window.

### Affected Versions

I don't know. On neos.io

**Comment by dimaip** [comment]
Hi @lisaguenther! I think it's not related to moving a node. The issue happens when I select any Image node on the neos.io website. I couldn't debug it further, as there are no sourcemaps in production currently. Will try to reproduce it locally.

**Comment by kdambekalns** [comment]
It even happens when selecting an image node in the structure tree.

<img width="609" alt="console-output" src="https://user-images.githubusercontent.com/95873/36141938-e1b21664-10a6-11e8-9f5a-3bf92a64290d.png">

**Comment by kdambekalns** [comment]
In case it's fixed with the most current version, https://github.com/neos/Neos.NeosIo/pull/195 might help already.

**Comment by dimaip** [comment]
@kdambekalns yep once it's merged I'll debug it in production

**Comment by kdambekalns** [comment]
Not fixed, at least not for me. Maybe your caches will be cleaner than mine, if that's an issue… :)

**Comment by dimaip** [comment]
@kdambekalns it was not supposed to fix it, but now we have sourcemaps to debug the issue even in production build. Will take care this evening.
