### ISSUE TITLE
CK-Link-Editor Searchable Selectbox Header to small in FF 58

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#1609]
![screenshot_2018-02-05_07-18-55](https://user-images.githubusercontent.com/12071529/35790884-e433dc14-0a44-11e8-830a-2ed0d0fb1169.png)

**Comment by dimaip** [comment]
Ah, I guess it's that extra pixel I added, in Chrome it looks good.

**Comment by mstruebing** [comment]
Did you remember why you added this pixel?

**Comment by dimaip** [comment]
@mstruebing to make it look good in Chrome... but I think it could be subtracted, then it will be cropped by 1px in Chrome, but that'll still look ok.

**Comment by mstruebing** [comment]
![screenshot_2018-02-27_13-39-39](https://user-images.githubusercontent.com/12071529/36729177-990966b0-1bc3-11e8-9ea5-03ef77802839.png)

That's a screenshot from chrome, without that extra pixel. 
Maybe I'm blind but for me it seems good
