### ISSUE TITLE
404 after editing `uriPathSegment` alongside any other property with `reloadIfChanged`

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#1612]
If you edit the `uriPathSegment` of a document and additionally edit another property, that is configured with `reloadIfChanged: true`, the UI will show a 404 error page in the guest frame.

Currently, `reloadIfChanged` triggers a simple `window.location.reload()` call in the guest frame, which of course leads to a 404 in case the URI of the guest frame document changed in the meantime.

My suggestion would be to change the routing configuration for the guest frame entirely and leave the client side reload as it is. 

There's absolutely no benefit to rely on frontend-like URIs for the frame, since these are inivisible to the user anyway. This could be an opportunity to route all guest frame requests through a special guest frame controller, instead of the usual `Frontend\NodeController` of the Neos package.

**Comment by MCStreetguy** [comment]
Happens for me too.

**Comment by dimaip** [comment]
@grebaldi will it work with things like pagination in user content?

**Comment by skurfuerst** [comment]
@dimaip @grebaldi I'd keep the iframe URLs as they are currently, to ensure pagination and other API calls still work. We cannot IMHO transfer all URLs routing-wise in the iframe to another endpoint...

Except you have another idea :)

**Comment by dimaip** [comment]
@skurfuerst in fact I'd propose the oposite, and switch the host routing to frontend urls as well.

See my comment in slack: https://neos-project.slack.com/archives/C0U0KEGDQ/p1519229095000153

**Comment by skurfuerst** [comment]
I see the elegance of your solution @dimaip :)
