### ISSUE TITLE
Inspector editors block loading of the iFrame

### ISSUE THREAD

**Issue by gerdemann** [neos/neos-ui#1616]
### Description

We have a lot of reference editors on a page and the UI waits until all requests are ready before it runs the iFrame.

### Steps to Reproduce

1. Add reference editors or image editors on your Document-NodeType
2. Open or reload the Neos-Backend

#### Expected behavior

Requests from the backend UI should not block the loading of the iFrame.

#### Actual behavior

The requests from the backend UI block the loading of the iFrame.

Here a Screenshot of the requests:
![Screenshot of requests](https://cdn-pro.dprcdn.net/files/acc_496443/VEYKRo)

### Affected Versions

Neos: 3.3.3

UI: 1.0.4

**Comment by dimaip** [comment]
Just check, I do not see inspector requests blocking anything. Iframe starts loading about 200ms after the editors started fetching data, but before they have finished:

![image](https://user-images.githubusercontent.com/837032/36482257-c3fef956-1723-11e8-9bc3-834ae754c71c.png)

There's another problem, we should actually start loading iframe way earlier, but there's a different issue for that, which is not that easy to solve: #1020

Feel free to re-open if you got additional info.
