### ISSUE TITLE
formatlesspaste not working correctly in CKEditor

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-ui#1620]
### Description

Formatless paste does not work reliably.

It seem as if CKEditor (and/or our bindings to it) do not allow to completely block the lesaking of markup into Neos through copy and paste. In `removeTags.js` someone left this comment:

> For some reason, it does not strip out `<p>` Tags; not sure why...

### Steps to Reproduce

Using a config like

    ui:
      aloha:
        'formatlesspaste':
          'button': FALSE
          'formatlessPasteOption': TRUE

and then pasting something with formatting, the formatting is not removed.

#### Expected behavior

The formatting is removed as configured.

#### Actual behavior

The formatting was not removed as expected.

### Affected Versions

UI: 1.0.4

**Comment by klfman** [comment]
Can confirm this bug

**Comment by dimaip** [comment]
Will try to look into it in a few days, if nobody else does before me.

**Comment by klfman** [comment]
@dimaip any progress on this topic? It's not exactly urgent but would be nice to have it fixed :)

**Comment by dimaip** [comment]
@klfman hey, nope, haven't touched it yet, been fixing other stuff. Feel free to take over if you wish.

**Comment by klfman** [comment]
@dimaip Sorry, lacking the skill to fix stuff in neos yet :)

**Comment by mhsdesign** [comment]
I think we can close this as we now use ckeditor5 and not aloha anymore ^^

but there still seems to be a similar issue https://github.com/neos/neos-ui/issues/2918
