### ISSUE TITLE
RFC: Exchange `package.json` with `make` as build tool

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#1629]
I'm currently using more and more Makefiles as make ist mostly available on every system and has built-in features like command completion for like every shell. Most developers are familiar with it - who have never typed a `make install`?

As our project grows I think it would be good to remove the scripts from our `package.json` inside a Makefile. That way it would be easier to write small scripts or help messages.

**Comment by dimaip** [comment]
Ah, sorry, missed this and left a comment on the PR.
Actually I think it's more common for JS projects to make use of npm scripts, at least I have a very shallow background with make, and it feels really unix-y to me... But whatever works, don't really mind, if you feel it will be easier to use I should trust you judgment here (wait, I'm writing it to a person who regularly uses vim... :D)

**Comment by mstruebing** [comment]
I just find it more convenient when writing little scripts and stuff instead of doing it in the `package.json`, especially when this grows. 
I mean it would be possible to write bash scripts (or any other language) and trigger them via npm/yarn. 
If the majority is against introducing make I would suggest that we should write more complex scripts in bash or node or whatever to make setup, releasing etc. easier and more smooth and trigger them via npm.

**Comment by dimaip** [comment]
As said, I remain neutral on the issue, if nobody is against it then I don't mind whatever tool.
