### ISSUE TITLE
Changing pagination reloads content iFrame

### ISSUE THREAD

**Issue by lorenzulrich** [neos/neos-ui#1637]
### Description

When using pagination inside Neos, the content iFrame is reloaded after switching to another page, leading to the first page again.

### Steps to Reproduce

1. Create a component with pagination, e.g. a `Flowpack.Listable:PaginatedCollection`
2. Switch to page 2

#### Expected behavior

Records of page 2 are displayed

#### Actual behavior

Records of page 2 are quickly displayed, but a reload is then triggered leading back to page 1:

![image](https://user-images.githubusercontent.com/1816023/36249844-4a94848c-123c-11e8-9f03-93a11898c60a.png)

The reason seems to be the method `updateIframeUrlIfNecessary()` of `Host.js`.

### Affected Versions

Neos: 3.3
UI: 1.0.7

**Comment by dimaip** [comment]
Closing in favor of #1461
