### ISSUE TITLE
Login to Neos with new ui does not work with IE11

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-ui#1638]
### Steps to Reproduce

1. Use Internet Explorer 11 to log into a Neos 3.3 (with new React UI)

#### Expected behavior

I am logged in an can edit content

#### Actual behavior

I get a white browserpage

### Affected Versions

Neos: 3.3.4

UI: 1.0.7

**Comment by lorenzulrich** [comment]
Currently, the Neos UI does not work at all in IE11. The reason might be the same problem discussed in detail here: https://github.com/facebook/react/issues/8379
We will need to try to find out which is the best solution.

**Comment by DrillSergeant** [comment]
Thank you guys.
