### ISSUE TITLE
No possibilty to remove inline links

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#1639]
Inline links set via CKEditor cannot be deleted currently.

**Comment by dimaip** [comment]
Can not reproduce...
![peek 2018-02-19 12-22](https://user-images.githubusercontent.com/837032/36370355-abd8be30-156f-11e8-936a-dd94fc5afc63.gif)

**Comment by mstruebing** [comment]
Magic! Thx!

**Comment by dimaip** [comment]
I'd rather call it a UX issue if people have trouble understanding how to remove links...
