### ISSUE TITLE
RFC: lazy-load policies

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1646]
Currently rendering node information is dead slow due to policy checking. We can't instantly make it fast, it's a hard task to speed it up.

So I propose to lazy-load it.
On initial page load we just render info about current documentNode.
Then we lazily request all nodes needed to render the tree. It happens quickly, as policies are not applied at this moment (with an exception of `NodeTreePrivilege`).
And then the policies are lazily loaded as another json request. It doesn't really matter how long it would take, as you only notice policies when creating new nodes and doing stuff like that.

**Comment by skurfuerst** [comment]
Makes sense :) I also checked the numbers (and after a wrong benchmark on my side) came to the same conclusions :)
