### ISSUE TITLE
Re-add node type attribute to content element wrapping

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-ui#1647]
Previously the `NodeType` was part of the `ContentElementWrapping`:
```html
<div data-node-_node-type="Some:Node.Type">...</div>
```
We use that for example in the Form Builder to improve Backend UX: https://github.com/neos/form-builder/#adjust-appearance-of-the-form-builder

With the new UI that attribute no longer exists so CEs can't be targetted via CSS/JS based on their type.

I suggest to re-add the attribute, but call it `data-__neos-node-type` to be in sync with the other attributes

**Comment by lorenzulrich** [comment]
+1
