### ISSUE TITLE
SelectBoxEditor cannot set reference to entity

### ISSUE THREAD

**Issue by lorenzulrich** [neos/neos-ui#1667]
When using a DataSource to select an entity as described [here](https://discuss.neos.io/t/guide-how-to-select-entities-in-the-inspector-neos-2-3-lts/1664), e.g. through [this package](https://github.com/visol/Visol.Neos.AssetCollectionHelpers) (which is not yet on packagist), the selected value is lost on clicking apply and cannot be stored at all.

**Comment by lorenzulrich** [comment]
A relation with #1536 is possible.

**Comment by DrillSergeant** [comment]
I can confirm this, we experience exactly the same issue.

**Comment by dimaip** [comment]
So, there are two things here.
1. I fixed SelectBox to work with objects and integers.
2. Using `json_encode` here is no longer needed, if I remove it starts working: https://github.com/visol/Visol.Neos.AssetCollectionHelpers/blob/master/Classes/DataSources/AssetCollectionDataSource.php#L57
If you want to support both old and new UI you got to do smth like this in the data source:https://github.com/neos/neos-ui/blob/master/Classes/Neos/Neos/Ui/TypeConverter/UiDependentImageSerializer.php#L47

**Comment by dimaip** [comment]
Guys, there are two issues here.

1. SelectBox editor didn't work with non-string values. It does now.
2. The horror of `typeConverter`s. See https://github.com/neos/neos-ui/issues/1688

In practice that means that to get a working entity selectbox, you can just remove `json_encode` from your datasource and it would start working.
Please confirm!

**Comment by DrillSergeant** [comment]
Yeah, works when removing the json_encode in the datasource. Thank you.

**Comment by lorenzulrich** [comment]
Can confirm this, too. Thanks!
