### ISSUE TITLE
Dynamic configuration doesn't work for group or editor

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-ui#1682]
The feature #1618 does not work for setting the inspector group or editor (as the example in the PR shows) because that part of the configuration is extracted before the processing happens. It would be nice though to be able to do that.

**Comment by kitsunet** [comment]
@dimaip This is it :)

**Comment by dimaip** [comment]
I looked into this a while ago, and it's not easy to fix without huge render performance penalty.
I propose to not support moving a property dynamically between groups, but instead to add an additional option to hide and editor, e.g.
```
  ui:
    inspector:
      hidden: true
```

**Comment by dennisirmscher** [comment]
@dimaip Would love to have something like this for dynamically show properties. I have to deal with circumstances with somehow depending properties quite often and it would be charming and less confusing for editors to display only the needed ones.

**Comment by dimaip** [comment]
@dennisirmscher wouldn't this help https://github.com/neos/neos-ui/issues/1682#issuecomment-386269035?

**Comment by dennisirmscher** [comment]
@dimaip It totally would! :)

**Comment by dimaip** [comment]
@dennisirmscher I think it would be quite trivial to implement here: https://github.com/neos/neos-ui/blob/master/packages/neos-ui-editors/src/EditorEnvelope/index.js#L146
E.g. check for `hidden` and then just `return null`.

**Comment by dennisirmscher** [comment]
All right, this is working so far. I added a property `hidden` to the inspector like this (shortened):

```
'foo':
  type: boolean
'image':
  ui:
    inspector:
      hidden: 'ClientEval:node.properties.foo ? false : true'
```

The property image now disappears if `foo` is set to false:

![dynamic configuration](https://user-images.githubusercontent.com/16836984/45105453-8f932100-b134-11e8-9f36-981d12943eb4.gif)

Of cause the value of the property `image` won't get removed as it only get's removed from the inspector. I don't think it would be a god idea to the delete the value but let the developer take care of dealing with the properties.

@dimaip wanted to discuss the naming of the property as `hidden` might not be the best option. Any other suggestions?

**Comment by dimaip** [comment]
Yeah it definitely shouldn't mess with the value.
Next steps:

- [ ] create a PR
- [ ] create a documentation PR in https://github.com/neos/neos-development-collection/
- [ ] check if it's needed to adjust the NodeTypes schema for this property

**Comment by dennisirmscher** [comment]
> The feature #1618 does not work for setting the inspector group or editor

I just found out, it works for changing the editor on the fly. Here is an example of switching between the LinkEditor and the TextEditor:

![image](https://user-images.githubusercontent.com/16836984/45145128-37a1fc00-b1c0-11e8-8ccf-e5848759af11.png)

But I guess this can break quite quickly, e.g. when entering a value in the TextEditor the LinkEditor can't handle.

**Comment by dimaip** [comment]
Yeah, this behavior should be used with caution. Though on compatible data types it could work quite well.
`ClientEval:` is a super powerful low-level hack basically.
