### ISSUE TITLE
Make loading "spinner" a color-changing Neos logo

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-ui#1686]
I imagine a Neos "N" going through several color variations as a loading animation. Would look so much cooler and more Neos than the "ring" we have now.

**Comment by skurfuerst** [comment]
sounds awesome :D

**Comment by mstruebing** [comment]
As the Neos logo is already in Font-Awesome and we are on this version internally it should be possible with to much effort.
https://fontawesome.com/icons/neos?style=brands

**Comment by markusguenther** [comment]
The PR has been merged so I guess this ticket can be closed :) 

cc @mstruebing

**Comment by mstruebing** [comment]
No it's not. I've closed my PR in favour of https://github.com/neos/neos-ui/pull/2188 which is still open. :+1: 
Or did I miss anything?

**Comment by mstruebing** [comment]
Now it is :D
