### ISSUE TITLE
Hardcoded conversion of data coming from the UI

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1688]
edit: Currently we serialize data with `Neos\Neos\Service\Mapping\NodePropertyConverterService` and de-serialize it with `Neos\Neos\Ui\Domain\Service\NodePropertyConverterService`.

`Neos\Neos\Ui\Domain\Service\NodePropertyConverterService` has hardcoded converting of data coming from the UI.

**Comment by kitsunet** [comment]
`userInterface.inspector.dataTypes` is totally sensible if you need to represent any arbitrary data as node property
unless we find another way to do that

**Comment by dimaip** [comment]
Updated the issue to reflect our discussion in Slack.

**Comment by dimaip** [comment]
Comment from @skurfuerst:

```
problem was that the old and new Ui use a different serialization format -the old ui has to work with strings only while the new UI “understands” objects (e.g. for images). Back then the code in the old UI was static; so I had to copy and adapt it. Seems the old ui is configurable now, great! However I guess it is not possible to just reuse all converters from the old ui code because of the different format.
```

**Comment by dimaip** [comment]
Will close for now, as it's not clear what to do about it.
