### ISSUE TITLE
Reloading the current document node

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-ui#1689]
I often want to reload the current document node while I am in the backend. When I click on the current node in the document tree, nothing happens.
Right now I reload the current document by loading another document and then again the recent document. Or I reload the whole browser tab when reloads the whole ui.
Both workarounds are not really nice to work with.

Is it a bug that you cannot reload the current document node by clicking on it in the document tree?

### Affected Versions
Neos: 3.3.6
UI: 1.0.8 (but also before)

**Comment by mstruebing** [comment]
Why do you want to do that?

**Comment by DrillSergeant** [comment]
While development I often change things like rendering, properties, translations and need to reload the current document node to see my changes in action. Some of the changes needs a complete UI reload but many of them just need to reload the current document node.

In my company every developer has this need. Do you work a different way?

**Comment by dimaip** [comment]
I've heard many people expected exactly the described behavior. It's a UX issue, not a bug per se, but I think we should fix it, shouldn't be hard.
