### ISSUE TITLE
Unset or empty inspector groups still show up

### ISSUE THREAD

**Issue by MCStreetguy** [neos/neos-ui#1707]
### Description

When you override existing inspector groups in a yaml configuration file with `~` these groups still show up in the inspector as empty collapsibles.
(Empty groups with no properties belonging to them also still show up, maybe this is related behaviour)

### Steps to Reproduce

1. Define an inspector group in a NodeType
2. Define another NodeType inheriting from the first
3. Override the group in the second NodeType

#### Expected behavior

The overridden or empty groups should not be shown in the inspector panel.

#### Actual behavior

Overridden groups still show up but are lacking their title and icon:

![image](https://user-images.githubusercontent.com/8970747/37514576-a0f5a418-2908-11e8-8ea4-32b65ca39a24.png)

Empty groups also still show up:

![image](https://user-images.githubusercontent.com/8970747/37515026-d5ae3ed0-2909-11e8-9c4c-3baa45efe66f.png)

### Affected Versions

Neos: 3.3.8

UI: 1.0.8

**Comment by suffle** [comment]
I already fixed that in #1680, fix is included in v1.0.9
