### ISSUE TITLE
Missing CKEditor toolbar for inline editable `document node properties`

### ISSUE THREAD

**Issue by jobee** [neos/neos-ui#1711]
### Description

Inline editable document properties don't show the CKEditor toolbar (upper left corner) when focused.

### Steps to Reproduce

1. Add an inline editable property to a document nodetype
2. Click on it / focus

#### Expected behavior

CKEditor toolbar should show up

#### Actual behavior

Content dimension navigation is shown, which means the document is still focused

### Affected Versions

Neos: 3.3

UI: > 1.0.7

**Comment by dimaip** [comment]
This is probably the cause: https://github.com/neos/neos-ui/pull/1649/files
