### ISSUE TITLE
Add special class to content shining through

### ISSUE THREAD

**Issue by ComiR** [neos/neos-ui#1715]
### Description
When a content element exists in a fallback dimension, but not in the current one, it shines through.
The UI of `neos/neos` has a special class `neos-contentelement-shine-through` for these elements but with `neos/neos-ui` you can't differentiate between normal content and content shining through.

### Steps to Reproduce
1. Create content element in one dimension
2. Switch dimension to one with dimension above as fallback

#### Expected behavior
You can differentiate elements "only" shining through from those actually existing in the selected dimension.

#### Actual behavior
You can't.

### Affected Versions
Neos: 3.3.*, tested with 3.3.9
UI: <=1.0.9, tested with 1.0.9

**Comment by dimaip** [comment]
These kind of things were never an official API, but I still believe we should fix it, so PRs are welcome.
