### ISSUE TITLE
Inspector does not hide on mobile

### ISSUE THREAD

**Issue by ComiR** [neos/neos-ui#1716]
#### Steps to Reproduce
1. Open UI in chrome or open on mobile device (then skip next step)
2. Go to "mobile view"
3. Hide Inspector

#### Expected behavior
Inspector is hidden fine
![inspektor](https://user-images.githubusercontent.com/11410095/37832693-97f04980-2ea9-11e8-93f9-e6186a24ecb4.gif)

#### Actual behavior
Site gets zoomed out due to inspector being right of the UI:
![inspektor_fail](https://user-images.githubusercontent.com/11410095/37833002-826ecaa4-2eaa-11e8-93c2-abf09d9663a4.gif)

### Affected Versions
Neos: 3.3.9
UI: 1.0.9

**Comment by maltemuth** [comment]
Some notes for anyone trying to tackle this:
- There is no viewport-meta-tag in the head of the document, so mobile browser fall back to their "scaling" behavior
- Adding `<meta name="viewport" content="width=device-width, initial-scale=1">` will render the backend unusable on small screens:

![localhost_8081_neos_content_node _sites_neosdemo user-maltem language en_us galaxy s5 1](https://user-images.githubusercontent.com/5989390/38433379-e4c886d8-39ca-11e8-813b-b8975ef09f53.png)

- Something like `<meta name="viewport" content="width=device-width, initial-scale=0.001">` _kind of_ works in Chrome Devtools but is very hacky.

**Comment by danielkestler** [comment]
Closed, as the backend is now responsive.
