### ISSUE TITLE
Backend exception causes infinite waiting

### ISSUE THREAD

**Issue by ComiR** [neos/neos-ui#1718]
### Description
If the backend throws an exception (i.e. at the `/neos/ui-services/flow-query` endpoint), the UI doesn't show an error, it just waits for an answer indefinitely (i.e. the loading indicator/spinner shows forever).

### Steps to Reproduce
1. create a subpage
2. remove the property `uriPathSegment` (directly in the database) [2]
3. open the parent page in the UI

[2] I created a page without the permission to edit it (the page created matched a `NodeTreePrivilege`). Therefore I ended up with a page node without properties.

#### Expected behavior
Show an error message and stop waiting.

#### Actual behavior
Infinite waiting.

### Affected Versions
Neos: 3.3.9
UI: 1.0.9

**Comment by ComiR** [comment]
With UI 1.4.1, this is much better. It still is waiting indefinitely, but at least the error page gets shown in the content frame.

**Comment by grebaldi** [comment]
Closed in favor of https://github.com/neos/neos-ui/issues/3477.
