### ISSUE TITLE
Replace immutable with immer

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1726]
This is not really an issue, more or less a reminder and discussion base.
I played a bit with immer and it can replace immutable js and performance better and is easier to handle.

It works with a straight forward and simple API and can handle plain JS objects and so own.
Would like to here what you think about it. For transformations and state changes it performance better and uses proxies under the hood to be so fast.

It works nicely with plain react states or with redux.

Don`t know if such a move is welcome or possible because we are on a LTS version.
https://github.com/mweststrate/immer

**Comment by skurfuerst** [comment]
Hmmm, I personally don't like the "magic approach" taken with Immer - I'd rather like to have an explicit "mutation" API. Maybe let's discuss this during some hangout etc? (I am on parental leave for the next two months; so feel free to do the discussion without me).

All the best, Sebastian :)

**Comment by markusguenther** [comment]
I just listend to a podcast with Michel Westrate and thought it would be an awesome idea to use that also in neos. So excerpt little experiments I never used it at the moment.

And sadly my time is limited... enjoy the parental leave. The two month are sooooo short ;)

**Comment by dimaip** [comment]
I think we'd have to move to something lib with native api like seamless immutable or immer in order to not loose type information in TypeScript.
But I'll close this discussion here for now and redirect further discussions to this issue: https://github.com/neos/neos-ui/issues/2102
