### ISSUE TITLE
Remember open tab when hiding Inspector 

### ISSUE THREAD

**Issue by ComiR** [neos/neos-ui#1744]
### Description
When I close the inspector and reopen it again, I want to see the same tab as before.

### Steps to Reproduce
1. Select other tab than first in inspector
2. Close inspector
3. Reopen inspector

#### Expected behavior
The same tab is selected/open.

#### Actual behavior
![tab](https://user-images.githubusercontent.com/11410095/38372483-395e8526-38ef-11e8-875b-0dc3ed64d4dd.png)

### Affected Versions
Neos: 3.3.9
UI: 1.0.9

**Comment by dimaip** [comment]
@maltemuth you are precisely correct. In fact it was originally hidden via CSS, but I changed not to render hidden stuff, as a performance optimization.
I'll think what to do about it.

**Comment by ComiR** [comment]
It would also be nice to remember the opened tab when switching pages. I.e. I had to change a few document types and always was starting on the first tab after changing the page, which was kind of annoying.
Keep that in mind when thinking about another way to implement ;)

Thanks already!

**Comment by Sebobo** [comment]
I also recently realized that it would make a lot of sense if the tabs wouldn't remember the tab number when I switch between elements, but the identifier of the tab. This way I could show an analysis in the inspector which updates when switching content. Right now I can't guarantee that not suddenly a different tab is visible.

**Comment by Sebobo** [comment]
I made the PR for the remembering the tab by identifier instead of the index. So any change here might need to build on that. See #2383
