### ISSUE TITLE
CodeMirror CodeEditor can't be closed when containing 2 or more LoC

### ISSUE THREAD

**Issue by ComiR** [neos/neos-ui#1748]
### Description
CodeMirror uses `z-index` 1 to 6. The close button of the `SecondaryInspector` gets assigned a `z-index` of 2. The lines in CodeMirror therefore overlap the close button, making it unusable.

### Steps to Reproduce
1. Open the CodeEditor for any property
2. write 2+ lines of code

#### Expected behavior
CodeEditor can be closed

#### Actual behavior
Close button cannot be clicked.

### Affected Versions
Neos: 3.3.9
UI: 1.0.9

**Comment by markusguenther** [comment]
The index needs to be just 3, the others are not that important. The PR will raise the index and then the code close button is working again. The four other secondary inspectors are still working :)
