### ISSUE TITLE
Pasting a content element into a content collection leads to inconsistent node order

### ISSUE THREAD

**Issue by beheist** [neos/neos-ui#1762]
### Description

Order of nodes in structure view and content area is inconsistent after copying a node and pasting it.

### Steps to Reproduce

1. Copy a content node in a content collection
2. Click on the content collection in the structure tree so it is marked
3. Click "paste"

#### Expected behavior

The newly pasted node appears at the end of the content area and structure tree.

#### Actual behavior

The newly pasted node is last in the content area, but first in the structure tree. A page reload fixes the problem.
![image](https://user-images.githubusercontent.com/10347669/38603114-faccccdc-3d6c-11e8-9433-d9d73556140e.png)

### Affected Versions

Neos: 3.3

UI: 1.0.9

**Comment by dimaip** [comment]
@beheist I thought you said this was a CR bug, no?

**Comment by dimaip** [comment]
It's a CR issue.
