### ISSUE TITLE
Using "Mark all" (CMD+A) on formatted text removes the formatting

### ISSUE THREAD

**Issue by beheist** [neos/neos-ui#1763]
### Description

See headline

### Steps to Reproduce

1. Select a formatting for a paragraph of text (e.g. "Headline 1")
2. Click into the text and use the hotkey to mark all content (CMD+A on Mac)
3. Type something to replace the existing text.

#### Expected behavior

The new text gets inserted in the same formatting as the text that was there previously.

#### Actual behavior

The new text is inserted without formatting.

### Affected Versions

Neos: 3.3

UI: 1.0.9

**Comment by mstruebing** [comment]
I can't reproduce it on the demo page. @beheist is this still the case?

**Comment by beheist** [comment]
@mstruebing yes, the problem still exists - tested on 1.0.14 and 1.1.0.
Here's a short video:
https://www.dropbox.com/s/h99v700ade2gpe6/ScreenFlow.gif?dl=0

**Comment by beheist** [comment]
This is fixed with 1.3.0. Can be closed.
