### ISSUE TITLE
Make document loading indicator more visible

### ISSUE THREAD

**Issue by rolandschuetz** [neos/neos-ui#1771]
The loading indicator is not very visible currently. To make it more visible it should be centered and mirrored.

Jira-URL: https://jira.neos.io/browse/NEOS-828

**Comment by mstruebing** [comment]
I think he means the orange progress bar at the top when switching pages for example.

**Comment by rolandschuetz** [comment]
Well, that is an issue from 29 Nov 2014 which I just moved to the UI repository during issue cleanup. 

Right now when you switch pages, the only indicator of loading is the orange progress bar at the top. 

I don't really have an opinion if that's fine or not. I'm not the creator of the ticket.
