### ISSUE TITLE
Exception: Copy & paste of Node with NodeType constraint

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#1777]
### Description

When copying a Node to a place where it should not be inserted due to NodeType constraints (via the copy and insert buttons next to the structure tree) an exception is shown to the user.

#### Expected behavior

Either a nice message to the user that doesn't scare them or the same behavior as when dragging & dropping: it should be impossible if there is a constraint (-> paste button inactive)

#### Actual behavior

![screen shot 2018-04-17 at 17 30 43](https://user-images.githubusercontent.com/9661367/38880494-294edaf2-4266-11e8-9bf7-38b333bd35d3.png)

### Affected Versions

Neos: 3.3.9

UI:
neos/neos-ui                       dev-master a1f8e2a NEOS CMS UI rewritten in React
neos/neos-ui-compiled              dev-master 4d7f86c

**Comment by klfman** [comment]
I will try to do so but after a project of mine finished in around two weeks.

A reason I can think of is that during development I was changing constraints and the browser cache was still different from the business logic?

**Comment by skurfuerst** [comment]
@klfman that might very well be the issue. Closing for now, please reopen when the problem persists :)
