### ISSUE TITLE
LinkEditor deletes URL when clicking it for inspection

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#1784]
If I want to see a long URL that I entered in the LinkEditor in the inspector I click it. However, clicking means it will be deleted instantly making room for the input of a new URL.

#### Expected behavior

The flyout of the LinkEditor should probably be more like the one used for the link funcitonality in the CKEditor, there i can open the flyout without deleting its content.

#### Actual behavior

Long URL that cannot be read without clicking it: 

![screen shot 2018-04-18 at 09 38 51](https://user-images.githubusercontent.com/9661367/38919933-5616360c-42f2-11e8-98bc-c94b35964100.png)

### Affected Versions

Neos: 3.3.9

UI:
neos/neos-ui                       dev-master a1f8e2a NEOS CMS UI rewritten in React
neos/neos-ui-compiled              dev-master 4d7f86c

**Comment by dimaip** [comment]
Agree, Link editor has currently a pretty bad UX, in part due to inherent FrankenBox(tm) problems....
