### ISSUE TITLE
JavaScript warnings for the EditPane Sliders

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1804]
### Description

In the react-slick package is an issue regarding the arrow buttons.

![bildschirmfoto 2018-04-23 um 10 20 00](https://user-images.githubusercontent.com/1014126/39114804-2ba7b96c-46e0-11e8-9882-4863747a811f.png)

This can be fixed by using react-components instead of plain HTML elements.

### Steps to Reproduce

1. Just load the backend

#### Expected behavior

Editpane slider buttons work without warnings :)

#### Actual behavior

Warnings in the console.

[What actually happened]

### Affected Versions

Neos: 3.3

UI: 1.0.11

**Comment by dimaip** [comment]
Maybe even better to fix it upstream?

**Comment by markusguenther** [comment]
They had lot of discussions there and it seems that the outcome is that theses properties don't belong to HTML and therefore they use React-Components now. They also do this now in there examples.

**Comment by markusguenther** [comment]
PR has been merged :)
