### ISSUE TITLE
react-codemirror is dead

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#1814]
... but the community of react-codemirrow created a new package.
Maybe we should move along and use also the "new" version. Also tried to contact Jed Watson.

Will see what happen :)

https://github.com/scniro/react-codemirror2

**Comment by mstruebing** [comment]
Are there any mention-worthy differences between react-codemirror and react-codemirror2?
We shouldn't use a dead tool/dependency, if there are no bigger difference we should simply swap them I think

**Comment by markusguenther** [comment]
Yeah will care for it ... just need some free time ;)
