### ISSUE TITLE
Changes on image(asset) properties are not saved when opened from inspector

### ISSUE THREAD

**Issue by paintsmultimedia** [neos/neos-ui#1817]
When you click on an image in the inspector-sidebar the images and properties are opened. When changing some asset properties like title or caption, these changes are not saved.
Changing asset properties within the Management/Media module works.
When I switch to the old ui, it is possible to change the asset properties from the inspector sidebar.

neos/neos v3.3.9
neos/media v3.3.9
neos/neos-ui v1.0.11

**Comment by dimaip** [comment]
Wow, this is quite an issue! Thanks for reporting.
