### ISSUE TITLE
Cannot add link to a node in LinkEditor (node://)

### ISSUE THREAD

**Issue by sruegg** [neos/neos-ui#1820]
### Description

Since the new UI we can't add a link to a node in LinkEditor (either in the property editor or in the ckeditor).

A use case will be when using the package [Flownative.Anchorlinks](https://github.com/flownative/neos-anchorlinks) you can't paste the direct link to the node#anchor.

### Steps to Reproduce

1. Add a text on a page
2. Select a word and click the link button
3. Type "node://_anyNodeTypeIdentifier_"

#### Expected behavior

The link should be saved "as is".

#### Actual behavior

Nothing happens. The link is not saved at all.

### Affected Versions

Neos: 3.3.9
UI: 1.0.11

(I didn't test on other versions but it was working on the old UI)

**Comment by ComiR** [comment]
Can confirm - a little workaround is to create the link via the button, double click it to open the advanced link editor and paste it there.
But if you'll focus the link again - the UI will break due to not being able to resolve the link correctly.
