### ISSUE TITLE
Allow configuration of keyboard shortcuts via Settings.yaml

### ISSUE THREAD

**Issue by theilm** [neos/neos-ui#1823]
### Description

We have a hotkey registry for global keyboard shortcuts (see #1765). The shortcuts are defined in the manifest.hotkeys.js file at the moment; they should be configurable via Settings.yaml.

**Comment by mstruebing** [comment]
This is already the case see https://github.com/neos/neos-ui/pull/1839

**Comment by mstruebing** [comment]
This is already the case see https://github.com/neos/neos-ui/pull/1839
