### ISSUE TITLE
Improve user notification during publishing

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#1830]
Currently the UI does not show any kind of visual notification (or not enough) during publishing. With a big workspace, that can take quiet long. 

The old UI use the "three dot" animation, it's good, but too small from my point of view. 

My proposition is to replace the chevron in the publishing dropdown, with a spinner and at the same disallow opening the publishing dropdown during publication.

**Comment by DrillSergeant** [comment]
In the current state, you can still drag&drop in the document-tree while publishing other changes. Not sure if it happens all the time, but if the currently published changes contain other document-tree movements often you end up with some exceptions.
Mabye during publishing the UI should not allow any edit/drag&drop/...-actions?

**Comment by dimaip** [comment]
Ideally it would be nice to fix this kind of mess at backend side, so no kind of command could lead the CR into a broken state... But yes, improving the UI feedback is also important.

**Comment by johannessteu** [comment]
i'll take care
