### ISSUE TITLE
Improve user notification during tree navigation

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#1831]
If you open/close a branch with a lots of children, this can be a bit long. Currently without notification the user can try to do double clicking, so open + close or close + open, with frustrating results.

My proposal is the replace the chevron in the tree (where the user click to open a branch) with a spinner, immediately after the click.

**Comment by dimaip** [comment]
@dfeyer isn't it already the case?

![peek 2018-04-27 10-00](https://user-images.githubusercontent.com/837032/39349035-1f4485a4-4a02-11e8-8544-a232c8d58abc.gif)

**Comment by dimaip** [comment]
@dfeyer?

**Comment by dimaip** [comment]
Closing for now for the lack of feedback. @dfeyer feel free to reopen with additional details.
