### ISSUE TITLE
Missing node type title attribute for nodes in content tree

### ISSUE THREAD

**Issue by ComiR** [neos/neos-ui#1844]
### Description
In the old UI the links to the nodes in the content tree had a `title` attribute which contained the node type.
In the new UI the equivalent `span`s don't have this attribute.

### Steps to Reproduce
1. Hover over a node in the content tree

#### Expected behavior
![image](https://user-images.githubusercontent.com/11410095/39534890-e6fa311e-4e32-11e8-9828-5d320af843b6.png)

#### Actual behavior
![image](https://user-images.githubusercontent.com/11410095/39535065-48175148-4e33-11e8-997b-79223f3db219.png)

### Affected Versions
Neos: *
UI: <= 1.0.13

**Comment by dimaip** [comment]
Makes sense to fix it.
