### ISSUE TITLE
JavaScript error breaks ui

### ISSUE THREAD

**Issue by pduersteler** [neos/neos-ui#1846]
### Description

The console throws various errors stating `Cannot read property 'indexOf' of null`. This leads to the "change type" property in the inspector also displaying this message, together with various other errors, like clicking on the "create new" button in the toolbar leading to a blank white page.

### Steps to Reproduce

1. Set up a project with neos-ui 1.0.14 or upgrade from earlier versions to 1.0.14
2. Log into backend
3. Select a content collection
4. Click "create new"

#### Expected behavior

Omitted since the description and expectations are quite clear.

#### Actual behavior

Errors and not working UI.

![screen shot 2018-05-03 at 11 28 16](https://user-images.githubusercontent.com/175990/39569306-198c5d40-4ec5-11e8-9922-22f64df889f3.png)

### Affected Versions
UI: Only 1.0.14

**Comment by dfeyer** [comment]
I try to update my current project to confirm or not the issue.

@pduersteler Can you give us more details on your browser / os versions ? Sometimes it helps with JS nasty error ;)

**Comment by dimaip** [comment]
Hello Pascal!
I can not reproduce the error here so far. Could you please show the full console output (maybe via a screenshot)?

**Comment by pduersteler** [comment]
Of course.

OS: macOS Sierra (10.12.6)
Browser: Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by dfeyer** [comment]
Just update on dev-master, freshly compiled, and unable to reproduce too

**Comment by pduersteler** [comment]
Okay let's try that again with more information as requested.

I just updated neos-ui and neos-ui-compiled from 1.0.13 to 1.0.14, fired up `flow server:run`, logged myself in as admin, and selected a node of type `Neos.NodeTypes:Text`. This leads to the screenshot from above (inspector error).

This gives me the following:
![screen shot 2018-05-03 at 12 02 51](https://user-images.githubusercontent.com/175990/39570852-f0b210e0-4ec9-11e8-8133-224b238dbc10.png)

**Comment by dimaip** [comment]
Thanks, that helps! Will fix after lunch.

**Comment by dimaip** [comment]
@pduersteler could you please test if my fix fixed it? If not reopen.
To test just pull the latest master.
Btw, I still couldn't reproduce it, but I made it more robust in the place where it failed for you.

**Comment by pduersteler** [comment]
Solved together with https://github.com/neos/neos-ui/pull/1848 👍
