### ISSUE TITLE
Working with dimensions 2.0 - Improve UX

### ISSUE THREAD

**Issue by akappler** [neos/neos-ui#1860]
### Description

Editors are often confused about the behavior of the dimension selector as it disappears as soon as a content element is selected and it is not obvious how to get them back. Also many mistakes accure as they don't know that they have to follow a specific process to have dimensions translated/connected.

Therefore I was thinking a lot about a new position and behavior. 

To make it more visual, I created these mockups:

This would be the view if this page is present in all dimensions:
![dimension-selector-translated](https://user-images.githubusercontent.com/30337968/39664424-58d7e1c6-5083-11e8-98b5-27756d159adc.jpeg)
 
This would be the case if some or all dimensions are missing:
![dimension-selector-missing-translations](https://user-images.githubusercontent.com/30337968/39664441-85a35d84-5083-11e8-8bc3-3f03a29a1130.jpeg)

And a possible hover state for the "Translate now" button:
![dimension-selector-hover-state](https://user-images.githubusercontent.com/30337968/39664448-972725d6-5083-11e8-97b6-6d1db978f17a.jpeg)

#### Adding the dimension selector to the center top bar area
The current position doesn't reflect that all components depends on the selected dimension and even worse at the current position the dimension selector will disappear as soon as you select a content element. Also it isn't intuitive at all how to get back this important component.

But the dimension will affect:

1) Page - & Structure Tree: this will adapt to the content of the selected dimension 
2) Property Inspector: the properties are also releated to the selected dimension and will change
3) Content Area 

So in my point of view, all of those three parts are relaying on the selected dimension which makes the center top bar a valid and perfect matching position, which reflects the importance of this component.

#### Add a "Translate now" button
Due to issues with clients who are accidentally creating pages outside the default dimension and didn't realize that they have to follow a process to create connected translated pages, I was wondering how to guide/support the editors more.
Therefore I came up with the idea to show kind of a status and an button to translate pages/documents and help customers with this.

My suggestion would be to show the following dialog if the "Translate now" button will be clicked, as long as some dimensions are not translated:
![creationdialog](https://user-images.githubusercontent.com/30337968/39664619-0d27b3c0-5086-11e8-9bf6-e825a4a48b1d.png)

These pages get autogenerated to the live workspace, so that other editors can see that this page is now available for translating and they can do this at some point of time.

#### Set autogenerated documents to hidden as default
It might be, that the editor who created a page on a dimension won't add the content for other dimension. As suggested, the autogenerated documents are right away in the live workspace, they have to be hidden, till they are ready for publishing and an editor will unhide them.

### Benefits
1) highly reduces complexity
2) makes it less error prone to work with dimensions 
3) improves the user experience the biggest USP of Neos

These are my thoughts to this topic and I'd love to discuss this.

**Comment by mficzel** [comment]
@kapale so you basically suggest to separate the dimension switch from creating a node variant. 

I think this i a very good idea and allows us to show the editor much more meaningful help. This can help to avoid editors getting lost in dimensions and fallbacks

**Comment by dimaip** [comment]
I like all the concepts here!
But I don't like placing it int the middle of top bar design-wise. Would be nice to bring in this topic for #guild-ux.

**Comment by akappler** [comment]
Support from UX pro's is very welcome! :)

From my point of view the top bar is currently the best place (left, center, right doesn't really matter), without having to redesign to much. As the bar below is related to node type and used for CK-Editor, so I think you'll keep this space free for custom extensibility. Furthermore I think it is very unlikely that a lot of new tabs well be added to the top bar. Even though, some space is still left. Placing it to the center was also as I think it's not related to the left tabs, nor to the right publishing and user login.

**Comment by dimaip** [comment]
Yes, I agree. Just having it centered looks a bit awkward to me.

**Comment by dfeyer** [comment]
> I like all the concepts here!
> But I don't like placing it int the middle of top bar design-wise. Would be nice to bring in this topic for #guild-ux.

Yes we need to improve, but please, nothing "floating" in the middle on the top toolbar.

I dont' have a clear solution right now. I like where it's placed right now. I hate that the editor toolbar replace it ;) 

So basically the location of the dimensions switcher is OK (if we move it somewhere here, we "break" the full screen mode, or at least it's not possible to switch dimensions from the full screen mode, and that's bad).

My first proposal is: why not improve the editor toolbar and place it on the right of the dimension switcher ? And if needed make the Dimension Switcher, when closed, a bit more compact, by using only icons with tooltip.

For the other point, Translate Now, @akappler can you open an other issue ? I think we need to be focused on each discussion.

**Comment by dfeyer** [comment]
> It might be, that the editor who created a page on a dimension won't add the content for other dimension. As suggested, the autogenerated documents are right away in the live workspace, they have to be hidden, till they are ready for publishing and an editor will unhide them.

I'm a bit against this, even if I understand the concerns. If we can make this an optional settings, I'm fine. If not, we basically change and editorial workflow (good or bad, it's not the question) and force all our users to update there documentation, help editors, ...

**Comment by akappler** [comment]
@dfeyer I'd suggest to discuss in this issue the overall picture first. I'd suggest, after we have a common picture of the new workflow with dimensions, creating dedicated issues where we discuss the specific details. Otherwise I'm worried that we are discussing about details before we know where we are going.

**Comment by Sebobo** [comment]
The dimensions selector is always visible since some releases now. So I consider this fixed.
