### ISSUE TITLE
ImagePreview stays in loading state when local file upload is cancelled

### ISSUE THREAD

**Issue by cvette** [neos/neos-ui#1862]
Image Preview does not return to previous state when cancelling upload.

1. Select a node type with an image editor
2. Click on 'Choose File'
3. Cancel the file selection

#### Expected behavior

The image preview should show the original state again.

#### Actual behavior

![image_upload](https://user-images.githubusercontent.com/6884391/39667216-15e2cb8c-50b1-11e8-96e5-c60e0ae80de0.gif)

### Affected Versions

Neos: 4.0
UI: 1.0.14

**Comment by skurfuerst** [comment]
Thanks for the detailed bug request, opened a MR in https://github.com/neos/neos-ui/pull/1998!
