### ISSUE TITLE
Inline editing toolbar is hidden by header

### ISSUE THREAD

**Issue by cvette** [neos/neos-ui#1863]
When an inline editable content element is placed at the very top of a page, the inline editing toolbar is hidden by the header of the UI. Only when changing the width of the page its position changes and it becomes visible.

### Steps to Reproduce

1. Place a content element on an empty page
2. Select the element

#### Expected behavior

The inline editing toolbar should be visible.

#### Actual behavior

![inline_editing](https://user-images.githubusercontent.com/6884391/39667267-50f3b7bc-50b2-11e8-82ce-d793bc9e329f.gif)

The inline editing toolbar is hidden by the UI header.

### Affected Versions

Neos: 4.0
UI: 1.0.14

**Comment by skurfuerst** [comment]
I am unsure how to solve this issue... Suggestions? :)

**Comment by dimaip** [comment]
@cvette could you please try to test the latest master? Seems to work for me...

**Comment by cvette** [comment]
@dimaip looking good :100: Works in 1.3.3 and master. Tested in Chrome.
