### ISSUE TITLE
NodeTreePrivilege leads to JS-Errors and white screen

### ISSUE THREAD

**Issue by sbruggmann** [neos/neos-ui#1872]
Given the following site Structure:
```
Home
  - Some Page
  - About us
    - Jobs
  - Another Page
```
and given, we have a Role with the PrivilegeTarget `isAncestorOrDescendantNodeOf("identifier-of-about-us")` and login with such a user.

then we get the following error message when we visit the Home:
![image](https://user-images.githubusercontent.com/1162368/39813075-540d42ee-538f-11e8-98fa-c057d72e13e4.png)

and if we click to a not-editable element, we get a completely white screen and the following error message:
![image](https://user-images.githubusercontent.com/1162368/39813097-630b586c-538f-11e8-849d-7dbfd12228a9.png)

### Affected Versions

Neos: 3.3.9
UI: 1.1.0

**Comment by dimaip** [comment]
@sbruggmann Could you please verify if it's still the case on master?

**Comment by sbruggmann** [comment]
@dimaip Hm, I can't reproduce this since UI Version 1.2

**Comment by dimaip** [comment]
Awesome, thanks for testing!
