### ISSUE TITLE
Implement dimensions selector

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#188]
![image](https://cloud.githubusercontent.com/assets/837032/16446910/b89a7d6c-3df2-11e6-9744-f6d62ad129f0.png)

Look up how it looks in current Neos UI.

This should be taken in mind when doing styling: https://github.com/neos/neos-ui/wiki/Styling

**Comment by Inkdpixels** [comment]
Oiii, #5 already has some progress regarding this, dunno which issue we should close.

**Comment by dimaip** [comment]
Haha, your issue was gone for a while... closing this one
