### ISSUE TITLE
Update CKEditor to a recent version, fixes strange editing behavior in Chrome

### ISSUE THREAD

**Issue by hlubek** [neos/neos-ui#1889]
### Description

See https://github.com/neos/neos-development-collection/issues/2076 for a description of the editing issue. It seems it is caused by a regression for (at least) Chrome in CKEditor when editing certain inline elements.

A quick test of replacing it with the current version 4.9.2 seems to fix the issue.

UI: 1.1.0

**Comment by dimaip** [comment]
I don't think it makes sense to maintain CKE4, as CKE5 integration is quite mature already and we should make it the default soonish.
Re-open if you disagree.
