### ISSUE TITLE
DocumentTree Icons does not differentiate between hidden and hiddenInIndex

### ISSUE THREAD

**Issue by sbruggmann** [neos/neos-ui#1895]
![image](https://user-images.githubusercontent.com/1162368/41276931-0b0e7cfa-6e26-11e8-9824-5982e44d29e9.png)

Neos: 3.3.*
UI: 1.1.*

**Comment by mstruebing** [comment]
IIRC it is shown correctly once you've clicked on that Document

**Comment by sbruggmann** [comment]
Correct, the "Hidden in Index"-Icon starts as "Normal" page. If clicked it changes the Icon.

**Comment by johannessteu** [comment]
Related to #1500
