### ISSUE TITLE
No hint, when a node shines through from another content dimension

### ISSUE THREAD

**Issue by LeonardFollner** [neos/neos-ui#1977]
### Description

When editing a node in a content dimension, which is not the main content dimension, there is no hint, that another dimension might be shining through.

### Steps to Reproduce

1. Create a node in your main dimension
2. Switch to another dimension
3. Delete the created node
4. Reload

#### Expected behavior
The Node should be gone.

There should be an indicator in the Node Tree or elsewhere that the view of the current node is coming from another dimension.

#### Actual behavior
The node reappears.

### Affected Versions

Neos: v4.0.3

UI: v1.0.13

**Comment by mstruebing** [comment]
fixed by #2136
