### ISSUE TITLE
Flex items should have min-height to shrink

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-ui#1982]
According to:
https://developer.mozilla.org/en-US/docs/Web/CSS/flex

An item in a flex container will not shrink below content size if it doesn't have a min-height. This is apparently handled differently in FF and Chrome but if you use something like the https://github.com/psmb/Psmb.FlatNav
You will have problems with long trees/lists in FF as it pushes the content tree out due to the missing min-height.

**Comment by kitsunet** [comment]
Above just fixes the most obvious error I found when using FlatNav, I guess there are more cases.

**Comment by dimaip** [comment]
Seems like this one is fixed. Will close for now.
