### ISSUE TITLE
NodeTreePrivilege not working since 1.2.0

### ISSUE THREAD

**Issue by vectoholic** [neos/neos-ui#1995]
### Description

Since I got the latest changes right, the privilege for any nodes are checked now by clicking on the node in the node tree. This results in showing all nodes and it doens´t hides nodes anymore.  

### Steps to Reproduce

My Policy.yaml

```
'Neos\Neos\Security\Authorization\Privilege\NodeTreePrivilege':

    'Foo.Bar:BuzAllNodes':
      matcher: 'true'

    'Foo.Bar:BuzRestricted':
      matcher: >-
        isAncestorOrDescendantNodeOf("identifier")`

 'Foo.Bar:RestrictedUser':
    parentRoles: ['Neos.Neos:RestrictedEditor']
    privileges:
      -
        privilegeTarget: 'Foo.Bar:BuzRestricted'
        permission: GRANT
```

#### Expected behavior

See only the ancestor and descendent nodes of the chosen node (identifier)

#### Actual behavior
Shows all nodes

### Affected Versions

Neos: 3.3.12

UI: 1.2.0

**Comment by skurfuerst** [comment]
@kitsunet @mstruebing this might be related to you policy changes on the sprint, no? :)

**Comment by kitsunet** [comment]
Is this fixed with 1.2.3?

**Comment by nlx-lars** [comment]
@kitsunet I am still facing this problem with 1.2.3.

**Comment by vectoholic** [comment]
I tried also 1.2.3 and the problem still exists!
