### ISSUE TITLE
Keyboard shortcut "SelectNodeTypeModal Apply" js error

### ISSUE THREAD

**Issue by KPeschke** [neos/neos-ui#2013]
### Description
Shortcut "SelectNodeTypeModal Apply" js error

### Steps to Reproduce
1. Open Add-Node-Modal
2. Focus a nodetype
3. Press shortcut: as

#### Expected behavior
Insert selected nodetype and close the modal.

#### Actual behavior
js error in util.js (line 225):
`uncaught at addNode 
 at takeLatest 
 at _callee 
 at nodeCreationWorkflow 
 at nodeCreationWorkflow 
 Error: Key must be a string
...`

### Affected Versions
Neos: 3.3.12
UI: 1.1.2

**Comment by dimaip** [comment]
This shortcut indeed doesn't seem to work. But I wonder why such complicated shortcut is needed as all? I would expect from such dialog that arrow keys would select the nodetypes, enter would apply and esc would close the dialog. Wdyt @mstruebing?

**Comment by dimaip** [comment]
@mstruebing wdyt? If you agree with the above suggestion I could take care of it.

**Comment by mstruebing** [comment]
It's okay for me, as I introduced these shortcuts I actually just converted every redux action which doesn't take a parameter into a shortcut. So there are maybe more which can be removed.
