### ISSUE TITLE
Multisite installation with access restrictions for each site not working

### ISSUE THREAD

**Issue by Benjamin-K** [neos/neos-ui#2025]
### Description

When setting policies for multiple sites, the new UI makes only the first site accessible for users that are not an Administrator and do only have access to the second page. This is due to the fact, that the backend menu catches the first website in the backend instead of the current site (see [Backend/Root.fusion#L196](https://github.com/neos/neos-ui/blob/master/Resources/Private/Fusion/Backend/Root.fusion#L196)). This causes an error if the user does not have access to the other website.
Further information about this issue can also be found in the [Neos Forum / Multisite capabilities of Neos](https://discuss.neos.io/t/multisite-capabilities-of-neos/553/26).

### Steps to Reproduce

1. Create a neos installation with two websites.
2. Create policies for both websites (have a look at [Policy.yaml of flownative/multisitekickstarter](https://github.com/flownative/neos-multisitekickstarter/blob/master/Resources/Private/Generator/Configuration/Policy.yaml) for some good starting point).
3. Create a user for each site that can only access one of the two sites (Role Editor and SiteA/SiteB).
4. Try to log in on each site with those two users.

#### Expected behavior

Login should work for the site, the user is allowed to edit.

#### Actual behavior

Login on the second site causes an Error 500. This is, because the user does not have access to the other site and the LinkingService tries to create a link for SiteA while logged in on SiteB (see method [LinkingService::createNodeUri()](https://github.com/neos/neos-development-collection/blob/fd5d3136fcc830be36e0f186017097af6552562e/Neos.Neos/Classes/Service/LinkingService.php#L226) and [Backend/Root.fusion](https://github.com/neos/neos-ui/blob/master/Resources/Private/Fusion/Backend/Root.fusion#L196))

[What actually happened]

### Affected Versions

Neos: 3.3.x

UI: Don't really know, but possibly exists for a long time, as the fusion-part exists since before Dec 2016.

**Comment by dimaip** [comment]
Should have been fix by now.
