### ISSUE TITLE
Update FontAwesome to Version 5.2

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#2028]
The React UI as well as the HTML-based UI should be updated to use FA 5.2

**Comment by markusguenther** [comment]
Is there a reason that the issue has not been closed?

**Comment by mstruebing** [comment]
nope :)

**Comment by markusguenther** [comment]
@mstruebing Ah I see that in the neos distribution it is still version 5.0.10 ... but this should be a new issue in the Neos.Neos package right?

**Comment by dimaip** [comment]
Yep
