### ISSUE TITLE
animateScrollToElementInGuestFrame scrolls out of viewport for horizontal slider

### ISSUE THREAD

**Issue by patricekaufmann** [neos/neos-ui#2040]
### Description

When selecting elements in the NodeTree, the window may scroll out of view when the elements technically are outside of the viewport. This is problematic for sliders when the elements usually are outside of the viewport.

### Steps to Reproduce

1. Have a collection of nodes that align amongst the X axis, like an usual slider.
2. Select an element inside the collection that is technically outside of the viewport.
3. neos-ui will scroll outside of the viewport to focus the element.

#### Expected / Actual behavior

Since there are also sites with horizontal scrolling, it is hard to say what the expected behaviour should be like. Best would be if it would be configurable on the parent element, eg. a overflow-direction on the wrapping neos-contentcollection.

### GIF

![gif_bug](https://user-images.githubusercontent.com/41791606/43323104-fa3d7a08-91b0-11e8-96e9-47a172333600.gif)

### Affected Versions

Neos: 4.0.0
UI: 1.3.0

**Comment by dimaip** [comment]
No strong opinion here. It's rather an exotic usecase, but yeah, we've got to do something about it.
Having too much configuration is always a pain, but that might still be the best option that we have.
Alternative would be to disable horizontal scroll.

**Comment by mstruebing** [comment]
I think there are use cases when you would want to scroll horizontally.
I mean I expect the iframe to scroll to the position vertically so I would expect to scroll horizontally too when my page is build like this.

**Comment by skurfuerst** [comment]
Hey all,
We have this problem currently as well - and for us it has quite a high prio to get this fixed.

What do you think about the following:

- we add an additional safeguard if the to-be-scrolled-to-area is outside of the document boundaries: if so, we clamp the scrolling to the document boundaries (OR we disable the scrolling).
- this would at least fix the behavior with most HORIZONTAL sliders. If you build more fancy things like vertical sliders etc, things might break still.

All the best,
Sebastian

**Comment by dimaip** [comment]
@skurfuerst sure, sounds reasonable!
