### ISSUE TITLE
Move to @friendsofreactjs/react-css-themr

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2052]
### Description

The currently used react-css-themr is not maintained for 2 years now. We get warnings because of the react compatibility. See issue #877

So we should move to the maintained for @friendsofreactjs/react-css-themr
https://github.com/FriendsOfReactJS/react-css-themr

#### Expected behavior

Get rid of the warnings

#### Actual behavior

Warnings from yarn

### Affected Versions

Neos: 3.x

UI: 1.x

You can get this information by running `composer show` or using the package management module within Neos.
The UI version can also be found inside the left sidebar after version 1.0.3.

**Comment by dimaip** [comment]
In addition to this, would be nice to figure out how we are actually going to do theming, so far it seems nobody really give it a try.

**Comment by markusguenther** [comment]
Is it planed to have a bright theme and the dark one? Have seen an issue somewhere. And of course it would be cool to have backend themes :)

Also the customers will love that. Can see branded neos backends.
