### ISSUE TITLE
Images in help tooltip from Node creation dialog

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#2088]
Help tooltips in theNodeCreationDialog are not be able to render images currently (absolute path and resource uris).
As this was the case in the old ui this should be reimplemented.

followup from https://github.com/neos/neos-ui/issues/1694 and https://github.com/neos/neos-ui/issues/1948

**Comment by markusguenther** [comment]
@mstruebing @dimaip Is this done or do we need to polish this at some point?

**Comment by dimaip** [comment]
Uhm I'm not sure, probably #2092 is the way to go.

**Comment by grebaldi** [comment]
Closing this. Help tooltips are well established now and I don't see what this issue would be waiting for. #2092 still needs to be fixed though.
