### ISSUE TITLE
Navigation in PageTree not working in Internet Explorer 11

### ISSUE THREAD

**Issue by dennisirmscher** [neos/neos-ui#2114]
### Description

If you are using Internet Explorer 11, you will only be able to navigate the page tree once. After that, nothing happens when you click on another page in the tree.
I'm not sure if you want to support Internet Explorer anymore, but I wanted to report the error just to be on the safe side. If not, feel free to just close the ticket :)

### Steps to Reproduce

1. Log in to the Neos backend with latest version of Internet Explorer 11
2. Click on any page in the page tree on the left and wait for the page to be loaded
3. Click on any other page in the page tree on the left

#### Expected behavior

The page selected in step 3 gets loaded.

#### Actual behavior

Nothing happens at all.

### Affected Versions

Neos: 3.3.13

UI: 1.3.3

**Comment by dimaip** [comment]
Yes, we are actually trying to support IE11. Needs to be fixed.

**Comment by markusguenther** [comment]
Hello, I guess the UI is actually not Internet Explorer ready. But maybe the target changed and @dimaip  knows more.

**Comment by dimaip** [comment]
It was working in IE11 a few month ago...

**Comment by dennisirmscher** [comment]
I feel for you! 🙈

**Comment by ger4003** [comment]
The Microsoft Edge browser is affected as well.

**Comment by dimaip** [comment]
Could you please expand the full error message from here? And also perhaps the filename, where it occurs.

**Comment by ger4003** [comment]
![neos-js-error-react-ui-frontenddevelopmentmode](https://user-images.githubusercontent.com/1758522/48486737-ad5bc100-e81c-11e8-8558-c8c0d5688c76.png)

I have now enabled the `frontendDevelopmentMode` and made another screenshot with expanded error messages.
The error occurs in file `﻿﻿_Resources/Static/Packages/Neos.Neos.Ui/JavaScript/Host.js`

![neos-js-error-react-ui-host_js](https://user-images.githubusercontent.com/1758522/48486967-2f4bea00-e81d-11e8-8604-dbe266800af9.png)
