### ISSUE TITLE
UI doesn't automatically parse the links of type node://

### ISSUE THREAD

**Issue by Lemmork** [neos/neos-ui#2117]
Im using flownative/neos-anchorlinks to create anchor links on my site.
Unfortunately it is not possible to paste the links of type node://d5bb1a30-8048-4b35-a27f-73fd82945b9a#anchorname in the inspector fields "link" or "shortcutTarget". The field responds with a "No matches found" message.

Could you please allow usage of node links.

Neos: 3.3.14
Neos.UI: 1.3.3

**Comment by dimaip** [comment]
It should be possible with CKE5. Could you please give it a try.

**Comment by Lemmork** [comment]
Hi Dimitri,

editing the links inline in cke works for me. Even with cke version 4.10.
Is the cke even responsible for the inspector fields on the right?

Regards
Heiko

**Comment by dimaip** [comment]
CKE5 integration has a totally reworked link editor.
See: https://www.neos.io/blog/neos-is-in-love-with-ckeditor5.html

**Comment by dimaip** [comment]
Ah gosh sorry, I thought you meant inline link editor, didn't read attentively enough.
In that case yes, the new link editor should also be used in inspector, it's something to be done yet.

**Comment by dimaip** [comment]
@Lemmork check out https://github.com/neos/neos-ui/pull/2121

**Comment by Lemmork** [comment]
Hi Dimitri,

thanks for your work.
Will this work in Neos 3.3?
I thought I have switched to ckeditor5, but the link-editor does not change appearance.
The only difference is that in every inline-editing field a p-Tag was added.
So therefore I'm not sure if ckeditor works in 3.3 or only in 4.x

**Comment by Lemmork** [comment]
Hi Dimitri,
ckeditor seems to work with Neos3.3 in my NodeType Configuration I had the old aloha configuration syntax therefore I did not see the new link editor while inline editing.
But there are no changes in the link editor in inspector. Do I have to adjust some settings?
For all link fields in the inspector I use the 'Neos.NodeTypes.BaseMixins:LinkMixin'.
There is a definition for
ui:
  inspector:
    editor: 'Neos.Neos/Inspector/Editors/LinkEditor'
Do I have to change this?

**Comment by dimaip** [comment]
Hi @Lemmork! Please review this PR and you'd get the new link editor in inspector too https://github.com/neos/neos-ui/pull/2121

**Comment by Lemmork** [comment]
Hi @dimaip,
I'm not sure if I did it right. I followed this guide: https://help.github.com/articles/checking-out-pull-requests-locally/
I compared the files which are marked as "Files changed" in PR and they are changed on my local installation. But the linkeditor in the inspector looks and behaves like the old one.
Perhaps I have to wait for the official release.

**Comment by dimaip** [comment]
@Lemmork that's not enough. You got to recompile JS assets locally and tell UI to include it. You should follow this guide: https://github.com/neos/neos-ui#contributing

**Comment by Lemmork** [comment]
@dimaip Great, it works. Thanks a lot for your help.

**Comment by dimaip** [comment]
I'll consider it for a review and merge then
