### ISSUE TITLE
PageTree and dimension switcher are sometimes broken

### ISSUE THREAD

**Issue by davidspiola** [neos/neos-ui#2126]
### Description
Sometimes, when you switch to an other dimension, the page tree is not loading and the dimension switcher is disabled. This happens most likely if you switch to an other website that has a other default dimension configured (https://packagist.org/packages/flownative/neos-hostbaseddefaultpreset) 

### Steps to Reproduce

1. Login to website A
2. Use the website switcher to switch to website B with an other default dimension
3. Refresh once to fix the behavior

**Redux Step**
![screen shot 2018-09-10 at 09 11 04](https://user-images.githubusercontent.com/7107011/45281933-b1482b80-b4d9-11e8-9d95-e6a34f8fa287.png)

![screen shot 2018-09-10 at 09 10 50](https://user-images.githubusercontent.com/7107011/45281934-b1e0c200-b4d9-11e8-8cd7-bb99f028fd5f.png)

**Redux Step**
![screen shot 2018-09-10 at 09 11 46](https://user-images.githubusercontent.com/7107011/45281938-b9a06680-b4d9-11e8-81cc-f816b796d48c.png)

![screen shot 2018-09-10 at 09 11 36](https://user-images.githubusercontent.com/7107011/45281937-b9a06680-b4d9-11e8-9e76-5ec44977a278.png)

**Comment by dimaip** [comment]
@davidspiola just to clarify, does this happen for you with the latest master? We have reworked recently how the dimension switching works, so I'm wondering if it could resolve the issue.

**Comment by davidspiola** [comment]
No, I tested with the latest stable version. I'll check the master and let you know.

**Comment by dimaip** [comment]
Just make sure when testing on master, you got to pull master version of both Neos.Neos.Ui and Neos.Neos.Ui.Compiled (or rebuild).

**Comment by davidspiola** [comment]
Alright, I tested dev-master and the problem still occurs, but I might have same additional information. It only happens on first login and I noticed that the url dimension configuration is changing. It seems to load the default preset (de) and switches to the one I would like to see (en, en-US,en-GB). Basically I end up with the correct URL dimension fallback chain, but the dimension switcher is disabled and the pagetree is empty. If I do a reload (the URL is correct at this point) everything works fine.

**Comment by dimaip** [comment]
Hey @davidspiola, I did my best to reproduce the issue on a demo site, but didn't manage to do so.
I suggest we could try to debug this issue together on your installation, I guess that could be the fastest way to tackle it.

**Comment by davidspiola** [comment]
alright, when do you want to do that?

**Comment by grebaldi** [comment]
Hi @davidspiola and @dimaip,

did the two of you ever get to reproduce this issue? Can you verify whether it is still present in recent versions?

**Comment by Sebobo** [comment]
I will close this now and it can be reopened if necessary
