### ISSUE TITLE
Media tool close button overlays user menu dropdown

### ISSUE THREAD

**Issue by KPeschke** [neos/neos-ui#2140]
### Description
Wrong z-index for close button on media tools, e.g. cropping tool. 

### Steps to Reproduce
1. Open the media module or the cropping module from within the inspector 
2. Open the user menu

#### Expected behavior
![image](https://user-images.githubusercontent.com/8969952/45996693-64e61980-c09d-11e8-9135-fffe3f04050a.png)

#### Actual behavior
![image](https://user-images.githubusercontent.com/8969952/45996701-6b749100-c09d-11e8-88ba-a668838a568c.png)

### Affected Versions
Neos: v3.3.14
UI: v1.1.2 - v1.3.3

**Comment by johannessteu** [comment]
I'll take care
