### ISSUE TITLE
CK 5 Editor and placeholder

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#2146]
In CK 5, the placeholder text is added via a data-attribute which is a very nice idea. But because the CSS class `[data-neos-placeholder]::before` has the declaration `position: absolute` it will get a bit messy if you have a longer placeholder text.

## CK Editor 4
<img width="774" alt="Screenshot CK Editor 4" src="https://user-images.githubusercontent.com/4510166/46145043-1d0ef000-c25f-11e8-8c58-f35fab527585.png">

## CK Editor 5
<img width="773" alt="Screenshot CK Editor 5" src="https://user-images.githubusercontent.com/4510166/46145067-3152ed00-c25f-11e8-9cfb-20c8502eb4d3.png">

**Comment by dimaip** [comment]
Nice catch. Any idea how to fix it? `position: relative` on parent?

**Comment by jonnitto** [comment]
`position: relative` could fix the overflow horizontally, but not vertically. With `position: absolute` you lose all pieces of information about the height. It tried to remove the `position: absolute` but then it messes up with creating text…

**Comment by dimaip** [comment]
Unfortunately before CKE5 introduces a native placeholder feature, I don't know how else we could fix it better... See https://github.com/ckeditor/ckeditor5/issues/479

**Comment by danielkestler** [comment]
Has it been fixed? Because I tried to reproduce it with no success. ```[data-neos-placeholder]::before``` is not positioned absolute in my installation and therefore works perfectly. Or am I missing something?

**Comment by dimaip** [comment]
Yup, Aske fixed it a while ago
