### ISSUE TITLE
Validation logic doesn't work the same as old UI and Flow

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-ui#2199]
In Flow and the old UI a validator could declare to accept empty values and many validators did. That allowed to validate IF a value was entered but still have the field optional (you could pair with an NotEmptyValidator to prevent empty values then). The react UI doesn't seem to respect that. A StringLengthValidator on a node property with a minimum > 0 will error even if the field was empty (but wouldn't error in the old UI).

**Comment by markusguenther** [comment]
Thanks to @sbruggmann for taking care.

**Comment by bwaidelich** [comment]
Related: #2552
