### ISSUE TITLE
Disable PreviewButton when a DocumentNode is hidden

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#2204]
### Steps to Reproduce

1. Hide a DocumentNode
2. Click previewbutton

#### Expected behavior

The preview-button should be disabled because it doesn't make sense to view a page in the frontend which is hidden.

#### Actual behavior

The preview-button is clickable and the page which opens produces an error: `Validation failed while trying to call Neos\Neos\Ui\Controller\BackendController->redirectToAction(). `

### Affected Versions

Neos: 4.1

UI: 1.4.0

**Comment by bwaidelich** [comment]
I think that one is solved in the meantime
