### ISSUE TITLE
Boolean Inspector editor doesn't show help message

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#2249]
The boolean inspector editor doesn't show a help icon and the corresponding help message when clicking.
Related #1926

**Comment by maya-shines** [comment]
Hey @mstruebing is this fixed with the PR by @j6s? Can this be closed?

**Comment by markusguenther** [comment]
Yeah the `Fixes: #ID` was missing in the PR and no one closed the issue.
Thanks for tackling that Maya :)
