### ISSUE TITLE
Extensibility: neos-ui-editors not correctly exported for extensions

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-ui#2250]
The mappings for extensibility contain

`'@neos-project/neos-ui-editors': '@neos-project/neos-ui-extensibility/src/shims/neosProjectPackages/neos-ui-editors/index'`

but in fact there is no index.js in the neos-ui-editors (/src). So nothing is actually exported. We should fix that to allow embedding existing editors (or parts of them, like secondary inspectors) to be reused.

**Comment by dimaip** [comment]
Yep, the cleanest way is to just split index and manifest files, like in all other extensions.
And add tests for this :)
