### ISSUE TITLE
Moving Documents in and out of subfolders without publishing can detach childNodes since 1.3

### ISSUE THREAD

**Issue by mficzel** [neos/neos-ui#2258]
When a document is accidentally moved below another document and instantly moved one level up again it looses its childNodes after publishing. This problem usually occurs very easily when editors try to reorder documents. 

### Steps to Reproduce

1. Take a Document with content and child-documents
2. Move it below one of its siblings (like an error during sorting)
3. Move it out again
4. Publish

#### Expected behavior

This should simply work :-)

#### Actual behavior

The site shows and error that no main collection is found and all sub-nodes (contens and documents) are gone aswell but can be found in the database under the original nodePath.

### Affected Versions

Neos: 4.1 (probably 4.*)
UI: 1.3, 1.4

**Comment by dimaip** [comment]
So is this issue resolved now or not? /cc @sbruggmann

**Comment by mficzel** [comment]
It is solved from a ui perspective as soon as it is released. The underlying cr issue is still there but it will hardly be triggered.

**Comment by dimaip** [comment]
Ok, cool, then I'll close this
