### ISSUE TITLE
ckeditor5 tables centered text

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-ui#2260]
The styles for the ckeditor5 table editor contain a text-align: center which means tables potentially look different in the backend. That's not nice, we should remove it to make table editing more WYSIWYG.

**Comment by dimaip** [comment]
Makes sense. Link incoming: https://github.com/neos/neos-ui/blob/master/packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/TableStyles.vanilla-css#L160

**Comment by kdambekalns** [comment]
I fixed this in a project by using this in my (S)CSS:
```
body.neos-backend {
  .ck-content .table table td, .ck-content .table table th {
    text-align: initial;
  }
}
```
