### ISSUE TITLE
Clipboard kills Neos when Node deleted

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-ui#2261]
When you put a node into the clipboard (copy or cut), then delete said node and finally reload the UI you will be stuck in a fatal server error, because the server-side tries to hydrate the node from the clipboard but it doesn't exist anymore in the DB. 
Either the `\Neos\Neos\Ui\Controller\NodeClipboard` should store only a reference (nodecontextpath or similar) and hydrates in a try/catch or we need to take care of removing the clipboard entry on deletion.

**Comment by dimaip** [comment]
Ouch. Will take care in 1-2 days if nobody beats me to it.

**Comment by kitsunet** [comment]
I am mostly putting the stuff up here to remind myself. You don't necessarily need to do it...
