### ISSUE TITLE
Find alternative to `ReactDOM.unstable_renderSubtreeIntoContainer`

### ISSUE THREAD

**Issue by JamesAlias** [neos/neos-ui#2264]
### Description

Follow-up from #2216 
Find and evaluate alternatives to `ReactDOM.unstable_renderSubtreeIntoContainer`.

possible alternatives:
- [ ]  Portal (https://gist.github.com/robertgonzales/b1966af8d2a428a8299663b92fb2fe03)

**Comment by JamesAlias** [comment]
@dimaip I think you resolved this, right?

**Comment by dimaip** [comment]
True
