### ISSUE TITLE
ckeditor5 cannot parse ckeditor4 tables

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-ui#2288]
Tables with header rows from Aloha/ckeditor4 will not work correctly in ckeditor5 as they are not properly separated into thead and tbody as ckeditor5 expects. It will change all rows to header rows due to that, an error which editors cannot recover from and needs fixing on database level.

So a table like this (which was generated by earlier editors):

```
<table>
    <tbody>
        <tr>
            <th>Header 1</th>
        </tr>
        <tr>
            <td>Row content</td>
        </tr>
    </tbody>
</table>

```

Would be transformed by ckeditor5 to:

```
<table>
    <tbody>
        <tr>
            <th>Header 1</th>
        </tr>
        <tr>
            <th>Row content</th>
        </tr>
    </tbody>
</table>
```

And editors cannot change that back because the header rows are not in a thead.

**Comment by daniellienert** [comment]
I guess it would be best to write a core migration for the content? Or is this too breaking as the markup changes which could affect styling?

**Comment by dimaip** [comment]
@daniellienert I think the code migration should be doable and very useful!

**Comment by dimaip** [comment]
And it's better if it breaks the styling rather than completely disappears. But we should only run this migration only if CKE5 is enabled.

**Comment by kdambekalns** [comment]
I just came across this, but I could recover by unchecking the "header (row|column)" in the toolbar.

**Comment by markusguenther** [comment]
Is this still an issue? I mean, we are not maintaining the old versions anymore.
But it is still possible to enable the ck4 in the UI, I guess.

**Comment by markusguenther** [comment]
Will close this issue as we have no feedback. In Neos 8.0 the CKEditor 4 will also be removed.
So even the switch to the version is just possible until 7.3.
