### ISSUE TITLE
A created table cannot be adjusted

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#2290]
### Description

Using the table button I can insert a new table with various settings. I didn't find out, how to adjust these settings after inserting.

#### Expected behavior

Selecting the table and clicking on the table button shows the configuration dialog of the table.

#### Actual behavior

A new table is inserted.

### Affected Versions

Neos: dev-master

UI: dev -master

**Comment by dimaip** [comment]
It seems you are using CKE4, which is not deprecated.
See https://github.com/neos/neos-ui/pull/2291

**Comment by daniellienert** [comment]
Works with CK5
