### ISSUE TITLE
Dynamically hide properties in the inspector doesn't work anymore

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#2296]
### Description

Dynamically hide properties in the inspector doesn't work anymore

### Steps to Reproduce

Create a node property described here:
https://github.com/neos/neos-ui/pull/2118

#### Expected behavior

The property should show/hide depends on the other property

#### Actual behavior

Stays hidden

### Affected Versions

Neos: `4.2.4`

UI: `dev-master`

**Comment by dimaip** [comment]
Figured it out, will fix

**Comment by jonnitto** [comment]
You can give a report when it is done, I'll test that with joy :-D
