### ISSUE TITLE
Editing values in the inspector and publishing does not change publish state

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#2319]
When exchanging something in the inspector and publishing, the bar remains orange.
After a reload the bar is green and the change is persisted.

UI Version 3.0.0

![bug-publishstate](https://user-images.githubusercontent.com/642226/52045435-d1d65800-2544-11e9-948d-c0d98d2e4bde.gif)

The server response looks good:

![image](https://user-images.githubusercontent.com/642226/52045578-195ce400-2545-11e9-8b8b-54ba119f714e.png)

**Comment by dimaip** [comment]
Can't reproduce with demo site, 2.0.1 and Neos 3.3.

**Comment by daniellienert** [comment]
Does it only happen when publishing to a workspace?

**Comment by danielkestler** [comment]
Cannot reproduce, also when trying in a draft workspace.

**Comment by dimaip** [comment]
Will close for now, till new info comes in how to reproduce it.
