### ISSUE TITLE
Switch to old UI button leads to 404

### ISSUE THREAD

**Issue by aertmann** [neos/neos-ui#2321]
### Description

The legacy UI switch code was removed in #2307, however the button still appears in the new UI when the configuration is enabled.

### Steps to Reproduce

1. Set configuration `Neos.Neos.Ui.frontendConfiguration.legacy.enableUiSwitch` to `true`
2. Click button in dropdown menu in new UI

#### Expected behavior

To redirect to the old UI or the button not to exist.

#### Actual behavior

Button exists and leads to a page not found (404).

### Affected Versions

Neos: 4.2

UI: 3.0.1

**Comment by dimaip** [comment]
@daniellienert that's what I was trying to remember when reviewing you PR :)

**Comment by danielkestler** [comment]
IMO we can maybe remove this button in the meantime.

**Comment by daniellienert** [comment]
I guess so.
