### ISSUE TITLE
Removing node tree search filter triggers search

### ISSUE THREAD

**Issue by theilm** [neos/neos-ui#2339]
### Description

When removing the search string in the node tree, a search with an empty string is triggered. This leads to performance problems / server errors on large installations (see #1508).

### Steps to Reproduce

1. Enter search string as filter for node tree -> node tree is filtered
2. Remove the search string via the X-button.

#### Expected behavior

After removing the search filter, a regular neosUiDefaultNodes request should take place, e.g.:

```
{"chain":[{"type":"createContext","payload":[{"$node":"/sites/mysite@user-admin"},{"$node":"/sites/mysite/current/node@user-admin"}]},{"type":"neosUiDefaultNodes","payload":["Neos.Neos:Document",1,[],""]},{"type":"getForTree","payload":"ALL"}]}
```

#### Actual behavior

Instead, a search takes place (which is broken on larger installations):

```
{"chain":[{"type":"createContext","payload":[{"$node":"/sites/mysite@user-admin"}]},{"type":"search","payload":["","Neos.Neos:Document"]},{"type":"getForTreeWithParents","payload":""}]}
```

### Affected Versions

Neos: 3.x / 4.x

UI: 1.4.1 (but probably all)

**Comment by dimaip** [comment]
Oh yeah I also noticed this a while ago.
Fixers wanted!

**Comment by danielkestler** [comment]
This is strange. A while ago, I fixed a similar bug, see:
https://github.com/neos/neos-ui/commit/a7ed33c15f275099d93ff6c1c2363b2da9a31b5a

Maybe I introduced a new bug this way?

**Comment by theilm** [comment]
@danielkestler Yes you are right - it seems to be fixed in the current release. Sorry, apparently I overlooked the commit and did not test with master.
There seems to be a problem showing the current page in the node tree when resetting the filter; I'll do some more testing and create a new issue.
