### ISSUE TITLE
Wrong "publish all" icon

### ISSUE THREAD

**Issue by KPeschke** [neos/neos-ui#2353]
### Description
Could be a misstake in this [commit](https://github.com/neos/neos-ui/commit/28b06f81dcf8a5598d0f4545e5cbe1e5d5a7d5e9).
Instead of the previous upload icon the check-double icon is used.

#### Expected behavior
![image](https://user-images.githubusercontent.com/8969952/52807627-57512080-308c-11e9-9ce9-074c86e1aa1c.png)

#### Actual behavior
![image](https://user-images.githubusercontent.com/8969952/52807522-fcb7c480-308b-11e9-8e36-f8746361bc29.png)

### Affected Versions
Neos: 3.3.19
UI: 2.1.0

**Comment by danielkestler** [comment]
Oh, I am sorry, this was indeed an intentional change, as the old icon means „upload from harddrive“ which is not quite appropriate. Let‘s discuss better alternatives if you like 😉

**Comment by KPeschke** [comment]
Ok I understand. It looked wrong at first glance and my first thought was that the symbol is positioned incorrectly and something is cut off on the left side. :smile: The "upload-icon" is in my opinion not wrong to symbolize publishing. The icon is also explained by the label. Unfortunately, in the free version of Font-Awesome, the "arrow-to-up-icon" is not available. :disappointed: In Google Material Design this is used to symbolize publishing. (https://material.io/tools/icons/?style=baseline section editor - publish) You may also use the "share-icon" - make the content available to the / share with public.

By the way, great style improvements. :heart_eyes: 👍

**Comment by dimaip** [comment]
I personally have nothing against the new icon and I agree do Daniel's argument.

**Comment by danielkestler** [comment]
Closing this for now – feel free to reopen if you think otherwise.
