### ISSUE TITLE
ckeditor5 tables problems

### ISSUE THREAD

**Issue by KPeschke** [neos/neos-ui#2354]
### Description
There are more problems with tables in addition to [ckeditor5 tables centered text](https://github.com/neos/neos-ui/issues/2260).

### Steps to Reproduce in backend
1. create a table
2. algin table cells with alignment options - works for now with align right, if you doesn't reset the alignment for backend by yourself
3. publish - in frontend the alignment is visible
4. reload the page in backend - all alignment settings are gone
5. edit something in the table
3. publish again

#### Expected behavior
After reload the page in backend all alignment settings are readded, visible and can be stored 

#### Actual behavior
After reload the page in backend all alignment settings are **removed** and not visible any more. Any changes on this table and republish changes reset the frontend too.

### Affected Versions
Neos: 3.319
UI: 2.1.0

**Comment by christophengelmayer** [comment]
I can confirm that this happens in 
UI: 2.1.0 (Neos: 3.3)
but not in
UI: 2.9.0 (Neos: 3.3).

Looks like this issue has been fixed somewhere between UI version 2.1 and 2.9.

**Comment by dimaip** [comment]
Thanks for checking @christophengelmayer!
