### ISSUE TITLE
NodeType changes need to consider constraints

### ISSUE THREAD

**Issue by rolandschuetz** [neos/neos-ui#2355]
### Description

The NodeType switcher currently does not consider constraints. Let's say I have the following NodeTypes:
```
MyCompany.MySite:Content.Slider (Neos.Neos:Content + Neos.Neos:ContentCollection)
MyCompany.MySite:Content.Slider.Item  (Neos.Neos:Content)
MyCompany.MySite:Content.Image  (Neos.Neos:Content)
```

### Steps to Reproduce

1. Create a `MyCompany.MySite:Content.Slider`
2. Inside create a `MyCompany.MySite:Content.Slider.Item`
3. Change the type to `MyCompany.MySite:Content.Image`

#### Expected behavior

Switching to NodeTypes, which cause an invalid state should not be possible

#### Actual behavior

I have `MyCompany.MySite:Content.Image` which has a disallowed child node `MyCompany.MySite:Content.Slider.Item`

### Affected Versions

Neos: 4.2

UI: 3.1

**Comment by sbruggmann** [comment]
@rolandschuetz On Neos Demo not reproducable with Neos 3.3 / UI 2.x and Neos 4.2 / UI 3.x

Is this still a thing?

**Comment by dimaip** [comment]
Let's close till we have new info on this one.

**Comment by rolandschuetz** [comment]
I tested it and on the newest UI, this is definitely fixed.
