### ISSUE TITLE
Content elements inspector has Copy button always active

### ISSUE THREAD

**Issue by soee** [neos/neos-ui#2359]
### Description

Content elements inspector has the Copy button always active - even if there is no any item selected. This leads to an error beeing thrown by Neos.

### Steps to Reproduce

1. Open backend interface
2. Check content elements inspector controls
3. Copy button is active

#### Expected behavior

Copy button should be disabled until 1 content element is focused

#### Actual behavior

![Inspector](https://i.imgur.com/2ub2M1g.png)

There is not element selected but Copy button is active.

### Affected Versions

Neos: 4.2.5

UI: 3.1.0

**Comment by dimaip** [comment]
This one should have been fixed, reopen if not
