### ISSUE TITLE
FEATURE: Add own icon font / pass svg string

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#2370]
## This feature request is all about the icons in the backend

Even there are a lot more icons now, sometimes those who are available are not enough. So it would be really nice to have the possibility to add other icons:

1. Replace the font-awesome font with the pro version (If someone has the license)
2. Pass directly an SVG string 
```
<svg height="100%" width="100%" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="currentColor" /></svg>
```
3. Pass a file with a eel helper: `${File.readFile(filepath)}`

**Comment by danielkestler** [comment]
I like option 2.

**Comment by DrillSergeant** [comment]
I would love this feature, sometimes the Icons of FontAwesome are just not the one we need. I would love to have option 2 and option 3 (I think I would use option 3 more than option 2)

**Comment by jonnitto** [comment]
Option 2 and 3 are basically the same, just with the difference that we run some eel helper on the icon property (just like `label`). Another benefit of this option would be that we could change the icon depending on a node property

**Comment by mficzel** [comment]
There is a discuss post pointing to an api in font-awesome that allows to add custom icons. https://discuss.neos.io/t/add-a-custom-icon-to-fontawesome/5402 

I also found an article that explains this approach a bit deeper https://dev.to/astagi/add-custom-icons-to-font-awesome-4m67

Maybe we can create a setting where we define additional custom icons where needed. That would be awesome.

**Comment by paavo** [comment]
The feature `Replace the font-awesome font with the pro version` wasn't implemented, right @markusguenther?
"only" adding a Link to an .svg Icon was done by @jonnitto?

Any known workaround to change Fontawesome to Pro in Neos Backend?
