### ISSUE TITLE
Empty-Collection overlay disappears when adding more nodes to page (outside of collections)

### ISSUE THREAD

**Issue by beheist** [neos/neos-ui#2376]
### Description

This animation documents the issue:

![screenflow](https://user-images.githubusercontent.com/10347669/53340440-53819180-3909-11e9-9e1f-e6d49230c6f0.gif)

### Steps to Reproduce

See video

#### Expected behavior

Empty collection overlays should be still rendered after new content is added

#### Actual behavior

The first empty collection overlay on the current page disappears (is not rendered anymore) after a content node is added.

### Affected Versions

Neos: Tried with 4.2 and 4.0

UI: Tried with 3.0.x and 3.1

You can get this information by running `composer show` or using the package management module within Neos.
The UI version can also be found inside the left sidebar after version 1.0.3.

**Comment by dimaip** [comment]
I don't get it. Empty collection overlays should only be shown when a collection is empty... If you add something inside it stops being empty.

**Comment by beheist** [comment]
Hey @dimaip :) I'm not adding things inside. I'm adding more nodes to the page, as siblings of the columns. The content collections are still empty, but the overlay is not displayed anymore. Did you check the gif?

**Comment by dimaip** [comment]
Ah, sorry, missed it.

In that case this is indeed a bug and it's looking for some nice person who could fix it :)

**Comment by beheist** [comment]
if anyone else encounters this while it's not fixed, this CSS works around the issue:
```
.neos-contentcollection:empty {
  height: 20px;
  width: 100%;
  box-shadow: inset 0 0 0 2px #adadad 
}
```
