### ISSUE TITLE
fetchPolicies sends "undefined" as node context path to server

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-ui#2378]
### Description

I am seeing this after upgrading from 1.4.1 to 3.1.0 (the same happens with 3.0.2):

- log in to Neos
- UI loads fine, content appears in frame
- Trees stay empty, showing just a spinner
- URL changes to `…/neos/content?node=undefined`

The browser console shows a 505 when POSTing to `…/neos/ui-services/get-policy-info`. The server complains about `Could not convert target type "array<Neos\ContentRepository\Domain\Model\NodeInterface>", at property path "38": Only absolute paths are allowed for Context::getNode()` which is the result of this being submitted:

<img width="630" alt="get-policies-request" src="https://user-images.githubusercontent.com/95873/53560188-1bb65c00-3b4c-11e9-94b7-55f3b7605fa1.png">

Where does that `undefined` come from? I know the request is dispatched in `fetchPolicies`, called from within `watchNodeInformationChanges` in the UI, but anything further is beyond me right now.

Any help appreciated, if you need further details, let me know.

### Affected Versions

Neos: 4.2
UI: 3.1.0, 3.0.2

**Comment by dimaip** [comment]
Needs debugging. The usual tools are Chrome devtools + redux devtools + react devtools.
I can try to help tomorrow if we have a call and you share the screen. Or you can try to debug it yourself.

**Comment by kdambekalns** [comment]
Huh… whatever it was, it's gone. It was not the browser cache, that's for sure. But mayne something with the files was weird after the `composer update`. Either way, I just logged in using Chrome, and it worked. Went back to Firefox, to make sure it wasn't a browser issue, nope, working there as well.

Closing this, if it ever happens again, I'll reopen.
