### ISSUE TITLE
Order of positional sorting is inconsistent with Flow

### ISSUE THREAD

**Issue by PRGfx** [neos/neos-ui#2379]
### Description

The positional array sorter claims to sort by _weight_, when using a keyword like `end`, `start` etc. implying items weighted higher to appear before items with a lower weight.

### Steps to Reproduce

1. set node-types' `ui.position` to e.g. `start 10` and `start 20`
2. see new node dialog

#### Expected behavior

When sorting by weight, the items should be sorted in descending order. Compare the Flow test-case:
https://github.com/neos/flow-development-collection/blob/master/Neos.Utility.Arrays/Tests/Unit/PositionalArraySorterTest.php#L79

#### Actual behavior

Items with weight are sorted according to ascending weight as per the sorter's test:
https://github.com/neos/neos-ui/blob/643338e7e08ca128319dc0100a6e73325db5ea8e/packages/positional-array-sorter/src/positionalArraySorter.spec.js

### Affected Versions
UI 1.4.1; quoted code is from current master

**Comment by dimaip** [comment]
Oh, could catch!

**Comment by PRGfx** [comment]
After I had a more thorough look at the current implementation, I got curious about the `positionValue.includes('start')` [parts](https://github.com/neos/neos-ui/blob/8c81506206fafa446357882bae8ce598112d6733/packages/positional-array-sorter/src/positionalArraySorter.ts#L60). Are there real-life problems that led to `includes()` over `startsWith()` (or `trim().startsWith()`)? The current implementation would mess up sorting with keys using these "keywords", e.g.
```
[
  {position: 'after start'},
  {position: 'start'},
  {position: 'end'},
  {key: 'start'}
]
```
`position: after start` contains `start` and precedes `position: start` so it would go first rather than after the "middle key" `start`.

Other than that I would amend my initial issue by noting that sorting by weight would need to happen ascending or descending depending on the positioning being `before` or `end` and `after` or `start` respectively.

Maybe I get to create an alternative implementation in the next days.

**Comment by dimaip** [comment]
Thanks for your thorough research, the fix would indeed be very welcome.

> Are there real-life problems that led to includes() over startsWith() (or trim().startsWith())? 

Can't answer that at the moment. In any case, the Flow implementation should be the reference I'd say.

**Comment by PRGfx** [comment]
It took some time but now I've completely rewritten the thing according to my prior re-implementation of the php version in C# (that's why I was confident, I would have gotten here sooner...).
https://github.com/PRGfx/neos-ui/commit/225994d19ba0017ac8cffed2480f9a0fc92507f6
Possibly it's not up to standard yet.

As for the test-cases I primarily scrapped the existing ones and imported the [sample arrays](https://github.com/neos/flow-development-collection/blob/master/Neos.Utility.Arrays/Tests/Unit/PositionalArraySorterTest.php#L63) from the php implementation. Maybe there are some JS-specific test-cases that would be good to add (e.g. regarding the "position"-value-accessor-function or dynamic types (e.g. `100 vs "100"`)).

However it seems I branched off the wrong branch so I'm hesitant to open a pull request, as it shows _a lot_ of changes from everywhere else.

**Comment by dimaip** [comment]
Wow! Thanks so much!
You can cherry-pick you commit to the right branch and open a PR.

**Comment by PRGfx** [comment]
I added some tests for the JS implementation and fixed the handling of cyclic before/after references. However I could not verify the behaviour of the original implementation (I get errors when testing these input arrays `array_walk_recursive(): recursion detected`), so the result seems a bit random in these cases.
As I don't do any checks like "is this a valid before/after reference point" like they were in place before and just clean up any "orphans" without reference point (so far), there is no handling like putting these keys in the end like before. (They will be inserted before the `end` keys.)

Additionally I didn't re-add the logging on invalid position strings - they now silently "fail" and are treated as "middle keys". That might be something to change.
