### ISSUE TITLE
Upgrade dependency monet

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2424]
### Description

The package monet for image cropper is outdated

#### Expected behavior

Monet is up to date

#### Actual behavior

Actually the version 0.8 is outdated.

### Affected Versions

Neos: 4.2

UI:2.x

**Comment by dimaip** [comment]
Thanks for taking care of that stuff!
Btw, I don't think it's really necessary to create an issue for such small stuff that you've already done...
Personally I only create an issue if I don't plan to immediately submit a PR.
