### ISSUE TITLE
Scrollbar colours inconsistency

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#2428]
Main scrollbar is still of the old colour. /cc @danielkestler 

![image](https://user-images.githubusercontent.com/837032/55062960-091a3e80-5088-11e9-917b-d8bb15aca061.png)

**Comment by danielkestler** [comment]
Are you sure you have cleared your browser's cache completely? As the styling of the guest scrollbar is in a different file inside the iFrame which is quite resistent to reloading the page.

**Comment by dimaip** [comment]
Oups, hard reload helped indeed. Sorry for the noise.
