### ISSUE TITLE
Elements flow out of "Create New" dialog, if there are too many

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-ui#2429]
I just updated the UI in one of our projects to 3.2.1 and the Nodes that I can select in the  Node Creation Dialog overflow at the bottom of the modal. In previous versions, I'd have to scroll to see all of them. The scrolling doesn't work now.

![image](https://user-images.githubusercontent.com/6552092/55077432-01fb2c80-5098-11e9-90da-d60df2bd98ee.png)

**Comment by dimaip** [comment]
Can confirm. Would be actually nice to fix this before we announce the release. Would you have some spare minutes @danielkestler or should somebody else look into it?

**Comment by Sebobo** [comment]
Setting `overflow-y: auto;` for the wrap would solve it but doesn't look so nice. So some feedback from @danielkestler would be best.

**Comment by danielkestler** [comment]
I will have a look at it tomorrow!

**Comment by markusguenther** [comment]
Can be an issue because of the select box change. To be able to float out the selectbox content I changed the overflow value.

But did not see this behaviour while testing :/

https://github.com/neos/neos-ui/pull/2398/files

**Comment by danielkestler** [comment]
It is indeed related to the overflow-change. I have no solution as to revert this change and maybe find a different solution (z-index?) for the selectbox-change – what do you think, @markusguenther, are there other possibilities to make the selectbox work?

**Comment by markusguenther** [comment]
@danielkestler I need to investigate this again. Will try to take a look soonish. But for the release it is maybe better to revert it first :/

**Comment by dimaip** [comment]
Yes please! Let's revert, it's a way more critical issue obviously. Then I'll announce the release.

**Comment by danielkestler** [comment]
@markusguenther Will you revert it?

**Comment by markusguenther** [comment]
The revert is on the way. Created a PR for that because I did not know how to handle that.

**Comment by markusguenther** [comment]
Will search for a new solution later :/

**Comment by markusguenther** [comment]
Change is reverted now and this works like before. So guess we can close this topic and I need more nodes-types for testing the next try ;)

**Comment by maya-shines** [comment]
@markusguenther Or you can let me know and I'll test it with my vast amount of nodetypes! :)

**Comment by markusguenther** [comment]
@Maya-shines ok can request your review then :)
