### ISSUE TITLE
Configured child nodes can be deleted

### ISSUE THREAD

**Issue by maya-shines** [neos/neos-ui#2437]
### Description

Auto-created child nodes can be deleted, even though the delete button is disabled

### Steps to Reproduce

1. Click on an automatically created child node
2. Click the (disabled) delete button
3. Confirm the deletion
4. Publish
5. Watch it burn

#### Expected behavior

Auto-generated child nodes shouldn't be removable/disabled buttons should not be clickable (I'm unsure what the real problem is here...?)

#### Actual behavior

The node is removed and upon reload, there's an exception

### Affected Versions

Neos 4.2.9 und Neos-UI 3.2.1

(@daniellienert will try to add a screencast)

**Comment by jonnitto** [comment]
This happens to one of our content editors today with a content collection.

**Comment by dimaip** [comment]
For anyone who'd be fixing this bug: the `disabled` prop doesn't get passed down from IconButton to Button. Should be an easy (and urgent!) fix

**Comment by jonnitto** [comment]
Thank you @pmaas for the quick fix, and thank you @dimaip for all your support! ❤️
