### ISSUE TITLE
Synchronous wait -Clarification

### ISSUE THREAD

**Issue by PonmaniAnnamalai** [neos/neos-ui#2463]
Hi,
I am automating a site using testcafe. After successful login, it has to wait the home page to be loaded successfully, 
Actual:
The browser gets closed before the page is loaded.
Clarification:
Can wait for page load can be done using testcafe-react-selectors.If so can you please provide me that piece of code
I tried beforeEach but in vain.
Or can you suggest me any utilities to make it sure that page is loaded before getting closed.

**Comment by dimaip** [comment]
Hi @PonmaniAnnamalai! Sorry, I didn't quite follow how this issue relates to neos-ui. Closing for now, please re-open if does.
