### ISSUE TITLE
Property editor array<Assets> not working as expexted/at all

### ISSUE THREAD

**Issue by simonedelmann** [neos/neos-ui#2471]
### Description

The property editor for array<Asset> seems to be broken somehow. If the array is saved and non-empty, clicking on an asset in the media browser opens the asset's properties (title, description, ...) instead of adding the asset to the array.

Also asset search is not working entirely. Assets are never be found.

To aviod environmental influence, I could reproduce both bugs within a fresh Bitnami Neos stack (with Neos.Demo installed).

#### Steps to Reproduce

1. Fresh install of Neos + Neos.Demo site
2. Add an Neos.NodeTypes.AssetList somewhere.
3. Add one or multiple elements from media browser to the list and apply changes.
4. Try to add another element from media browser.

#### Expected behavior

In Step 4 another element should be added to the list.

#### Actual behavior

A spinning wheel appears within the property editor. 
The media browser opens the detail view, where I could edit the asset's properties (title, description, ...).

### Bug 2: Adding assets via search field

Edit: Bug 2 moved to separate issue. (https://github.com/neos/neos-ui/issues/2472)

### Affected Versions

Neos: v4.3.0
UI: v3.3.0

Tried also with Bitnami Neos stack 4.3.1.

**Comment by danielkestler** [comment]
Yes, confirmed, see my PR: https://github.com/neos/neos-ui/pull/2466

**Comment by simonedelmann** [comment]
Thank you! I will wait for your PR getting merged into the core.
I will edit my issue and move bug 2 to another issue.

**Comment by danielkestler** [comment]
Closing as the PRs are merged.
