### ISSUE TITLE
Property editor array<Assets> not finding any assets

### ISSUE THREAD

**Issue by simonedelmann** [neos/neos-ui#2472]
### Description

The search functionality within the property editor for array<Assets> does not work at all. Assets could never be found, although they're there.
(Extracted from https://github.com/neos/neos-ui/issues/2471)

#### Steps to Reproduce

1. Fresh install of Neos + Neos.Demo site
2. Add an Neos.NodeTypes.AssetList somewhere.
3. Try to add an asset via the search field. (Enter correct filename...)

#### Expected behavior

In Step 3 there should be search results.

#### Actual behavior

"No matches found", although the asset does exist and filename was correct.

### Affected Versions

Neos: v4.3.0
UI: v3.3.0

Tried also with Bitnami Neos stack 4.3.1.

**Comment by beardcoder** [comment]
Oki this problem is only in the master and not in the 2.x Branch

**Comment by markusguenther** [comment]
This issue has been resolved in the PR (https://github.com/neos/neos-ui/pull/2478) 
We will release a new UI version soonish 🎉
