### ISSUE TITLE
Title in page tree is broken when the document title contains `[en]`

### ISSUE THREAD

**Issue by 2case** [neos/neos-ui#2496]
### Description

Title in page tree is broken when the document title contains `[en]` the page tree will cut and only show `[e`

### Steps to Reproduce

1. Simple create a new page which include `[en]` in the title

#### Expected behavior

It is expected that the correct title is visible inside the page tree like in the inspector

### Affected Versions

Neos: 4.2.1ß

UI: 3.3

**Comment by markusguenther** [comment]
Ok that was easy to reproduce:

<img width="296" alt="Bildschirmfoto 2019-05-20 um 08 10 45" src="https://user-images.githubusercontent.com/1014126/57999766-dc5a3480-7ad6-11e9-9403-0c303e174a98.png">
<img width="307" alt="Bildschirmfoto 2019-05-20 um 08 10 51" src="https://user-images.githubusercontent.com/1014126/57999767-dc5a3480-7ad6-11e9-88f1-50256bbcc957.png">

**Comment by PRGfx** [comment]
The `Neos.Neos:Node` label [replaces](https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Configuration/NodeTypes.Node.yaml#L3) `<br\W*?\/?>|\x{00a0}|[[^:print:]]|\s+`. Like that it will strip `[:print]\]` from all (standard) node labels. It would have to be `[^[:print:]]` instead. (Additionally it will strip tag-like content (e.g. `1 < 2` will display as `1`).
