### ISSUE TITLE
`@neos-project/build-essentials` only installable using yarn

### ISSUE THREAD

**Issue by j6s** [neos/neos-ui#2512]
### Description

When trying to install `@neos-project/build-essentials` the assumption is made that `rimraf` is in a particular location - however, if the project already has `rimraf` installed (lot's of node modules depend on it) somewhere else, then that assumption is not met because `npm` decides where modules are installed to.

Yarn seems to resolve paths correctly.

### Steps to Reproduce

```
$ uname -a 
Linux jo-mini 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

$ npm -v
6.4.1

$ node -v
v8.16.0

$ mkdir neos-test-npm

$ cd neos-test-npm/

$ npm install rimraf
[...]

$ npm install @neos-project/build-essentials
[...]
npm ERR! path /home/j/tmp/neos-test-npm/node_modules/@neos-project/build-essentials/node_modules/.bin/rimraf
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/j/tmp/neos-test-npm/node_modules/@neos-project/build-essentials/node_modules/.bin/rimraf'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/j/.npm/_logs/2019-06-12T11_10_51_878Z-debug.log
```

#### Expected behavior

`@neos-project/build-essentials` can be installed using `npm`.

#### Actual behavior

See error above.

### Affected Versions

As far as I could gather all versions of the package are affected.

**Comment by dimaip** [comment]
Hi! Thanks for investigating!
But should we really bother supporting npm? I thought we had `yarn` commands in all the instructions? E.g. yarn has files and we rely on those...

**Comment by j6s** [comment]
I don't think ignoring the language default tool for a task (npm for installing node modules) is a good strategy as it alienates a lot of potential users and developers.

In my specific case it is policy to use `npm` and I had to move this one project over to `yarn` despite that in order to use this package.

**Comment by markusguenther** [comment]
I am also not sure if we should support both. The community (javascript) made a big shift in the yarn direction and also just provide the yarn.lock instead of a package-lock.json and so on.

But we can create a discuss post for that and can try to find a team and community wide decision. What do you think?

**Comment by kdambekalns** [comment]
yarn FTW

**Comment by markusguenther** [comment]
I guess we can close this by now, as no one started the discussion!
