### ISSUE TITLE
Release 3.6.0 has wrong neos version dependency

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-ui#2516]

**Comment by markusguenther** [comment]
Do you think we should change that? Or why do you create this issue?
I mean without force pushing we could not achieve that and this would also break something.

**Comment by kitsunet** [comment]
Haha, I didn't plan to make a fixed release right away, but it happened, so we can close this now :D It was more a marker for "we need a release with correct dpeendencies ASAP"
