### ISSUE TITLE
Table Icon is too big

### ISSUE THREAD

**Issue by MarcoPNS** [neos/neos-ui#2518]
### Description

After Upgrading from v3.5 to v3.6.1 the icon for the table in CKEditor is just too big.

### Steps to Reproduce

1. Install newest Neos Version
2. Create a Table

#### Expected behavior

small icon

#### Actual behavior

![image](https://user-images.githubusercontent.com/35105681/59664527-80f09480-91b1-11e9-87c6-3b469dde046d.png)

### Affected Versions

Neos: 4.3.3

UI: 3.6.1

**Comment by MarcoPNS** [comment]
In the figure of the table is a class missing: `ck-widget_selectable`

**Comment by Sebobo** [comment]
Thanks for the bugreport!

Seems to be a css class change, so I will adapt the css in a PR. The classes come from the ckeditor, so we have to follow their styling.
