### ISSUE TITLE
Remove ramda as dependency

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2522]
### Description

We use ramda and lodash at the moment. And we use way less ramda then lodash.
I personally dislike this libraries and would prefer own little helpers instead and ES6, but thats a different story.

I would like to lower the dependencies and replace ramda with ES6 and bit lodash code.

#### Expected behavior

Same working UI with less dependencies to maintain.

#### Actual behavior

lodash and ramda in coexistence.

**Comment by dimaip** [comment]
ramda is actually really cool library, but FP-oriented. But for the pragmatic reasons I don't mind throwing it away, we are not using it that much.

**Comment by johachi** [comment]
I will take on this PR

**Comment by johachi** [comment]
I'm currently replacing Ramda with Lodash now, but I had one question, why are you removing Ramda and keeping Lodash, and not the other way around?

**Comment by markusguenther** [comment]
Thanks for taking care and welcome in the neos community as well.

The intention was to have just one of those libraries and ramda is not used that much. So it is less effort to replace ramda.

We have plenty of dependencies and would be nice to shrink that a bit.

Thanks 🙏

**Comment by dimaip** [comment]
My take on this:
Ramda is more functional, Lodash is more mainstream. Since people who were more into hardcore FP stuff are not around now (I mean you @bwaidelich and @Inkdpixels ;) ), it makes sense to keep the more "pop" version, especially that most of codebase already uses it.
But personally I really don't care of what we are going to end up using, no strong opinions on the topic.

**Comment by bwaidelich** [comment]
> Since people who were more into hardcore FP stuff are not around now (I mean you @bwaidelich

Me and "hardcore FP" in one phrase.. a first timer :D

**Comment by dimaip** [comment]
Lol I meant @grebaldi, autocomplete slip...

**Comment by johachi** [comment]
Just writing to let you know that I have not forgotten this. I have done the code changes, just need to test so it works. I'm currently setting up the environment.

**Comment by markusguenther** [comment]
If you need help with that just ping us :)

**Comment by markusguenther** [comment]
@johachi No problem, take your time. And it is awesome that you pick up that task :)

**Comment by johachi** [comment]
Hi @markusguenther ,

I keep getting the error below. Do you have any suggestions on how to solve this?

```
Warning: Uncaught Neos\Flow\Error\Exception: Warning: require(/Users/johachi/neos-example/Data/Temporary/Development/Doctrine/Proxies/__CG__NeosContentRepositoryDomainModelNodeData.php): failed to open stream: No such file or directory in /Users/johachi/neos-example/Packages/Libraries/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php line 206 in /Users/johachi/neos-example/Packages/Framework/Neos.Flow/Classes/Error/ErrorHandler.php:81 Stack trace: #0 /Users/johachi/neos-example/Packages/Libraries/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(206): Neos\Flow\Error\ErrorHandler->handleError(2, 'require(/Users/...', '/Users/johachi/...', 206, Array) #1 /Users/johachi/neos-example/Packages/Libraries/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(206): require() #2 /Users/johachi/neos-example/Packages/Libraries/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(116): Doctrine\Common\Proxy\AbstractProxyFactory->getProxyDefinition('Neos\\ContentRep...' in /Users/johachi/neos-example/Packages/Framework/Neos.Flow/Classes/Error/ErrorHandler.php on line 81

Fatal error: Doctrine\Common\Proxy\AbstractProxyFactory::getProxyDefinition(): Failed opening required '/Users/johachi/neos-example/Data/Temporary/Development/Doctrine/Proxies/__CG__NeosContentRepositoryDomainModelNodeData.php' (include_path='.:/usr/local/Cellar/php/7.3.11/share/php/pear') in /Users/johachi/neos-example/Packages/Libraries/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 206
```

**Comment by johachi** [comment]
I was able to get above to work properly by doing a reinstall and increasing php memory limit.
