### ISSUE TITLE
Warning about Browserslist for postcss (build-essentials)

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-ui#2539]
### Description

The `browsers` option given should be replaced with new config.

### Steps to Reproduce

1. run `yarn run build` in some package using `@neos-project/build-essentials`

#### Expected behavior

No error message.

#### Actual behavior

```
  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist
```

caused by https://github.com/neos/neos-ui/blob/73bb95ca51a25ce8818b53e6eb9aa0f57b80c352/packages/build-essentials/src/postcss.config.js#L6-L8

### Affected Versions

UI: all? the file causing this has not been touched for two years.

**Comment by markusguenther** [comment]
Thanks for reporting @kdambekalns 
Created a PR for that. Hope that everything is solved now :)
