### ISSUE TITLE
Inspector can be submitted by pressing enter despite validation failure

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-ui#2554]
### Description

Changes in the inspector can be submitted by pressing enter, even though validation failures are present.

### Steps to Reproduce

1. Change a value in the inspector
2. Make sure some inspector fails validation
3. Submit the changes by pressing enter (in a single-line input field)

#### Expected behavior

No form submission, since the apply button is inactive, too.

#### Actual behavior

The changes are submitted.

### Affected Versions

Neos: 4.3

UI: 3.8.1

**Comment by dimaip** [comment]
uh that's nasty!

**Comment by dimaip** [comment]
I'll take this one
