### ISSUE TITLE
Spaces are removed between two marked words

### ISSUE THREAD

**Issue by Lemmork** [neos/neos-ui#2593]
### Description

If you mark two words in the backend (ckeditor5) which are divided by a space as e.g. bold and italic the space between these words are removed in frontend.

### Steps to Reproduce

1. Add inline text in ckeditor5 in the backend: Lorem ipsum dolor sit
2. Mark the word "ipsum" and click the bold button.
3. Mark the word "dolor" and click the italic button
4. Publish and open frontend view.
5. Output will be Lorem **ipsum**_dolor_ sit

#### Expected behavior

The space between marked words must be preserved. 
Output should be Lorem **ipsum** _dolor_ sit

#### Actual behavior

Output is Lorem **ipsum**_dolor_ sit

[What actually happened]

### Affected Versions

Neos: 4.3.7

UI: 4.0.1

**Comment by markusguenther** [comment]
Thanks for reporting that ❤️

**Comment by dimaip** [comment]
Hi @Lemmork! Thanks for reporting!
Can you reproduce this behaviour on the clean install of the demo site? I wasn't.
Could it be something related to your local styles? What markup do you get in HTML?
Here's what I get:
![image](https://user-images.githubusercontent.com/837032/69940479-74f45700-14f3-11ea-9cb9-f874d4f271f8.png)

Closing for now, feel free to re-open with more info!

**Comment by Lemmork** [comment]
Hi @dimaip, thanks for testing.
You are right, it is not a bug of neos-ui.
It turns out, that this behaviour comes up, when using flownative/neos-compressor

**Comment by dimaip** [comment]
Ah, makes sense, probably it just removes line breaks without adding a space.

**Comment by Lemmork** [comment]
Seems as the newer version of html-compress fixes this. I will open an issue at flownative/neos-compressor
