### ISSUE TITLE
Empty Create Dialog

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2610]
### Description

In Version 5.1 we integrated the Node Creation Handler for the "CreationDialogProperties".
This seems to lead to an issue when you don`t configure node types with properties for the create dialog.

I setup a brand new and clean instance of neos 5.1 with the neos.demo site package.

### Steps to Reproduce

1. Create a new page (works)
2. Create a new headline leads to an empty create dialog and you need to double click the confirm button.

#### Expected behavior

No create dialog for the headline node.

#### Actual behavior

Empty create dialog for the headline node.
![create-dialog-bug](https://user-images.githubusercontent.com/1014126/70649317-324a2180-1c4d-11ea-9241-90d5c8e06348.gif)

### Affected Versions

Neos: 5.1

UI: 5.0

**Comment by markusguenther** [comment]
@bwaidelich is already fixing this issue in neos.neos

https://github.com/neos/neos-development-collection/pull/2830

**Comment by Benjamin-K** [comment]
I think, this has already been fixed.
