### ISSUE TITLE
Version 2.9.2 cannot be installed, because dependency not available on packagist

### ISSUE THREAD

**Issue by koehnlein** [neos/neos-ui#2622]
### Description

Version 2.9.2 cannot be installed, because the required package `neos/neos-ui-compiled` is not available on packagist in version 2.9.2

### Steps to Reproduce

1. Open your Neos 3.3 project
2. run `composer require neos/neos-ui:^2.9.2`
3. See this error message:

```
  Problem 1
    - Installation request for neos/neos-ui ^2.9.2 -> satisfiable by neos/neos-ui[2.9.2].
    - neos/neos-ui 2.9.2 requires neos/neos-ui-compiled 2.9.2 -> no matching package found.
```

#### Expected behavior

The version 2.9.2 should be installable

#### Actual behavior

https://packagist.org/packages/neos/neos-ui-compiled#2.9.2 does not exist
https://packagist.org/packages/neos/neos-ui-compiled#2.9.1 does not exist
https://packagist.org/packages/neos/neos-ui-compiled#2.9.0 does exist

### Affected Versions

Neos: 3.3

UI: 2.9.1 and 2.9.2

**Comment by jonnitto** [comment]
Hm, it seems that the compiled UI doesn't have the needed tag… https://github.com/neos/neos-ui-compiled/releases 

### Therer are several release missing
* 2.9.1
* 2.9.2
* 1.4.0-beta
* 1.2.0
* 0.0.7-automaticRelease
* 0.0.8-automaticRelease

I think everything below 2.9 is not that important, but 2.9.2 should be available, as it is the version for Neos 3.3.* 
@markusguenther Do you know how we can trigger this?

**Comment by markusguenther** [comment]
Hmm need to check the Jenkins job. Because we don`t  create them manually for the neos-ui-compiled.
Need to check that later...

**Comment by markusguenther** [comment]
Ok checked it and in commit https://github.com/neos/jenkinsneosio-configuration/commit/70c765129951d50bd692fa35e0dd4e1c53a0e140

the branch 2.x has been removed from the Job.
I added the branch again and triggered the last job to rerun.
So hopfully after that the branches are available then.

Thank @koehnlein for reporting that 👍

**Comment by koehnlein** [comment]
>  So hopfully after that the branches are available then.

I'm sorry, but that seems not to have solved the problem.

**Comment by markusguenther** [comment]
![Bildschirmfoto 2019-12-18 um 20 23 58](https://user-images.githubusercontent.com/1014126/71116396-62a53900-21d4-11ea-9158-5d32a0120217.png)
![Bildschirmfoto 2019-12-18 um 19 37 48](https://user-images.githubusercontent.com/1014126/71116407-689b1a00-21d4-11ea-8414-c46c6c9ab477.png)

It works now ;)
Thank you for the hint :)

**Comment by kdambekalns** [comment]
Well – you should be using a more current version of $everything… ;)

**Comment by kdambekalns** [comment]
But thanks to @koehnlein for reporting and to @markusguenther for fixing!

**Comment by koehnlein** [comment]
> Well – you should be using a more current version of $everything… ;)

I know. But that's not the topic if this issue. ;)


Thanks to everyone, who was involved in solving this problem! 👍
