### ISSUE TITLE
Login screen keeps flashing in guest frame

### ISSUE THREAD

**Issue by gerhard-boden** [neos/neos-ui#2644]
When authentication authentication has failed (or the session timed out) the login page is flashing in an endless loop behind the login overlay.

![flickering_login](https://user-images.githubusercontent.com/10533739/72000900-978d3480-3244-11ea-8ccc-64c5bd70bae0.gif)

**Comment by Sebobo** [comment]
Is this still the case for you? If yes, which version?

For me there is no flashing in the background.

**Comment by Sebobo** [comment]
And duplicate of #2590
