### ISSUE TITLE
Document-Tree refresh crashes backend

### ISSUE THREAD

**Issue by eWert-Online** [neos/neos-ui#2652]
### Description

When refreshing the document tree, the inspector starts loading for an infinite amount of time. When you afterwards try to click in an Inline-Editable field, the backend crashes.

### Steps to Reproduce

1. Refresh the Document Tree (second Button from the right)

#### Expected behavior

- The document tree refreshes
- The inspector doesn't start loading

#### Actual behavior

![document-tree-bug](https://user-images.githubusercontent.com/7459510/72614009-6fcb5a00-3931-11ea-9477-f334c91bff4c.gif)

1. The inspector starts loading
2. When clicking in an inline-editable field, the whole backend crashes

### Affected Versions

Neos: 5.1.3
UI: 5.1.2

**Comment by Sebobo** [comment]
Can reproduce, will look into it.

**Comment by Sebobo** [comment]
PR is ready to fix this.
