### ISSUE TITLE
make build fails because of node version mismatch

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-ui#2654]
Lately a lot of dependencies are being updated but those updates ignored our defined node version in our .nvmrc.
Currently make install fails as some dependencies.

I assume this happens as we don't have a node version defined in our package.json.
Should we simply add it there, or is there a reason why we don't have it?

**Comment by Sebobo** [comment]
This already happened before btw. At the time I adjusted the .nvmrc

**Comment by dimaip** [comment]
I'm sorry, I don't understand the issue. Where does it fail? Locally? In CI?

**Comment by Sebobo** [comment]
Locally. `make install` fails when you use `nvm` or have some other global node version that doesn't match.
