### ISSUE TITLE
Upgrade to babel 7

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2661]
We are using the old versions of babel 6 and with babel 7 it has changed alot.
As we are now having issues upgrading other packages like jest, tslint and so on to the latest versions we need to change to babel version 7 and the new module structure.

So now they use @babel/core instead of babel-core and so on.
There is an upgrade guide.

https://babeljs.io/docs/en/v7-migration

**Comment by mhsdesign** [comment]
good first issue xD

**Comment by mhsdesign** [comment]
this will be replaced with #3200

**Comment by mhsdesign** [comment]
horray we are using esbuild now ;) so lets close this finally.
(thanks for your work on the babel upgrade though ;))
