### ISSUE TITLE
Migrate from tslint to eslint

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2662]
TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information. So we need to remove tslint and our two plugins and replace them with some eslint rules. So eslint now also takes care of typescript!

Upgrading to the latest version 6 makes no sense as since december 2019 the package gets no PRs anymore.

**Comment by mhsdesign** [comment]
closing as dub
