### ISSUE TITLE
Renaming document node does not refresh the document tree

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-ui#2665]
If you change the title of a document node and apply that change, the document tree doesn't get updated and still shows the old title.

### Steps to Reproduce

1. Open a document node in backend
2. Change title of the document
3. Apply changes

#### Expected behavior

Title of the document has to be changed to the new one. Also the document tree should show the new title of this node.

#### Actual behavior

The document tree stays the same and still shows the old title.

### Affected Versions

Neos: 5.1.4
UI: 5.1.2

**Comment by gerdemann** [comment]
I think the problem also exists in the content tree.

**Comment by rolandschuetz** [comment]
I guess this problem is related, newly created pages disappear from the list:
https://youtu.be/3uiKxCPcPXo

**Comment by Sebobo** [comment]
This is due to #2578 and the method that merges the changed node with the existing one behaves different since then.
I'll try to fix this.

**Comment by Sebobo** [comment]
@rolandschuetz I could fix the update issue, but I couldn't reproduce an issue with a page disappearing.
Can you reproduce it with the Demo site?
