### ISSUE TITLE
Focus first input element / the title element, when a new document is created

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#2696]
### Description

![image](https://user-images.githubusercontent.com/642226/78010366-9438af00-7342-11ea-9cb5-a62ebc4231dc.png)

When I add a new docuentNode, I have to click the title element manually, even if it is the only element. Which is unexpected and really anoying when creating a lot of pages.

Neos UI: 5.1.x / master

**Comment by markusguenther** [comment]
As it was intended but just did not work, I created a BUGFIX PR against 4.0 and this should work then in all versions :)

I bet that we broke it with the TS adjustment.

**Comment by daniellienert** [comment]
Wooohooo!! Thanks a lot!
