### ISSUE TITLE
Error 404 in Backend after Update 5.1.4 => 5.1.5

### ISSUE THREAD

**Issue by patriceckhart** [neos/neos-ui#2707]
I updated from 5.1.4 to 5.1.5 and now I get Error 404 in the backend when opening a page. In Exception Log:

`Exception in line 138 of /data/neos/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Neos_Neos_Ui_Domain_Model_Changes_AbstractCreate.php: Class' Neos \ Neos \ Ui \ NodeCreationHandler \ notationDreationProp`

**Comment by daniellienert** [comment]
@patriceckhart could you please provide the complete exception message (See Data/Logs/Exceptions)

**Comment by patriceckhart** [comment]
Exception in line 138 of /data/neos/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Neos_Neos_Ui_Domain_Model_Changes_AbstractCreate.php: Class 'Neos\Neos\Ui\NodeCreationHandler\CreationDialogPropertiesCreationHandler' not found

41 Neos\Neos\Ui\Domain\Model\Changes\AbstractCreate_Original::applyNodeCreationHandlers(Neos\ContentRepository\Domain\Model\Node)
40 Neos\Neos\Ui\Domain\Model\Changes\AbstractCreate_Original::createNode(Neos\ContentRepository\Domain\Model\Node)
39 Neos\Neos\Ui\Domain\Model\Changes\CreateAfter_Original::apply()
38 Neos\Neos\Ui\Domain\Model\ChangeCollection_Original::apply()
37 Neos\Neos\Ui\Controller\BackendServiceController_Original::changeAction(Neos\Neos\Ui\Domain\Model\ChangeCollection)
36 Neos\Neos\Ui\Controller\BackendServiceController::changeAction(Neos\Neos\Ui\Domain\Model\ChangeCollection)
35 call_user_func_array(array|2|, array|1|)
34 Neos\Neos\Ui\Controller\BackendServiceController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
33 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
32 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
31 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
30 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
29 Neos\Neos\Ui\Controller\BackendServiceController::changeAction(Neos\Neos\Ui\Domain\Model\ChangeCollection)
28 call_user_func_array(array|2|, array|1|)
27 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
26 Neos\Neos\Ui\Controller\BackendServiceController::callActionMethod()
25 call_user_func_array(array|2|, array|0|)
24 Neos\Neos\Ui\Controller\BackendServiceController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
23 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
22 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
21 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
20 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
19 Neos\Neos\Ui\Controller\BackendServiceController::callActionMethod()
18 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
17 Neos\Neos\Ui\Controller\BackendServiceController::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
16 call_user_func_array(array|2|, array|2|)
15 Neos\Neos\Ui\Controller\BackendServiceController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
14 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
13 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
12 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
11 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
10 Neos\Neos\Ui\Controller\BackendServiceController::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
9 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
8 Neos\Flow\Mvc\Dispatcher_Original::dispatch(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
7 call_user_func_array(array|2|, array|2|)
6 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call("dispatch", array|2|)
5 Neos\Flow\Mvc\DispatchComponent_Original::handle(Neos\Flow\Http\Component\ComponentContext)
4 Neos\Flow\Http\Component\ComponentChain_Original::handle(Neos\Flow\Http\Component\ComponentContext)
3 Neos\Flow\Http\Component\ComponentChain_Original::handle(Neos\Flow\Http\Component\ComponentContext)
2 Neos\Flow\Http\RequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()


HTTP REQUEST:
Neos_Session=eoXy3qESj8p6xlMOh3mwjO84puiAZC4Vde-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6,pt;q=0.5,da;q=0.4,fr;q=0.3,lb;q=0.2,pl;q=0.1,it;q=0.1gzip, deflate, brhttps://www.inoovum.io/inoovum/content?node=%2Fsites%2Fsite%2Fnode-zffdlhye5scv2%40user-editor%3Blanguage%3Ddeemptycorssame-originhttps://www.inoovum.io*/*Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.362a517348e0c5613a564739eb8828b7ffno-cacheno-cachehttpshttps443www.inoovum.io10.156.0.210.156.0.2ea5c6696647019bd8430804536028963www.inoovum.io1474application/json

HTTP RESPONSE:
200

PHP PROCESS:
Inode: 141218
PID: 3612
UID: 80
GID: 80
User: www-data

**Comment by uhley** [comment]
I have the same problem.

**Comment by sebastiansommer** [comment]
Same issue here

**Comment by albe** [comment]
D'oh - somehow the `CreationDialogPropertiesCreationHandler` got deleted in 5.1.5

https://github.com/neos/neos-ui/tree/5.1.5/Classes/NodeCreationHandler
https://github.com/neos/neos-ui/tree/5.1.4/Classes/NodeCreationHandler

and it's not even in the commit log: https://github.com/neos/neos-ui/commits/5.1.5/Classes/NodeCreationHandler

Which I can't even explain in any way 🤔🔍❓ /cc @markusguenther

**Comment by markusguenther** [comment]
I am look ing into that issue :(
After fixing that and releasing 5.1.6 we should also add a e2e test for the creation dialog.

Sorry for the inconvenience.

**Comment by markusguenther** [comment]
I am bit confused... githib comparision did not list the change but locally the ```git diff 5.1.4 5.1.5``` shows that. So again a upmerge was wrong.

Maybe we should check if the strategy option is the right one.
In the last release it also happened for @skurfuerst that the upmerge was wrong :(

But I don`t know why it looks correct in the github tag comparision :(

**Comment by markusguenther** [comment]
OK found the issue and it was just a human failure. The branch 5.1 is ok but I did enter the wrong branch in the jenkins job. So 5.1.5 is based on 5.0 branch. Started the 5.1.6 release. Again sorry for the inconvenience 🙏

**Comment by markusguenther** [comment]
This is fixed with the release of 5.1.6.
https://github.com/neos/neos-ui/releases/tag/5.1.6
