### ISSUE TITLE
Drag & Drop between trees not validated

### ISSUE THREAD

**Issue by rolandschuetz** [neos/neos-ui#2741]
### Description

It's possible to drag content nodes from the content tree onto document nodes from the document tree. The UI doesn't do anything but also gives no success nor error feedback.

### Steps to Reproduce

1. Drag a content element from the content tree onto the document tree
2. Drop it anywhere.

#### Expected behavior

Feedback that the position is invalid during drag.

#### Actual behavior

Blue valid drop locations

### Affected Versions

UI: 5.2.1

**Comment by grebaldi** [comment]
Should have been closed by #2905 - not sure, why it wasn't :/
