### ISSUE TITLE
Wrong dependencies to build-essentials and positional-array-sorter

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-ui#2742]
### Description

Trying to build JS code for the UI inspector and I am getting options has an unknown property `localIdentName` when building. 

#### Actual behavior

Turns out that is coming from `@neos-project/build-essentials` in version 5.1.1 that I have installed. Even though… I have `@neos-project/neos-ui-extensibility` as version 5.2.1 installed.

Why does `@neos-project/neos-ui-extensibility` 5.2.1 depend on version 5.1.1 of both `@neos-project/build-essentials` and `@neos-project/positional-array-sorter`?

### Affected Versions

Neos: 5.2.1
UI: 5.2.1

**Comment by Sebobo** [comment]
Seems the build scripts mixed this up.

**Comment by kdambekalns** [comment]
My problem right now: If I require the correct version in my package, I simply get both versions, and the build still fails. Any way to work around that in userland code?

**Comment by kdambekalns** [comment]
> Seems the build scripts mixed this up

Probably that, these lines have only been touched by Jenkins in the (recent) past.

**Comment by Sebobo** [comment]
I started updating a plugin to 5.2 yesterday but haven't finished yet. I will probably run into the same problem and will look for a quick fix.
