### ISSUE TITLE
when changing node type, re-rendering in UI might fail

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#2767]
### Steps to Reproduce

1. Use the demo site
2. use the two column on the homepage
3. change the node type to a four-column
  -  EXPECTED: the backend is re-rendered with a 4 column
  - ACTUAL: the backend is re-showing the two-column.
4. reload the backend
  - now, the BE shows the 4-column.
5. change back to two-column
  - EXPECTED: the backend is re-rendered with a 2 column
  - ACTUAL: the backend is re-rendered with a 4-column; with the two right columns being an error.
6. reload the backend
  - the error disappears

### Problem description

- in the `nodeDomAddress` for the change, the node type is encoded in the fusion path.
- when we **change** the node type, this is wrong....

### Solution Idea

- we want to send TWO nodeDomAddresses: one for the node itself, and one for the closest rendered parent.
- then the server can decide which one to use for the refresh; and in case the node type changes, use the outer one.

### Affected Versions

probably all versions

**Comment by skurfuerst** [comment]
reminder to self: once fixed (e.g. in Property.php in Neos UI), we also need to adjust the Event Sourced CR Property implementation

**Comment by Sebobo** [comment]
Yes that's something a bit similar to what I wanted to fix in general. There are often NodeTypes in which the collection children need to know about each other. Like for setting the correct css class. 
In this case the integrators always set something like "reloadPageIfChanged". But instead reloading the closest parent content element would be the desired option.

**Comment by grebaldi** [comment]
This should have been closed by  #2892, but wasn't because I misspelled the magic word :facepalm:
