### ISSUE TITLE
Tree shows last node in list multiple times when deleting nodes

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#2768]
### Description

Deleting nodes in the nodetree (visually) duplicates the last node in the tree. Interacting with the duplicate node makes actions visible in both nodes (for example opening its content).

The problem disappears upon reloading.

The problem does *not* occur when deleting the last node in the list.

![duplicate nodes](https://user-images.githubusercontent.com/9661367/90870857-7ecc2c00-e39a-11ea-8ee8-cfe1edec82df.gif)

(Note: In the last step where I delete a fourth node, I clicked on one of the upper two and the lower three got selected - not the one I clicked)

### Steps to Reproduce

1. Open any document with multiple child nodes
2. Delete one of them (any but the last in the list)
3. The tree shows them as duplicates and behaves weird when clicking on them

### Affected Versions

Until now reproduced in (no confirmation if it was first introduced with 5.2.3 yet):

Neos: 5.2.3; 5.3.0
UI: 5.2.3; 5.3.0

**Comment by paavo** [comment]
I have the same problem in a [Content Collection](https://mind-the-seb.de/blog/preventing-deep-content-nesting-in-neos-cms). 

Removing a node in the inline (content area) works well. 
Removing a node in the content tree, re-adds the "broken-node" as last element. 
Selecting the last "undeleted" node in the content tree, marks all deleted nodes too. 

![Screenshot](https://i.imgur.com/GsrN6MZ.gif)

**Affected Versions**
Neos: 5.2.3
UI: 5.2.3

**Comment by paavo** [comment]
I just tried with Neos 5.3 and the problem persists:

**Affected Versions**
Neos: 5.3.0
UI: 5.3.0

**Comment by klfman** [comment]
Can confirm: Stil exists in Neos 5.3, will update the description above

**Comment by Sebobo** [comment]
Do you know if 5.2.3 introduces the issue or if it's older?

**Comment by paavo** [comment]
Just checked with **5.2.2** @Sebobo and the Issue **already existed there**. 

**Affected Versions**
Neos: 5.2.2
UI: 5.2.2

**Comment by klfman** [comment]
I do not know either when it was introduced. I first saw it after upgrading from Neos 4.3 to 5.2. But that's a huge range, so frankly no idea :D

**Comment by skurfuerst** [comment]
(reminder to self: timebox max 4h for customer)

**Comment by skurfuerst** [comment]
is related to https://github.com/neos/neos-ui/pull/2743

**Comment by skurfuerst** [comment]
see fix: https://github.com/neos/neos-ui/pull/2774
