### ISSUE TITLE
Moving nodes keeps visual copy of node in old position until reload

### ISSUE THREAD

**Issue by patricekaufmann** [neos/neos-ui#2773]
### Description

When moving nodes via node tree, a copy remains on the page until reloading.

#### Steps to Reproduce

1. Move node in the node tree

#### Expected behavior

Old node should be removed from page

#### Actual behavior

![neos_ui_drag_bug](https://user-images.githubusercontent.com/41791606/92715190-6b8afb80-f35d-11ea-945d-95001d6262f9.gif)

### Affected Versions
Neos: 5.3
UI: 5.3
Content Cache enabled: Either

**Comment by patricekaufmann** [comment]
It seems very hard to miss this when testing so I would assume it has to do with something else going on in the background. I confirmed it not working on 2 Neos installations.

**Comment by Sebobo** [comment]
Maybe also related to an upmerge. We will check.
