### ISSUE TITLE
Improve performance of /neos/ui-services/get-additional-node-metadata endpoint

### ISSUE THREAD

**Issue by gjwnc** [neos/neos-ui#2784]
### Description

The endpoint `/neos/ui-services/get-additional-node-metadata` is called by the backend multiple times and can take many seconds to finish. In our case we have around 600 NodeTypes and this request can take 1-2 minutes.

The input for the call is a set of nodes which are processed here https://github.com/neos/neos-ui/blob/master/Classes/Controller/BackendServiceController.php#L465.

The runtime of this method depends on
* the number of nodes given as the input
* the number of NodeTypes configured
* the time needed for policy checks

Most of the time is consumed by https://github.com/neos/neos-ui/blob/master/Classes/Service/NodePolicyService.php#L109.

I'll provide a PR to reduce the number of NodeTypes processed during the policy checking.

### Steps to Reproduce

Have a look at the debug console in the neos backend of your browser. In bigger projects this request often takes a few seconds.

### Affected Versions

Neos: 4.x and up

UI: 4.x and up

**Comment by markusguenther** [comment]
Hello @gjwnc 

you are right that the endpoint can take some time depending on the amount of nodetypes.
I would like to speed that up but I am not sure if that is trivial and the policy handling is needed for the ui.

Maybe we can discuss that again in the team. If I am right we already talked in the past about that.
Thanks for bringen that up and impressive that you have 600 nodetypes.
