### ISSUE TITLE
Exception when clicking the preview button without a preset

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2807]
### Description

When you click the preview button and have no node type filter enabled the rendered page will show an exception that the presetBaseNodeType is missing.

### Steps to Reproduce

1. Go to content Module in the backend
2. Select a page in the PageTree (without a filter!)
3. Click the preview Button

#### Expected behavior

The page will be rendered.

#### Actual behavior

Exception

![Screenshot 2020-10-21 at 09 07 35](https://user-images.githubusercontent.com/1014126/96685383-50100900-137d-11eb-88ce-aed58b6c156b.png)

### Affected Versions

Neos: 5.1

UI:5.1.11

**Comment by DrillSergeant** [comment]
Should this be gone with UI 5.3.3? I still have it using v5.3.3.

**Comment by markusguenther** [comment]
It is gone with 5.3.4 just released ;)
