### ISSUE TITLE
JS error and UI unusable when publishing changes

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2819]
### Description

Editor experiences weird behavior in the backend after publishing changes.
The backend become unresponsive to some click, and he has to reload the interface in order to continue editing.

I found that the bug is caused by a JS error `Empty or non existent "message" passed to the addFlashMessage reducer. Please specify a string containing your desired message.` thrown by `Neos.Neos.Ui/packages/neos-ui-redux-store/src/UI/FlashMessages/index.ts:77`.
The code is trying to display a flash message, but the message is `null`.
I check what flash message should be displayed when publishing, and found the label `changesApplied` of `Neos.Neos.Ui:Main.xlf`.
This label exists only in EN and DE, and the editor set his language to FR.
Setting the editor's language to EN makes the error disappear and the flashMessage is displayed.

So either the translation fallback is not working, either the UI is too strict when displaying an untranslated flash message.

### Steps to Reproduce

1. Set the user's language preference to something different that EN or DE
2. Open the browser JS console
3. Edit a node property and publish it
4. A JS error is thrown and is visible in the browser console

#### Expected behavior

I should see the flash message saying "The change has bee published" in the user language (or in the fallback language)

#### Actual behavior

I see no flash message and there is a JS error.

### Affected Versions

Neos:  5.3.0

Flow: 6.3.1

**Comment by markusguenther** [comment]
This issue was reported by @dogawaf
Thanks for that ❤️ 

https://github.com/neos/neos-development-collection/issues/3154

**Comment by markusguenther** [comment]
<img width="569" alt="Screenshot 2020-11-20 at 10 26 29" src="https://user-images.githubusercontent.com/1014126/99783622-ec633200-2b1a-11eb-8c75-c29840ce1c46.png">

I have synced the language labels and with the next release it should not happen anymore ;)

**Comment by markusguenther** [comment]
@dogawaf Maybe you can review the french changes in the xliff file. As you are native speaker :)
I just used a translation tool ;)

**Comment by dogawaf** [comment]
Hi @markusguenther  thanks for taking care of this issue.
Can I add a commit for the fix of the french language translations directly to your PR?

**Comment by markusguenther** [comment]
Hmm sadly not because only team members can change PRs.
But you can fork my branch and submit a new PR. Would close my PR then.

Thanks in advance 👍

**Comment by dogawaf** [comment]
Hi made a new PR: https://github.com/neos/neos-ui/pull/2851
I hope I did it right.

**Comment by markusguenther** [comment]
Thanks again @dogawaf ... great to see that neos is also used in france :)
