### ISSUE TITLE
Make the baseNodeType optional in updateNodeInfo

### ISSUE THREAD

**Issue by samsauter** [neos/neos-ui#2875]
### Description

Without submitting a baseNodeType, no new node can be created in the NEOS pageTree.

#### Possible fix

I manually patched the file `Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php` according to this already applied fix in https://github.com/neos/neos-ui/pull/2814. But as far as I can see this is only fixed in newer versions of the UI, not the 4.x branch. Can you fix it in this older one as well?

### Affected Versions

Neos: 4.3.17

UI: 4.0.12

**Comment by Sebobo** [comment]
Sorry, the 4.x branch doesn't get bugfixes anymore.

**Comment by samsauter** [comment]
Alright, I'll just keep the patch then, it's fine for an older project. Thanks for replying!
