### ISSUE TITLE
removeFormat does not work

### ISSUE THREAD

**Issue by MarcoPNS** [neos/neos-ui#2878]
In the Neos Docs it says that you can use the formatting option "removeFormat: true" for the CKEditor. Apparently, however, it was never actually added.

I have tested it with Neos 7, but it is probably a general problem since the CKEditor 5 is used. The required package @ckeditor/ckeditor5-remove-format is not in the dependencies.

ref: https://ckeditor.com/docs/ckeditor5/latest/features/remove-format.html

**Comment by MarcoPNS** [comment]
a older issue also had `wait for removeformat to be implemented` as todo: #2002

**Comment by markusguenther** [comment]
Has been released with version 5.3.6
