### ISSUE TITLE
Allow custom previews in selectboxes

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-ui#2914]
### Description

Currently it's only possible to use FontAwesome Icons supplied with Neos as "icons" for the `SelectBoxEditor`.

It's often requested to also allow custom previews for each item like the `AssetEditor` or `NodeEditor` allow.

I implemented this already for a customer with a custom `SelectBoxEditor` that uses the `SelectBox_Option_MultiLineWithThumbnail` component for rendering and setting the `preview` option on the datasource instead of the `icon`.

Therefore I would integrate a new option that allows to switch to the other option component. This should be a rather small code change.

**Comment by Sebobo** [comment]
Put the plugin into a package for older Neos versions https://github.com/Sebobo/Shel.Neos.PreviewSelectBox.

**Comment by jonnitto** [comment]
This is freaking awesome! :heart:
