### ISSUE TITLE
Auto-Publish checkbox is just not properly aligned

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#2993]
### Description

The Auto-Publish checkbox  and label is just not properly aligned actually.

### Steps to Reproduce

1. Login to the backend 
2. Open the publish drop-down

#### Expected behavior

Checkbox and label are in the same line and the checkbox looks nice with aligned check mark

#### Actual behavior

Label is not in the same line and the check mark is not centered.
<img width="336" alt="Screenshot 2021-12-11 at 14 00 49" src="https://user-images.githubusercontent.com/1014126/145677537-b12eab9e-dc91-4f88-8616-4d0adf73df90.png">

### Affected Versions

Neos: 5.3

UI: 5.3.x

**Comment by markusguenther** [comment]
This issue is somehow related to #2978 as we maybe don't need to align the check mark anymore.

**Comment by mhsdesign** [comment]
oops mine was a dub https://github.com/neos/neos-ui/issues/3140
