### ISSUE TITLE
Bugfix: Passing wrong value to CountValidator makes everything go white 

### ISSUE THREAD

**Issue by pKallert** [neos/neos-ui#2999]
### Description
Passing null to the CountValidator makes the page go white

### Steps to Reproduce

1. Add a new property to a yaml file of type integer 
2. Add the 'Neos.Neos/Validation/CountValidator' as validation
3. Set minimum and maximum 

`
Testing:
      type: integer
      ui:
        label: 'blub'
        reloadPageIfChanged: true
        inspector:
          group: 'document'
      validation:
        'Neos.Neos/Validation/CountValidator':
          minimum: 1
          maximum: 255
`

#### Expected behavior
An Error message should be shown that the count validator does not work here. 

#### Actual behavior
The whole Backend is white and there is an JS error Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Count (index.tsx:32) [...]

### Affected Versions

Neos: 7.3

UI: 7.3

**Comment by markusguenther** [comment]
Thanks, @pKallert and great catch. I bet that this change is also needed for neos 5.3.
So need to check if that also occurs in the lowest maintained branch ;)

**Comment by markusguenther** [comment]
Neos 5.3 was also affected. So I rebased the PR to Neos 5.3.
