### ISSUE TITLE
Optimize width of DimensionSelector

### ISSUE THREAD

**Issue by cvette** [neos/neos-ui#3013]
### Description

Right now there is no min-width for the dimension selector. If you have a short dimension label selected and open the drop-down, some of the longer labels are restricted way too much.

### Steps to Reproduce

1. Configure some dimension presets with both long and short labels
2. Select a preset in the Neos UI with a short label
3. Open Dropdown

#### Expected behavior

There should be a min width and probable a bit higher max width.

#### Actual behavior
![2022-01-19_11-37](https://user-images.githubusercontent.com/6884391/150114952-858e658b-2e65-43d0-9132-679152f9441c.png)

### Affected Versions

Neos: all versions with the new UI ?

UI: all versions of the new UI ?

**Comment by NicoleNitschke** [comment]
I'll take this issue today. :)

**Comment by skurfuerst** [comment]
merged :)
