### ISSUE TITLE
Display bugs for SelectBoxEditor with data source and single selection

### ISSUE THREAD

**Issue by patricekaufmann** [neos/neos-ui#3136]
The following bugs originate from https://github.com/neos/neos-ui/pull/2930 when using a SelectBoxEditor with a data source and single select:

- wrong line heights for single select SelectBox with data source:
![image](https://user-images.githubusercontent.com/41791606/178183177-c192797c-f105-406e-8f5e-4c3efb7422d9.png)

- no hover styles for select options, reducing the overall user experience in backend:

https://user-images.githubusercontent.com/41791606/178183263-94db728a-cd61-477d-9512-d38ec77ae998.mp4

The project still runs on Neos 7.3.0.

**Comment by Sebobo** [comment]
This should be fixed by https://github.com/neos/neos-ui/pull/3125
Can you confirm?

**Comment by patricekaufmann** [comment]
> This should be fixed by #3125 Can you confirm?

Ah, you are already on it. Nice! I didn't see that earlier, sorry. I gave feedback on the MR discussion.

**Comment by Sebobo** [comment]
Resolved in #3125
