### ISSUE TITLE
BUG: auto-publishing hitbox is to small

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3140]
### Description

If you click here to enable it:
![image](https://user-images.githubusercontent.com/85400359/179528690-d3ba8153-9ef8-4b6b-91f0-14a5cc46317c.png)

the dialog will close, but the checkbox auto-publishing will not be enabled.

you need to actually click directly on the checkbox:

![image](https://user-images.githubusercontent.com/85400359/179528909-35697541-47b3-45ed-8055-55cc2bd4eca5.png)

### Affected Versions
UI version: v7.0.3

**Comment by NicoleNitschke** [comment]
I'll take this issue today. :)
