### ISSUE TITLE
Keep state of which document nodes were expanded between views

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-ui#3148]
Jira issue originally created by user @aertmann:

STUB: The tree should remember which branches were opened/closed during the last time

This should be possible with dynatree's cookie functionality

 Jira-URL: https://jira.neos.io/browse/NEOS-780

**Comment by mhsdesign** [comment]
now a duplicate of https://github.com/neos/neos-ui/issues/1159 ;)
