### ISSUE TITLE
Collapsible Document tree to make room for the Content tree

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-ui#3149]
Jira issue originally created by user @aertmann:

STUB: The Document tree should be collapsible in order to make more room for the Content tree in cases of pages with lots of content

 Jira-URL: https://jira.neos.io/browse/NEOS-781

**Comment by mhsdesign** [comment]
@Sebobo on slack

> [...] the structure is a bit strange. The two trees are not proper siblings in the sidebar. When this is cleaned up it should also be easy to adjust their relative heights
