### ISSUE TITLE
Inline editable field is not directly focused after node creation

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#3155]
### Description

If I create an inline-editable text or headline element via the backend it is not possible to change the text  as soon as the element is created. In Chrome it is working fine but in Firefox I have to click inside the text region again.

Weird: For a headline element it is enough to just click inside the text region but for text I need to click outside the element and then into the text region to edit the text.

This is not only an issue with my specific site package, I also tried the Neos demo page.
### Steps to Reproduce
1. Set up Neos demo page
2. Open the backend and create a Headline or text element
3. Try to input text without clicking anywhere
#### Expected behavior

I expect that it would be possible to input text right after the creation of the element in Firefox.
#### Actual behavior

The element gets created but nothing happens when text is written in Firefox, in Chrome it is working fine.
### Affected Versions

Tested with
Neos: 2.3.7

Flow: 3.3.4

**Comment by mhsdesign** [comment]
so i tried these steps:

- create an inline editable node
- dont click anywhere
- start typing and expect the inline editor to fill?

this is not the behavior in Chrome or Firefox and i dont think it should be right? @markusguenther tagging you here ^^

maybe over the time - and the ui rewrite - this behavior changed but i think currently it is fine as is. So we can close this i think?

**Comment by grebaldi** [comment]
Yep :)
