### ISSUE TITLE
Escape "Unapplied changes" when using "Selected element" to navigate to other Node

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3174]
### Description
Funnely it works astonishing well and is not buggy at all ^^ - i just found an escape hatch.

### Steps to Reproduce

1. Make changes on a Content Element (in the Inspector)
2. use the Selected element selectbox to move upward (Content Collection / Page)

#### Expected behavior

Idk - but for some reason its not allowed to change the node by using the Content Tree with unapplied changes - so i assumed the same for the "Selected element"  select box.

#### Actual behavior

You moved to the other node ^^ 
now you are free ;)  - unless you go back to the edited node.

### Affected Versions

UI version: v8.0.1

**Comment by grebaldi** [comment]
Fixed through https://github.com/neos/neos-ui/pull/3491
