### ISSUE TITLE
DocumentTree is not reloaded when discarding node move changes

### ISSUE THREAD

**Issue by klfman** [neos/neos-ui#3184]
### Description

After moving some documents in the document tree to a different parent, the document tree is not updated visually after a discard all.
Note: It works after a page reload, so the bug is only a neos-ui refresh problem, internally the move seems to have been reverted correctly.

This does **not** occur when moving a document within its parent.

https://user-images.githubusercontent.com/9661367/162416183-642d8a74-8038-4881-890a-61d79d6c5b02.mp4

### Steps to Reproduce

1. Create a nested document structure
2. Move some documents from one to another parent
3. Click "discard all"
4. The document tree does not update to reflect the state before the changes (e.g. what the discard all reverts to)

### Affected Versions

I saw this bug from Neos 7.1 through 7.3
Latest reproduced version is Neos 7.3.3, Flow 7.3.3 (the version running in the video above)

**Comment by mhsdesign** [comment]
Before merging Wilhelms bugfix into 8.3, we should check what the behaviour is on 9.0 to avoid a regression after having it fixed.
