### ISSUE TITLE
Bug: `Selected element` select a parent node, which is a shortcut.

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3219]
### Description

The inspector shows an infinite loading icon when a parent node was selected via `Selected element` which is a shortcut.

### Steps to Reproduce

This bug is not reproducible, when the shortcut was already loaded by the ui.

1. Have shortcut with a nested page (and publish them?)
2. Go to a page that is not the shortcut or a descendant of the shortcut
3. Reload the ui to make sure all JavaScript caches about nodes are flushed
4. expect the previous selected node to be still active
5. go to the subpage of the shortcut (without clicking the shortcut itself (gehe nicht über los ziehe keine 200 € ein usw.) )
6. use the `Selected element` dropdown to select the parent / eg the shortcut

[Bildschirmaufzeichnung vom 10.10.2022, 14:17:43.webm](https://user-images.githubusercontent.com/85400359/194864653-6d121aea-4cc3-4d4c-9ce9-14ce6a476a14.webm)

#### Expected behavior

The inspector should work as usually

#### Actual behavior

Infinitive loading to death

### What happened

the `<Inspector />` uses the `renderFallback` with spinner because `node.isFullyLoaded` is falsy or `state.viewConfiguration.tabs` is falsy 

https://github.com/neos/neos-ui/blob/7665b057e7f72fbd56026c106d3bab8528403469/packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js#L344-L350

### Affected Versions

UI:  v8.0.1

**Comment by grebaldi** [comment]
I was able to reproduce this on 7.3 as well.

**Edit:** I also found that this is not limited to shortcuts but happens generally.

**Comment by mhsdesign** [comment]
Thanks @grebaldi  that you basically fixed all ui bugs i found :heart:
