### ISSUE TITLE
Bug: Usermenu and Dimensionmenu open at the same time 

### ISSUE THREAD

**Issue by pKallert** [neos/neos-ui#3222]
### Description
When the dimensions Menu is open, clicking on the usermenu down-button leads to a state where both usermenu and dimensions menu are open. 

### Steps to Reproduce

1. Open dimensions Menu / language menu
2. Open user menu by clicking on the "down" button, not on the username 

Other way around: 
1.  Click on the "down" button on the user menu to open the usermenu
2. Click on the "down" button to open the language menu

#### Expected behavior
I would expect the language menu to be closed and the user menu to be open

#### Actual behavior
The language menu is open and the usermenu is open and overlaying the language menu.
 
![dropdown_error](https://user-images.githubusercontent.com/91674611/195060629-1de87906-0155-441c-888f-9d23e780b90c.gif)

**Comment by mhsdesign** [comment]
i noticed that too ^^
