### ISSUE TITLE
BUG: Opening Image Cropper causes immediate change

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#3242]
https://user-images.githubusercontent.com/2522299/199695632-b74ce466-2988-463c-9fef-7d50994c2bb6.mp4

### Description

When opening the Image Cropper, the Inspector immediately recognizes a change (given a crop is already applied) even though the editor didn't do anything.

### Steps to Reproduce

1. Click on an image that has a crop applied
2. Open the Image Cropper via the Inspector
3. See the "Apply" and "Discard" buttons at the bottom of the Inspector light up

#### Expected behavior

Opening the Image Cropper without applying a new crop does not cause a change.

### Affected Versions

Neos: 7.3 and above

UI: 7.3 and above

**Comment by grebaldi** [comment]
This bug was introduced here: https://github.com/neos/neos-ui/commit/d90ebf8463f1b97295197756057d292fc72507ed

I'll have a look, if there's a way to recognize whether the default crop has been applied yet.

**Comment by crydotsnake** [comment]
Solved with: #3243
