### ISSUE TITLE
Task: All 8.2 neos npm packages need to be delayed released and checked if they still work after esbuild change

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3262]
By changing the build system from webpack to esbuild in https://github.com/neos/neos-ui/pull/3200 and partly banning babel - a lot of internals change.

This issue holds left todos from #3200

Following sub packages of this monorepo are affected:
- https://www.npmjs.com/package/@neos-project/react-ui-components
- https://www.npmjs.com/package/@neos-project/neos-ui-extensibility
- https://www.npmjs.com/package/@neos-project/debug-reason-for-rendering
- https://www.npmjs.com/package/@neos-project/build-essentials
- https://www.npmjs.com/package/@neos-project/positional-array-sorter

Todos
- [x] re add `main` fields and build subpackages command for npm subsplits
- [x] check if neos-ui-extensiblity still works (bable stuff) did we update babel?
- [x] fix scss files in lib esm build of react-ui-components

**Comment by mhsdesign** [comment]
Following things where changed:

packages/neos-ui-extensibility/package.json
- "main": "./dist/index.js", -> "module": "./src/index.ts",

packages/positional-array-sorter/package.json
- "main": "./dist/positionalArraySorter.js", -> "module": "./src/positionalArraySorter.js",


also in packages/react-ui-components/package.json we must make sure via esbuid to always use the "main" field instead of "module"

**Comment by markusguenther** [comment]
We in the Jenkins release task we now change the module folder from src to dist and then we are using the babel transpiled code. So we can close this ...
