### ISSUE TITLE
Which esbuild target to set?

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3267]
Previously we had polyfills, autoprefixer and all the things. once even ie support.

Do we want to use simply "esnext" as target https://esbuild.github.io/api/#target?

Esbuild doesnt care about our browserlist ... but we can convert `> 1% and last 2 versions and not dead"` online https://browserslist.dev/ to
`'chrome106', 'firefox105', 'edge106'` -> which seems like esnext to me ;)

**Comment by Sebobo** [comment]
With esnext one has to be a bit careful as stuff can suddenly change according to some docs and it might be differently handled by various build tools.

So I would prefer something like `es2020`. And if you say browsers list is not used, why not just remove it then?

**Comment by mhsdesign** [comment]
> And if you say browsers list is not used, why not just remove it then?

i removed the config already with https://github.com/neos/neos-ui/pull/3266

but the whole dependency mess is still required for the webpack extensibility

**Comment by mhsdesign** [comment]
ES2020 sounds cool we would have esmodules and dynamic imports
