### ISSUE TITLE
Don't require NPM_TOKEN locally

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#3283]
### Description

For publishing the packages to `npm` we are using now `yarn npm publish` therefore yarn needs configuration for NPM authentication. As we use 2FA, we use a token in the CI/Jenkins to be able to act. Sadly, the configuration is also used in the local environment when we execute yarn install.

#### Expected behavior

Locally, we don't need to define NPM_TOKEN.

#### Actual behavior
<img width="1152" alt="Screenshot 2022-11-30 at 20 57 30" src="https://user-images.githubusercontent.com/1014126/204895958-d3a28319-df17-4ba1-bfcb-14513de6aaa7.png">

### Affected Versions

Neos: 8.2.0

UI: 8.2.0

### Workaround
If you need to build the neos-ui, you have to comment out the line `npmAuthToken: "${NPM_TOKEN}"` in the `.yarnrc.yaml`

**Comment by Sebobo** [comment]
Marc proposed the setting `npmAlwaysAuth: false`

**Comment by markusguenther** [comment]
Hmm did that work for you? tried it and had the same effect.
