### ISSUE TITLE
BUG: E2E fail to run locally via `make test-e2e-docker`

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#3301]
Running `make test-e2e-docker` on a fresh checkout of Neos.Neos.Ui 8.3 leads to the following error message on my machine:

```
An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution

  Type: Doctrine\DBAL\Exception\ConnectionException
  File: Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriv
        er.php
  Line: 112
```

Docker version: 20.10.12, build 20.10.12-0ubuntu4
Docker-compose version: 1.29.2

That's all I can tell so far. I'll investigate further...

**UPDATE:**
The issue was introduced here: https://github.com/neos/neos-ui/pull/3253

The db container is now ARM-based. It won't run on amd64 machines.

I'll see, if there's a possible workaround.

**Comment by markusguenther** [comment]
Hmm, is it possible to have kind of universal images? I just tested that with an ARM-based Mac and Sebastian used it but has a similar computer :/

Sorry for that.

**Comment by grebaldi** [comment]
> Sorry for that.

No worries :)

This has made me think about how to make the E2E-setup more accessible in general (for local development). I think it would be nice, if adding E2E test cases and running the tests was a bit easier than it is right now. I find the prospect of the E2E tests turning red in CircleCI always a bit scary, because debugging with the E2E setup adds a lot of headache.

I was wondering, if a DDEV-supported setup is possible, because this is what I usually use for local development. It takes away most of the headache that comes with a custom docker-compose setup. And most importantly for this issue: It comes with support for ARM64: https://github.com/drud/ddev/issues/1966

There is also precedent for running DDEV on a CI Server: https://dev.to/tomasnorre/codeception-tests-in-travis-ci-with-ddev-and-selenium-1607

So this may be worth a try :)

**Comment by markusguenther** [comment]
Some years ago, I tried to create a test distribution for the UI. Because I thought the "look into the circle ci yaml" to understand how it works was too complicated.

But today I am unsure if this improved it ;)

https://github.com/neos/neos-ui-testing-distribution

**Comment by mhsdesign** [comment]
we should use the db image `mysql:8` instead of specifying only the arm version (`arm64v8/mysql:8`)... we had the same issue with #3369 @JamesAlias
