### ISSUE TITLE
UX: Improve node creation dialog

### ISSUE THREAD

**Issue by manuelmeister** [neos/neos-ui#3303]
### Problem
I am a Neos newcomer and would love to have more context if I add a new node.
Often after clicking the plus icon button (either in the content tree or directly in the layout), I often wonder If I've actually selected the correct node. The current selected node could be visible (but only if the content tree is open) in the background, but it is not so easy to read, with the backdrop.

If I've selected the wrong node (the one above or the one higher/lower in the hierarchy) I can still "salvage the situation" (this means that I don't have to press "cancel", because in my mind, I'm already looking for the node I wanted to create) with the `insert mode` control. Sadly for me the icons were not self-explanatory what these buttons actually do.

### Suggestion
Make the dialog title dynamic based on the insert position (Default is inside) and the current node label. This means that the title would be called `Add inside Section`. Below the title we change the label to `Insert position` and separate the `insert before / after` from `insert inside` as this often leads to different nodes being displayed. We change the icons of the button to reflect the direction and meaning of the action. `before` and `after` add something to the parent of this item, so the arrow is pointing to the left. `inside` is one level deeper as the current level, therefore we point the arrow to the right.

| before | after |
|-|-|
| ![Dialog is called "Create new" and button order is above, inside, below. Icons are not self explanatory](https://user-images.githubusercontent.com/3001985/208709685-3b64314c-4e32-470a-b2d9-8c0279b7b57e.png)| ![Dialog is called "Add inside" and the label name of the NodeType. The button order is above, below grouped together and inside separate.](https://user-images.githubusercontent.com/3001985/208709684-7080704b-c4fb-4ba9-af9a-8f5ac79bed73.png)|
| ![Dialog is called "Create new" and button order is above, inside, below. Icons are not self explanatory](https://user-images.githubusercontent.com/3001985/208709689-c7200808-ed12-4c92-8030-d13af7547328.png)|![Dialog is called "Add above"  and the label name of the NodeType. The button order is above, below grouped together and inside separate.](https://user-images.githubusercontent.com/3001985/208709688-3a09d74c-ca1a-4b0b-bc97-c05bb7f5cd7b.png) |

> **Note**
> (Not completely unrelated sidenote)
> I think, in the preview we could also introduce a separate button for inserting inside the current position.
>
> This comes naturally, as the plus already signifies that we add something at the position (I just realized this is not the case, it adds it below and not above. I think above should be the default if clicked in the preview, as the button lays between the current and the previous field. We could still add a separate below the node to add something below this node). 
>
> ![Bildschirmfoto 2022-12-20 um 17 15 02](https://user-images.githubusercontent.com/3001985/208713945-a005cbcb-d6be-4c3a-8264-30c3197fc5ab.png)

**Comment by kdambekalns** [comment]
I like the idea of having the "context" in the title of the dialog. ❤️

TBH I would not have been able to tell the up/down arrows have a "tail". That being siad, for me "before" and "after" don't have any closer relation to the parent than to the current node – so I'm fine with either variant. 🤷‍♂️

_But_ for the "inside" position, I'd still put it in between the other two, as it just seems logical to me: before / inside / after is the "correct order" somehow. 🤔

**Comment by mhsdesign** [comment]
Thank you so much for this! :heart: It has been on my list for a while to discuss this topic but i didnt found the time or had the the proper solution. I agree 100% that its currently not super easy to use and you either need to properly read the title attributes or play around a few times with these 3 buttons.

In the past I mixed up the last two buttons a few times because:

- there is no readable indicator (without hover) whats about to happen
- it seemed in my brain for some reason to be more logical that the "into" button should be last position
- and the insert after icon gave me the impression that it could also be a insert into somehow because of its tail

so you nailed it!!!

(i think we should delay the discussion about the inline toolbar (i think its quite fine ..., or have it someplace else - but also thanks for rethinking that ;))

If you need help implementing this we can team up ;) 🦸

**Comment by manuelmeister** [comment]
@kdambekalns I think I agree with your order "before / inside / after", but only if they are displayed like this:
<img width="452" alt="Bildschirmfoto 2022-12-20 um 22 30 03" src="https://user-images.githubusercontent.com/3001985/208770625-3ef21b24-d840-42c7-acd4-c63ef8a520e6.png">

Sadly this uses too much real estate. 

I would still vote for the new grouping, because with different levels and allowed child nodetypes there is mostly only a difference between next to this node (inside the parent collection) or inside this node. That's why I've grouped them like this. 

As a frontend dev and advanced editor, I always need to look for the right icon. Maybe this would help:
<img width="515" alt="Bildschirmfoto 2022-12-20 um 22 32 58" src="https://user-images.githubusercontent.com/3001985/208771019-facf0a04-cf38-4867-a235-cc2e6478230d.png">

@mhsdesign If others agree with my suggestion. I'd love to team up!

**Comment by sbruggmann** [comment]
I vote for your second succestion.
If "Inside" is visually* separated, it can be out of the "above, inside, below" flow.

And maybe the simpler arrow-up and arrow-down icons make it slightly cleaner.

*edited

**Comment by ahaeslich** [comment]
I personally like the "before / inside / after" order.

But I think the crucial part which would improve this button row is the _text_ that is visible next to the icons in the last screens as they are not easily self-explanatory.

**Comment by kdambekalns** [comment]
This:

> Maybe this would help:
> <img alt="Bildschirmfoto 2022-12-20 um 22 32 58" width="515" src="https://user-images.githubusercontent.com/3001985/208771019-facf0a04-cf38-4867-a235-cc2e6478230d.png">

# 💯

**Comment by mhsdesign** [comment]
Do we want to get his into 8.3? @markusguenther would love that ;)
