### ISSUE TITLE
BUG: (Extensibility) I18n cannot be imported

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#3307]
### Description

Over at Slack Denny Lubitz described an issue with importing `@neos-project/neos-ui-i18n` in a custom plugin:

Quote:
> ATM I'm struggeling with translation, as I can't import the neos-ui-i18n :man-shrugging:
> https://github.com/neos/neos-ui/blob/8.3/packages/neos-ui-validators/src/Alphanumeric/index.tsx#L2

A quick look at https://github.com/neos/neos-ui/blob/8.3/packages/neos-ui-extensibility/scripts/helpers/webpack.config.js#L70 reveals that `@neos-project/neos-ui-i18n` is at least exposed correctly.

We'll need a proper reproduction to investigate the issue. Perhaps this is just a TS issue?

#### Expected behavior

Custom plugin vendors should be able to import from `@neos-project/neos-ui-i18n`.

### Affected Versions

Neos: any

UI: any

**Comment by mhsdesign** [comment]
For me this is working fine … (8.2 and prev)


```jsx
import I18n from "@neos-project/neos-ui-i18n";

const Lol () => <I18n is="foo" />
```

edit: 

should work see:
https://github.com/neos/neos-ui/blob/6aa5c74e75e4813ffd798905811d099df30d5705/packages/neos-ui-extensibility/scripts/helpers/webpack.config.js#L91
and
https://github.com/neos/neos-ui/blob/8.3/packages/neos-ui-extensibility/src/shims/neosProjectPackages/neos-ui-i18n/index.js

**Comment by dlubitz** [comment]
I tried to import it in my custom validator (@neos-project/neos-ui-extensibility@7.1.1), but it throwed the error:
```
Cannot find module '@neos-project/neos-ui-i18n' or its corresponding type declarations.
```
See:
https://github.com/VIVOMEDIA/neos-ui-json-validator/blob/use-i18n/Resources/Private/Validators/JsonValidator/src/JsonValidator/index.tsx

**Comment by mhsdesign** [comment]
but its a ts error no?
so it doesn't keep you from actually working ^^

you may want to add a `// @ts-ignore` before the line
or add a `d.ts` file where you manually add a type declaration for the i18n:


_neos.d.ts_
```ts
declare module "@neos-project/neos-ui-i18n" {
    import React from "react";

    interface I18nProps {
        /**
         * Fallback key which gets rendered once the i18n service doesn't return a translation.
         */
        fallback?: string;

        /**
         * The target id which the i18n service accepts.
         */
        id?: string;

        /**
         * The destination paths for the package of the translation.
         */
        packageKey?: string;

        /**
         * The destination paths for the source of the translation.
         */
        sourceName?: string;

        /**
         * Additional parameters which are passed to the i18n service.
         */
        params?: object;

        /**
         * className which gets added to the translation span.
         */
        className?: string;
    }

    export default class I18n extends React.PureComponent<I18nProps> {}
}
```

**Comment by mhsdesign** [comment]
Currently we offer no direct typescript support for plugins, so you need to come up with your own declarations (copy them from the Neos core)

**Comment by dlubitz** [comment]
I see! Thank you @mhsdesign 
I was using the neos validators as blueprint, which were in TS 🤷‍♂️ 
E.g: https://github.com/neos/neos-ui/blob/8.3/packages/neos-ui-validators/src/DateTime/index.tsx
