### ISSUE TITLE
BUG: Publish Dropdown has a large distance to the right

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-ui#3330]
### Description

The publish dropdown has a padding to the right, which makes it doesn't really look nice because the chevron icon no longer looks centered.

### Neos 8.2
![SCR-20230114-sbx](https://user-images.githubusercontent.com/39345336/212492707-2c2553c1-d06b-41e3-b33b-bea7489918a1.png)

### Neos 7.3

![SCR-20230114-smn](https://user-images.githubusercontent.com/39345336/212493050-8c0c0981-f0ef-4aa0-b1d2-d866337903c0.png)

### Affected Versions

Neos:
8.2
UI:
8.2

**Comment by crydotsnake** [comment]
This bug came up in #3282

**Comment by mhsdesign** [comment]
Let’s see if it will be fixed by #3366 ;)

**Comment by mhsdesign** [comment]
fixed in #3366

**Comment by mhsdesign** [comment]
Bear in mind my fix will only be available for Neo 8.3 due to technical reasons.
But I figured that its okay since people will most likely use the LTS either way ;)

**Comment by mhsdesign** [comment]
will close this as its fixed with https://github.com/neos/neos-ui/pull/3366
