### ISSUE TITLE
Feature: Make documents in pagetree into a link 

### ISSUE THREAD

**Issue by pKallert** [neos/neos-ui#3353]
### Description
This is based on feedback from Editors working with Neos.
 Editors sometimes want to work on multiple pages in parallel. For that, they open different pages in different browser tabs. 
Right now to open pages in the backend in new tabs, they have to open a new tab and navigate to the backend by hand. 

To make this workflow easier I would suggest making the documents in the page tree on the left side into links. 
This would allow backend users to open the pages with right click and "open page in new link".

**Comment by Sebobo** [comment]
This is already possible with "alt+click"

**Comment by pKallert** [comment]
Good to know, thank you 😄 
Would it still make sense to make it into a link? Right and middle click could be more intuitive for the normal user. 
Otherwise we should perhaps document it in the keyboard shortcut list

**Comment by Sebobo** [comment]
But it's not a keyboard shortcut 😉

Semantically a link or button would anyway be better. So if that helps and doesn't cause trouble it should be fine IMO.

**Comment by ahaeslich** [comment]
Semantically I would use a link ;)

**Comment by Sebobo** [comment]
I put this topic on the 8.3 release board, but I'm not yet 200% sure if this could be breaking for extensibility users. But I can verify that with my pile of plugins 😉
