### ISSUE TITLE
Text labels in creation dialog are misaligned

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#3361]
### Creation Dialog
<img width="1009" alt="CleanShot 2023-02-13 at 15 53 09@2x" src="https://user-images.githubusercontent.com/4510166/218491557-60529de9-e572-43f2-b472-05ea7640b4dc.png">

### Editors
<img width="308" alt="CleanShot 2023-02-13 at 16 36 34@2x" src="https://user-images.githubusercontent.com/4510166/218502224-0670db8b-7b5d-40c2-b59c-d001a5f9a589.png">
<img width="308" alt="CleanShot 2023-02-13 at 16 38 11@2x" src="https://user-images.githubusercontent.com/4510166/218502566-5f97ef2d-06f7-4e3f-ba61-bbe6bd305a47.png">

### Selectors
<img width="297" alt="CleanShot 2023-02-13 at 16 38 30@2x" src="https://user-images.githubusercontent.com/4510166/218502673-3a978b3c-17cd-4bee-8730-4aaec292b787.png">

### Filter
<img width="319" alt="CleanShot 2023-02-13 at 16 38 51@2x" src="https://user-images.githubusercontent.com/4510166/218502770-582f99c3-66f5-43ce-bfe8-f07228da20ce.png">

### Affected Versions

Neos: 8.2.2

UI: 8.2.4

**Comment by markusguenther** [comment]
Here i have the same issue that I could not reproduce the issue.
<img width="477" alt="Screenshot 2023-02-13 at 17 01 52" src="https://user-images.githubusercontent.com/1014126/218508788-c51a9ff4-8215-47b8-a2af-7eac591f3be6.png">

**Comment by markusguenther** [comment]
Search also looks nice
<img width="518" alt="Screenshot 2023-02-13 at 17 02 45" src="https://user-images.githubusercontent.com/1014126/218508986-25312dd0-913b-4c4e-9253-984137678f80.png">

**Comment by markusguenther** [comment]
Ok I deployed it to neos.io and there it is the same...

**Comment by Sebobo** [comment]
Same problem as in #3360 the pipeline build step mixes something up in the generated styles

**Comment by markusguenther** [comment]
Has been resolved with version 8.2.6
