### ISSUE TITLE
Remove unusefull tests `expect(true).toBe(true);`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3370]
i think one assertion is enough ;) currently we have 101

**Comment by JamesAlias** [comment]
I think those tests were some kind of reminder to actually write _real_ tests ^^

**Comment by mhsdesign** [comment]
yes but they might slow down testing and falsify our trust into them ;)
Also realistically - no one will anytime soon write the tests :P

**Comment by JamesAlias** [comment]
agreed 😅
