### ISSUE TITLE
Move from tslint to typescript-eslint

### ISSUE THREAD

**Issue by JamesAlias** [neos/neos-ui#3379]
### Description

We use `tslint` to lint our Typescript code and it is was deprecated in 2019 in favor of `typescript-eslint`.

I think it's time to make a transition and while we`re at it we can review some of the rules.

There are Rules like `interface-over-type-literal` which really bug me tbh.

Open for discussion. Maybe on a sprint.

**Comment by mhsdesign** [comment]
see also https://github.com/neos/neos-ui/issues/2662 :)

i also dislike that one cannot write `foo == null` to also check for undefined.
And lately I got used to always using parens in arrow functions so ...

**Comment by JamesAlias** [comment]
I searched for an open issue but didn't find it 🙈
