### ISSUE TITLE
BUG: Either update `@friendsofreactjs/react-css-themr` or declare correct peer dependency version

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3401]
we require `"@friendsofreactjs/react-css-themr": "^4.1.0",` which includes the lates release 4.3 but there was a little breaking change in between and the types changed or something...

so people should not install the latest version of react-css-themr for ts support but need to require the same version as us: 4.1.0

solutions:

A: pin the peerDependency to 4.1.0 so people are not confused
B: update (in yarn.lock) react-css-themr and rebuild our type declarations for the react-ui components

**Comment by mhsdesign** [comment]
I have the feeling that the type declarations of https://github.com/FriendsOfReactJS/react-css-themr are broken since 4.3

and when i look at the `themr` declaration i understand:
```ts
export default function themr(componentName: string | number | Symbol, localTheme?: any, options?: {}): (arg0: any, arg1: Function) => Function;
```
well this is bs :D

so when i locally updated the ui to themr 4.3.3

the typing generated for the react-ui-components are also useless (and ide says the same):

Button/index.d.ts
```ts
declare const _default: any;
export default _default;
```
 
i have the feeling request to use it as decorator is "wrong" https://github.com/FriendsOfReactJS/react-css-themr/issues/74 and now with the lose typing its forgiving.
Fyi typescript types for hoc DOESNT work when using decorators.


so for know im opting in for pinning to 4.1.0 and fix our https://github.com/FriendsOfReactJS/react-css-themr/ (if at all ^^ - there are discussions to remove it)

**Comment by markusguenther** [comment]
By the way, we can also fix the package as I can release a new version. ;)

**Comment by mhsdesign** [comment]
i know but i fear when we fix the package we make this (invalid usecase) broken again: https://github.com/FriendsOfReactJS/react-css-themr/issues/74
