### ISSUE TITLE
TASK: Adjust e2e pipeline for Neos 9.0

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#3406]
### Problem:

End-to-end tests are not running with Neos 9.0 because the content needs to be migrated to the new content repository first. The Neos 9.0 README contains instructions for migrating the Neos.Demo, but these need to be adapted.
The switch of the site packages also needs to be adjusted

### Solution Idea: 

Adapt the setup to the required steps of the Neos 9.0 branch documentation.
It may also be possible to utilize the new feature of multiple content repositories by creating one site for a dimension and a second site for the multiple dimensions. If we don't handle it this way, the end-to-end tests to need to be adapted to use the new importing when switching between different site packages for 1-dimensional tests and multidimensional tests. 

But guess would be nice to use the new 9.0 feature and also add an extra test to switch sites then :)

Neos: 9.0

**Comment by mhsdesign** [comment]
your wish came true

> It may also be possible to utilize the new feature of multiple content repositories by creating one site for a dimension and a second site for the multiple dimensions. 

good idea. Everything implemented and merged with https://github.com/neos/neos-ui/pull/3569 ^^
