### ISSUE TITLE
TASK: Change inside icon in create dialog

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#3407]
### Description

In the PR #3396 we have improved the create node dialog and the icon for inside was missing.
So when the custom Icon is available, we will replace the font awesome icon.

#### Expected look

![](https://user-images.githubusercontent.com/3001985/208771019-facf0a04-cf38-4867-a235-cc2e6478230d.png)

#### Actual look

<img width="952" alt="Screenshot 2023-03-06 at 13 51 40" src="https://user-images.githubusercontent.com/1014126/223115461-1c9ab3cf-b172-4897-a2d2-b327c83a8def.png">

### Affected Versions

Neos: 8.3

UI: 8.3

**Comment by manuelmeister** [comment]
I will commit this tomorrow 😊

**Comment by markusguenther** [comment]
But it is your vacation to no pressure ... the icon change is just a task and can also be done after the feature freeze ;)

**Comment by manuelmeister** [comment]
@markusguenther Where do I put the custom icons?
