### ISSUE TITLE
Stuck with react-ui-components@5.3.13 with Flowpack/Media.Ui

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-ui#3415]
I'm unable to upgrade to a more recent react-ui-components version.

## In 5.3.18

The esm build is again missing the compiled files.
Nothing to do about this anymore I guess.

## In 7.3.12

I get errors due to [`import {isNil} from '@neos-project/utils-helpers';` ](https://github.com/neos/neos-ui/blob/8aef186b161b2d9f8a5a7b399ebbb66edfe15ce5/packages/react-ui-components/src/SelectBox/selectBox.js#LL8-L8C51)

But we seem to have fixed this only in the 8.3 branch ?!?

## In 8.2.6
The esm build is again missing the compiled files. I thought we fixed that already once or twice?!?

I'm a bit frustrated with this package 😢

Best would really be to have a another step after build that builds two fake plugins, one with the esm stuff and one with the extensibility.

**Comment by Sebobo** [comment]
Have to get some work done, either someone picks this up or I will get into it when I'm in the mood.

**Comment by mhsdesign** [comment]
I fixed everything in 8.3 at least I hope so :P let’s have a chat sometime
