### ISSUE TITLE
FEATURE: Remove separate "apply"-Button from DateTime Editor

### ISSUE THREAD

**Issue by mficzel** [neos/neos-ui#3421]
### Description

The "Apply" Button of the DateTime Editor is often not visible when the datetime editor ist in the lower half of the screen. This leads to confusion when editors choose a date but the Inspector apply button stays inactive. 

Also it it a questionable ui-solution to have to push to different apply buttons in a row to actually select a date. 

This could be nicely combined with #3394 

#### Expected behavior

It would be great if the apply button at the datepicker would be removed entirely and the date would be set once the user sets a date (date-mode) or a (time).

Main Problem tody is that apply does two things: 1. Apply value, 2. Close DatePicker. If we find a different rule for closing the datepicker after editing apllying to values once they are slected should feel natural to editors.

[What actually happened]

### Affected Versions

UI: since ever

**Comment by ahaeslich** [comment]
Thx @Alvadda for your contribution 💖
