### ISSUE TITLE
9.0 TASK: Update `NodeInfoView` to ESCR changes

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-ui#3434]
### Description

In previous neos version, the `NodeInfoView` showed the following information in the inspector:

- `identifier`
- `properties._creationDateTime`
- `properties._lastModificationDateTime`
- `properties._lastPublicationDateTime`
- `properties._path`
- `properties._name`
- `nodeType`

In the current 9.0-dev version only `identifier` and `nodeType` show correct data.

Needed to complete this task: neos/neos-development-collection#4092

### Steps to Reproduce

1. Select a node
2. Got to the `Metadata`-Tab in the inspector
3. Open the Accordion ` Additional info`

### Affected Versions

- Neos: 9.0-dev
- UI: 9.0-dev

**Comment by kitsunet** [comment]
Also added the related #4208 as I think that is an issue regardless if we fix this
