### ISSUE TITLE
TASK: Improve Tabs component

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3437]
Imagine i want to implement some kind of localstorage and preselect the latest selected tab.
This is currently not possible, as i dont know at anytime, which tab was selected or when the selection changes.

Related: https://github.com/neos/neos-ui/pull/3399

**Comment by grebaldi** [comment]
I don't quite understand: Does #3399 solve the issue you're describing here or do you plan on implementing a feature for which you needed to merge #3399 first?

If the former case is true, I guess this issue can be closed. If the latter is true, I would like to suggest to re-title the issue to `FEATURE: ...`.

**Comment by mhsdesign** [comment]
sorry my changes might have been not that transparent - everything is now fine ^^
