### ISSUE TITLE
Test new `@neos-project/neos-ui-extensibility-webpack-adapter` (again)

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3461]
related: https://github.com/neos/neos-ui/issues/3445

migration looks the following:

```diff
"devDependencies": {
-  "@neos-project/neos-ui-extensibility": "^8.2.0",
-  "@neos-project/build-essentials": "^8.2.0"
+  "@neos-project/neos-ui-extensibility-webpack-adapter": "^8.3.0"
}
```

can be already tested rn, since we released a "8.3.0-beta3" https://www.npmjs.com/package/@neos-project/neos-ui-extensibility-webpack-adapter

**Comment by markusguenther** [comment]
@Sebobo Tested that with the new Media UI 👍
