### ISSUE TITLE
BUG: User-Dropdown jumps when in "small screen"-state

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#3479]
![Peek 2023-05-02 19-42](https://user-images.githubusercontent.com/2522299/235743569-72413d2b-4d6c-493d-8909-b5a05b7f821e.gif)

### Description

On smaller screens, the User-Dropdown in the top navigation bar shrinks to an icon-only version of itself. If you uncollapse the dropdown when it's in this state, it pushes the adjacent Edit-/Preview-Mode-Dropdown to the left.

#### Expected behavior

The dropdown body of the User-Dropdown underflows the Edit-/Preview-Mode-Dropdown header.

### Affected Versions

Neos: >= 7.3 (probably older versions as well)

UI: >= 7.3 (probably older versions as well)

**Comment by markusguenther** [comment]
After thorough testing, we couldn't replicate the reported issue in Chrome, Firefox, Safari, and Edge (Chromium). It seems the problem may have been specific to certain conditions or has been already fixed. Considering this, we're inclined to close the issue for now. However, we genuinely appreciate your proactive reporting. If the problem resurfaces or if you encounter it again, please don't hesitate to reopen the issue. Thank you for your diligence!

https://github.com/neos/neos-ui/assets/1014126/479a1b56-c1a8-4f0a-826c-24b1ca61ee79
