### ISSUE TITLE
BUG: Regression node info table layout broken

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3480]
8.0
<img width="318" alt="image" src="https://user-images.githubusercontent.com/85400359/235751100-4fe409b4-f9b2-44b9-bdbb-8ca701995d58.png">

8.3
<img width="311" alt="image" src="https://user-images.githubusercontent.com/85400359/235751150-c394610a-567c-416d-b1ca-be000581d853.png">

**Comment by grebaldi** [comment]
I think this should actually be a description list (`<dl/>`) rather than a table: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

**Comment by grebaldi** [comment]
This seems to occur on 8.2 as well: https://neos-project.slack.com/archives/C0U0KEGDQ/p1683116589047559

**Comment by ahaeslich** [comment]
> I think this should actually be a description list (`<dl/>`) rather than a table: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

Yes, this would be way better. Actually it currently is a `<ul/>`. As seen in this change: #3478.

**Comment by Sebobo** [comment]
Let's refactor the markup for 9.0, I fixed the style issue in #3484
