### ISSUE TITLE
BUG: `.unappliedChangesOverlay` is styled with needless `blur` filter

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#3488]
### Description

I've stumbled across an oddity while debugging the overlay that's responsible for triggering the unapplied changes dialog. When applying a background color to the container, you'll notice a slight blur at the edge:

![Screenshot_2023-05-12_12-33-21 - needless blur filter](https://github.com/neos/neos-ui/assets/2522299/68d0ec80-e447-4d3c-81e2-ac97025a7f06)

### Steps to Reproduce

1. Select a node and make some change in the inspector, but do not hit "Apply"
2. Use the browser dev tools to inspect the overlay that spans over the content canvas
3. Add a background color to the container
4. Notice blur

#### Expected behavior

There is no blur at the edge, as the container is actually transparent anyway.

### Affected Versions

I could trace the responsible CSS change down to this commit: https://github.com/neos/neos-ui/commit/94e6a5f0ac71bae4833438a753a6d58d95b4cfa8

This means, every UI version since 1.0 is affected.

I assume the intent was originally to blur everything behind the overlay (similarly to what the login box in the Neos login screen does). If this was the intent, I've never seen it work, and today imho this would rather be achieved via `backdrop-filter` (see: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter).

For now, I think, we should just get rid of the `blur` filter.

**Comment by crydotsnake** [comment]
Closed, since the PR for fixing this issue has been merged.
