### ISSUE TITLE
[9.0] Unknown named parameter $nodeTypeConstraints

### ISSUE THREAD

**Issue by crydotsnake** [neos/neos-ui#3514]
### Description

https://github.com/neos/neos-ui/blob/b2222ab1c8c429462cdec9fac2568f47a6eb727e/Classes/Fusion/Helper/NodeInfoHelper.php#L273-L284

```php
FindChildNodesFilter::create(nodeTypeConstraints: $nodeTypeFilterString)
```

### Steps to Reproduce

Go to the neos backend.

#### Expected behavior

Neos UI should not breake.

#### Actual behavior

Neos UI breaks.

![SCR-20230601-ptfm](https://github.com/neos/neos-ui/assets/39345336/a05435e5-0f18-4f21-9ab4-f2dc77d9a700)

### Affected Versions

Neos: 9.0

UI: 9.0

You can get this information by running `composer show` or using the package management module within Neos.
The UI version can also be found inside the left sidebar after version 1.0.3.

**Comment by mhsdesign** [comment]
After checking the code in the new cr 9.0 i found out that the named argument is correctly used:

https://github.com/neos/neos-development-collection/blob/2a6c0ff4ee880da095056be436e003607305d708/Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Filter/FindChildNodesFilter.php#L47

were you able to find something when checking it locally?

**Comment by mhsdesign** [comment]
cant reproduce locally
