### ISSUE TITLE
9.0 BUG: UI calls backend API with node path

### ISSUE THREAD

**Issue by nezaniel** [neos/neos-ui#3528]
In a multi-site environment (not sure whether this is important), when I navigate to the site node, the UI calls

https://acme.site/neos/service/nodes?workspaceName=user-admin&contextNode=%2Fsites&&nodeIdentifiers%5B0%5D=576233aa-2a09-404a-aa46-e6fe2fde14d2

(via Host.js). The given context node is a node path but must be a node address, leading to
`Warning: Undefined array key 1 in /.../Packages/Application/Neos.Neos/Classes/FrontendRouting/NodeAddressFactory.php line 64`

This only happens on the homepage, on other documents this endpoint isn't called at all

**Comment by nezaniel** [comment]
The multisite environment seems to be at least part of the issue.
This behavior is triggered by a reference editor being configured with a node path as starting point, which leads to above, unresolvable request

**Comment by mhsdesign** [comment]
didnt you fix this lately? 

see slack https://neos-project.slack.com/archives/C3MCBK6S2/p1686524742614209

**Comment by nezaniel** [comment]
Yes, this is resolved with the merge of the seriousRootNodes branch
