### ISSUE TITLE
8.3.0 -> 8.3.1 breaks CKE placeholder functionality for elements without autoParagraph

### ISSUE THREAD

**Issue by patricekaufmann** [neos/neos-ui#3557]
There is no placeholder being rendered when autoParagraph is set to `false`. The attribute `data-neos-placeholder` and the ::before Tag rendering the placeholder are both missing.

8.3.0:
![image](https://github.com/neos/neos-ui/assets/41791606/d7c2640a-e020-4c16-ae32-6e2819b4c71d)

8.3.1:
![image](https://github.com/neos/neos-ui/assets/41791606/fc914b16-5e50-4375-ae43-a099cdf77198)

**Comment by mhsdesign** [comment]
Thank you so much for reporting it that fast. We tried to make sure that https://github.com/neos/neos-ui/pull/3532 doesn't break anything accidentally but it seems the placeholder needs some extra love.

**Comment by mhsdesign** [comment]
fixed ;) and will be released soon with 7.3.19 ;)
