### ISSUE TITLE
E2E Flaky Tests ` Discarding: delete a content node and then discard deletion`

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3562]
### Description

it is just super flaky, it succeeds locally 1 out of 5 times and similar or worse on CI

<img width="1076" alt="image" src="https://github.com/neos/neos-ui/assets/85400359/450e8106-3ad7-44cc-9e62-3d2a674d4f04">

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Affected Versions

Neos:

UI:

You can get this information by running `composer show` or using the package management module within Neos.
The UI version can also be found inside the left sidebar after version 1.0.3.

**Comment by grebaldi** [comment]
This should be fixed by https://github.com/neos/neos-ui/pull/3560

See my commennt: https://github.com/neos/neos-ui/pull/3560#issuecomment-1621761003
