### ISSUE TITLE
TASK: Allow node v16 for 7.3...8.1

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3566]
On my mac, i simply cant get node 14 to run - and so far everything seems to work with node 16 as well.

**Comment by crydotsnake** [comment]
Use nvm for managing your node versions :)

**Comment by mhsdesign** [comment]
any opinions @grebaldi or @markusguenther? i mean we dont have to use it in ci, but if it works id like to allow it so i dont have to edit package.json all the time 😂 (again Node 14 doesnt work or sth on my system - and i like 16 better xD)

**Comment by grebaldi** [comment]
@mhsdesign 

If it builds, v16 ought to be fine. I don't think it collides with anything (and I'm sure I've run it accidentally in my local environment on 7.3 without issues :D). 

@crydotsnake 
> Use nvm for managing your node versions :)

I'd like to recommend https://github.com/Schniz/fnm instead - it's the much faster option.

**Comment by mhsdesign** [comment]
When we allowed Node 16 for newer branches we first stumbled upon a problem, that some unit test didnt work: https://github.com/neos/neos-ui/pull/2980

Also in the final pr for 8.1 there are some other files change. Im just thinking of backporting it?
https://github.com/neos/neos-ui/pull/3075

**Comment by mhsdesign** [comment]
One of the adjustments in #3075 was related to https://github.com/DevExpress/testcafe/issues/7097 which is now closed so it might be we can clean up this snippet in the e2e tests?

https://github.com/neos/neos-ui/blob/5881ede007f21fd03449d43e0717a03255b946c1/Tests/IntegrationTests/utils.js#L31C63-L34


interestingly, i dindt encounter any issues when running the e2e test on 8.0 https://github.com/neos/neos-ui/pull/3560 (i ran them on 8.0 and node 16)

**Comment by mhsdesign** [comment]
But the fetch polyfill introduced with #3075 

https://github.com/neos/neos-ui/blob/5881ede007f21fd03449d43e0717a03255b946c1/packages/neos-ui-backend-connector/src/FlowQuery/index.spec.js#L8

can definitely be backported

**Comment by grebaldi** [comment]
I'm not so sure there actually. Native fetch would require Node >= v16.15.0 (https://nodejs.org/en/blog/release/v16.15.0), and in v16, it is still behind a flag (v18 LTS removes that).

**Comment by grebaldi** [comment]
solved by: https://github.com/neos/neos-ui/pull/3589
