### ISSUE TITLE
BUG `plow` deprecated log spamming

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3594]
regression from https://github.com/neos/neos-ui/issues/3425

<img width="1481" alt="image" src="https://github.com/neos/neos-ui/assets/85400359/4e9f96e6-a62a-44b3-a08d-6ae337c00600">

i feared this already, but dindt know it was that bad ^^

**Comment by Sebobo** [comment]
Yes it's a bit annoying.

**Comment by mhsdesign** [comment]
i guess we can only trigger it once per caller entry point? But how? `get_debug_backtrace` ^^
