### ISSUE TITLE
BUG: Datepicker in AM/PM time and Su-Sa week format regardless of interface language

### ISSUE THREAD

**Issue by marco-wildermuth** [neos/neos-ui#3599]
### Description

The datepicker in the inspector shows the time in AM/PM format and the weeks starting on Sundays regardless of configured `Neos.Neos.userInterface.defaultLanguage` or selected interface language.

### Steps to Reproduce

The Neos Demo Site https://demo.neos.io/ currently has one of the affected UI versions 8.3.0. Create an account there and login to the backend or run an affected Neos installation locally.

1. Log in to the backend
2. Go to your user settings

<img width="565" alt="Screenshot 2023-08-22 at 11 52 43" src="https://github.com/neos/neos-ui/assets/60606559/358478f9-0cf6-4a5f-b294-746a55f58910">

3. Make sure that you have `Deutsch - German` selected as your interface language

<img width="245" alt="Screenshot 2023-08-22 at 11 53 27" src="https://github.com/neos/neos-ui/assets/60606559/4949d734-7207-4bb2-b81d-70bcab729eba">

4. Go back to the content and to any page
5. Go to the metadata tab in the inspector on the right and open the datepicker from `hide until` or any other datepicker

<img width="321" alt="Screenshot 2023-08-22 at 11 56 13" src="https://github.com/neos/neos-ui/assets/60606559/5a750bbe-d646-4405-a94e-aef65389a4c4">

#### Expected behavior

The datepicker in the inspector should show the time in 24h format and the weeks starting on Mondays for locale `de`.

<img width="321" alt="Screenshot 2023-08-22 at 11 57 24" src="https://github.com/neos/neos-ui/assets/60606559/001eae1f-16ed-49f2-95ab-cae17ef3c2f8">

#### Actual behavior

The datepicker in the inspector shows the time in AM/PM format and the weeks starting on Sundays for locale `de`.

### Affected Versions

Neos UI: 8.3.3, 8.3.0, possibly since 8.0.0

This used to work up until at least v7.3.3

---

This does not seem to be an issue with the wrong locale from `user.preferences.interfaceLanguage` being passed to the `react-datetime` DatePicker via `@neos-project/react-ui-components` DateInput. It contains "de".

This may very likely be an issue with other user interface languages also.

Thank you very much.

**Comment by mhsdesign** [comment]
might be fixed via https://github.com/neos/neos-ui/pull/3596 ;)

**Comment by mhsdesign** [comment]
is released ;)
