### ISSUE TITLE
BUG: DimensionSwitcher dropdown not visible at specific zoom levels

### ISSUE THREAD

**Issue by c4ll-m3-j4ck** [neos/neos-ui#3639]
### Description

At certain browser zoom levels, the language selector dropdown disappears. This only affects the DimensionSelector component and none of the other dropdowns in the primary toolbar.

### Steps to Reproduce

Set your browser zoom to something like 50% (we have seen this vary from computer to computer depending on the available screen-size). 
Click to toggle the DimensionSwitcher

#### Expected behavior

The dimension-selection dropdown should appear

#### Actual behavior

The dimension-selection dropdown does not appear

### Affected Versions

Neos: 8.3.5

UI: 8.3.4

**Comment by c4ll-m3-j4ck** [comment]
I have investigated this issue some more:

It appears that the dropdown for the single-dimension-selector is appended at the wrong dom-node as it gets appended directly to the body-tag. Every other dropdown (including multi-dimension-selector) gets appended to the respective dropdown dom-node. 

Starting at a certain zoom-factor (in my case it is 33% but again, this seems to vary from computer to computer), the misplaced <ul> dom-node for the dropdown gets its style-attribute updated to simply be `style="display: none;"` and is therefore not shown.

**Comment by markusguenther** [comment]
Will be resolved with the release of 8.3.6.
