### ISSUE TITLE
When inserting document nodes, create "mini-wizard" to set page name (wouldn't do that in the tree anymore)

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#364]

**Comment by skurfuerst** [comment]
Discussed this in Team-Unicorn; definitely a great idea! we should build this right in this way.

**Comment by dimaip** [comment]
@skurfuerst I would want to do this during the sprint

**Comment by skurfuerst** [comment]
awesome Dmitri :)

**Comment by skurfuerst** [comment]
https://github.com/neos/neos-ui/pull/379
