### ISSUE TITLE
Relocate User Menu to Left Drawer for Improved Navigation

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#3685]
### Description:
The current positioning of the user menu in the primary bar has been identified as a potential area for improvement. Considering user behavior, where the user menu is primarily utilized for actions like logging out, we propose relocating it to the left drawer. This adjustment aligns with established UX patterns observed in other systems, where the user menu is de-emphasized and accessed when needed. 

### Proposed Change:
Move the user menu from the primary bar to the left drawer to minimize its prominence in the interface. This approach reflects the user behavior, where interactions with the user menu are infrequent and often limited to specific actions such as logging out (which is not the most used action). Backend modules should be updated to maintain a consistent and streamlined user interface.

### Expected Benefits:

* Reduced prominence of the user menu, allowing the primary focus on essential application features.
* Simplified user interface, aligning with established UX patterns observed in other systems.
* Enhanced user experience by reducing visual clutter and emphasizing core functionalities.
* The drawer has way more space, and therefore we are able to add additional information, like a user avatar.

### Additional Information:
We've identified an opportunity to enhance the Neos User Interface (UI) by making it more consistent and user-friendly. The proposed changes include restructuring the primary and secondary toolbars, moving the workspace selector to the top level, and incorporating feedback from users, such as Daniel Kestler. This adjustment is part of our ongoing efforts to optimize the Neos User Interface based on user behavior and industry-standard UX patterns. 

https://github.com/neos/neos-ui/issues/3247
https://github.com/neos/neos-ui/issues/3803

**Comment by laurahaenel** [comment]
I would like to help with that topic at the upcoming sprint in Hamburg :)

**Comment by laurahaenel** [comment]
This change is affected by the open bug [#4590](https://github.com/neos/neos-development-collection/issues/4590)
