### ISSUE TITLE
(ImageEditor) Persisted Aspect ratio is not accurately re-calculated in the Cropper

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#369]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

Instead of `16:9` for instance, we get some numbers like `382:147`

![cropper-aspect-ratio](https://cloud.githubusercontent.com/assets/2522299/19691857/0dd049ca-9ad6-11e6-9413-7e6d0c605ded.png)

**Comment by Torsten85** [comment]
FYI: For the resolution 1146x441,  382:147 is the smallest possible fraction and its not 16:9.
16:9 is `1.777..7778`, this is `2.59..` 

so my guess is that the aspect ratio is calculated correctly.

**Comment by mstruebing** [comment]
I would say you are right, I've testet it with an aspect ratio of 4:3 and it was displayed correctly, so I'm closing this for now.
