### ISSUE TITLE
Creation dialog icons are not shown in Neos installations with subfolder setting

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-ui#3712]
![image](https://github.com/neos/neos-ui/assets/1756367/efb3c6a4-498f-4660-ae51-b5746f66e8fc)

Steps To Reproduce

1. Use a Neos installation in a subfolder (e.g. [www.myproject.com/subfolder/neos](http://www.myproject.com/subfolder/neos))
2. Trigger the creation dialog by creating a new node in the document or content tree

This is essentially caused in the `ResourceIcon` component:

https://github.com/neos/neos-ui/blob/fe77db35c48e886b7a0421ccf3e2f0da6d098e52/packages/react-ui-components/src/Icon/resourceIcon.tsx#L26

Relates: #3423

**Comment by mhsdesign** [comment]
Closing as dub of https://github.com/neos/neos-ui/issues/3616 and its about to be fixed 🎉
