### ISSUE TITLE
FEATURE: Offer resolution strategies when conflicts arise during rebase

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#3744]
When conflicts arise during publishing, the user needs a way to decide what to do about them. A possible conflict situation would be for instance:

> `Editor A` removes content node `TextElement-1` and publishes their change. Meanwhile, `Editor B` edits the contents of `TextElement-1`. Once `Editor B` publishes their workspace, `TextElement-1` is already gone. The changes to `TextElement-1` cannot be published.

In this case, `Editor B` would currently run into an exception during publish:
![Screenshot_2024-03-25_14-16-37 Publish Error](https://github.com/neos/neos-ui/assets/2522299/14efd2c8-f8c7-4373-8473-90907813c49c)

That is, if `Editor A` had published their removal changes during an ongoing editing session of `Editor B`. In this case, `Editor B` would not be informed about their workspace having gone into `OUTDATED_CONFLICT` state.

When `Editor B` reloads the page, their workspace state is properly reflected:
![Screenshot_2024-03-25_15-23-43 Sync Button](https://github.com/neos/neos-ui/assets/2522299/ee25971e-5648-4869-95ed-cecee6da488a)

Upon clicking the `Synchronize personal workspace` button, `Editor B` is currently informed that there's no way out of here:
![Screenshot_2024-03-25_12-57-27 Snyhcronize Workspace Error](https://github.com/neos/neos-ui/assets/2522299/9b3c78dc-6666-4eda-90f9-625737491b80)

`Editor B` is now trapped. Reasonably, they should at least be able to discard their workspace, but this currently leads to an error as well:
![Screenshot_2024-03-25_12-58-31 Discard Error](https://github.com/neos/neos-ui/assets/2522299/96424675-ef89-46c2-b9d2-0ce0c61dc57e)

A way to escape this trap would be to perform a `force-rebase` on `Editor B`s workspace. This has been implemented here: https://github.com/neos/neos-development-collection/pull/4939

During the Hamburg spring, @ahaeslich, @mficzel and I discussed the following basic strategies that we can offer the user in case of conflicts:

1. "Discard All" - If publishing fails due to conflicts, we allow the user to throw away all changes
  - This additionally requires an "Are you sure?"-confirmation type dialog
2. "Save what you can" - We allow the user to publish everything that can be published, while throwing away all changes that can't (see: https://github.com/neos/neos-development-collection/pull/4939)
  - For this, we would (ideally in beforehand) display information to the user, so they can understand what they're about to lose if they were to choose this strategy

*Additional strategies had also been discussed (with input from @nezaniel and @mhsdesign), with regards on retaining conflicting changes for later use. We concluded that it's best to focus on the above strategies for 9.0 and explore other solutions later.*

Here's a sketch for a possible dialog workflow:
![Untitled-2024-03-26-1410 Rebase Conflict Resolution](https://github.com/neos/neos-ui/assets/2522299/744710fe-f4b7-453f-b685-e82556afecb1)
(https://excalidraw.com/#room=b7f4a755ffda65849f6a,1SW-iMdJIpdvwWJWwb-CdQ)

***(1)** A Select box in anticipation of `n` possible strategies. At the moment, this select box would contain the options "Discard All", "Save what you can" and "Cancel". The latter will just abort the publishing operation.*
***(2)** Conflicts may be complex and numerous. We will need some way to summarize them for editors.*

**Open Questions**

- [x] What info can we reasonably display about publishing conflicts in the UI?
  - The newly introduced `RebaseFailedException` (see: https://github.com/neos/neos-development-collection/pull/4965) gives us a list of failed commands accompanied by the exception that made the respective command fail. We can deduce from the command which node was affected and what kind of modification was made. We can deduce from the exception class what has caused the conflict.
- [ ] How do we explain that "Discard All" during conflict resolution is not the same thing as "Discard All" in the Publish Dropdown?
  - "Discard All" during conflict resolution will discard everything in the workspace
  - "Discard All" in the Publish Dropdown will discard all changes in the current site, but leave other sites untouched

**Acceptance Criteria**

- [x] If a user clicks on "Synchronize" and a conflict arises during the rebase operation, they are presented with a dialog that allows them to choose between several conflict resolution strategies
- [x] If a user chooses "Cancel" from the resolution strategy selection, the rebase operation is aborted without side effects
- [x] If a user chooses "Discard all" from the resolution strategy selection, their changes are discarded globally
- [x] If a user chooses "Save what you can" from the resolution strategy selection, they are presented with a dialog summarizing what changes they are about to lose
- [x] If a user clicks on "Cancel" in the "Save what you can" summary dialog, they are again presented with the resolution strategy selection
- [x] If a user clicks on "Continue" in the "Save what you can" summary dialog, the rebase operation starts again, this time setting the `force` flag (as established in https://github.com/neos/neos-development-collection/pull/4939) to `true`
- [x] There is an E2E test scenario that creates a conflict state between two editors and asserts the results of choosing "Discard all" as a resolution strategy during rebase
- [x] There is an E2E test scenario that creates a conflict state between two editors and asserts the results of choosing "Save what you can" as a resolution strategy during rebase

**Comment by mficzel** [comment]
Good description. I only would add that the we ended up calling "Save what you can" forced-rebase.
Also it would be a viable option for 9.0 to include those in the rebase dialog when the workspace is in OUTDATED_CONFLICT state where it currently only says "call your admin | cancel".

**Comment by grebaldi** [comment]
I've updated the issue description, so it refers to "rebase" rather than "publish". I'll open another issue to integrate both operations.
