### ISSUE TITLE
BUG: 9.0 `change-base-workspace` is infinite loop and times out - always?!!

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3787]
In my tests changing the base workspace does not succeed:

<img width="317" alt="image" src="https://github.com/neos/neos-ui/assets/85400359/082da02e-224a-43dc-af3d-260dff1ad784">

(at least im not able to switch back to live)

This might be because the code that is bugged in 8.3 https://github.com/neos/neos-ui/pull/3734 doesnt work in 9.0 either.
(at least in the code there is a `while true` ...

https://github.com/neos/neos-ui/blob/28fb9c5e8e92a88fe8d79666b454b19c5533cff3/Classes/Controller/BackendServiceController.php#L469

Scenario 1:

- create workspace
- create new subpage in workspace and publish and highlight it
- change workspace to live again

->  fails currently

But scenario 2

- create workspace
- create new subpage in workspace
- create new subsubpage in workspace
- publish and highlight the new subsubpage
- change workspace to live again

->  fails currently

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Affected Versions

Neos:

UI:

You can get this information by running `composer show` or using the package management module within Neos.
The UI version can also be found inside the left sidebar after version 1.0.3.

**Comment by ahaeslich** [comment]
I just ran into the same issue. After switching to a base workspace other than live I can't change it to any other workspace.

Didn't change or publish anything btw. Just wanted to switch back.
