### ISSUE TITLE
BUG: placeholder for the `LinkEditor` cannot be set

### ISSUE THREAD

**Issue by dr-format-d** [neos/neos-ui#3797]
### Description

If you try to use the `LinkEditor` you cannot set a custom placeholder. If you try to set one, the default placeholder gets replaced with another different fallback placeholder.

### Steps to Reproduce

1. create a new property in your `.yaml` file for any node-type, setting its `editor:` to `Neos.Neos/Inspector/Editors/LinkEditor`
2. set a placeholder
3. look at your configured node-type in the neos frontend

#### Expected behavior

When I set a custom placeholder through my `.yaml` configuration, I expect to see my custom placeholder in the frontend.

#### Actual behavior

If I set a custom placeholder, it is ignored and a static fallback placeholder is used instead.

### Affected Versions

Neos: -

UI: every Version since 11.09.2018, currently in 8.3

**Comment by Sebobo** [comment]
Thx for spotting the issue and the fix!
