### ISSUE TITLE
BUG: Simply clicking into a ckeditor text field and afterwards selecting something else triggers a change

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#3832]
>  I fear this change introduced a regression which was not found during testing nor > is covered by e2e.
> I noticed that simply clicking into a ckeditor text field and afterwards selecting > something else triggered a change.
> This happens for every text element:
> 
>  <img width="274" alt="image" src="https://github.com/user-attachments/assets/cb64c15b-de57-44f8-96ad-783081101487">

_Originally posted by @mhsdesign in https://github.com/neos/neos-ui/issues/3751#issuecomment-2233110498_

To illustrate that a little more:

https://github.com/user-attachments/assets/9050d860-9cd9-4c50-a3ae-30a3b0642929

**Affected Versions:**

Neos UI: 8.3

**Comment by crydotsnake** [comment]
Can reproduce this too.

**Comment by crydotsnake** [comment]
@grebaldi I still have the issue if i use the dev version of neos-ui and compiled. But not with the 8.3.9 UI release 🤔

**Comment by Sebobo** [comment]
@crydotsnake maybe some cache effect on your side

**Comment by crydotsnake** [comment]
> @crydotsnake maybe some cache effect on your side

I flushed the cache afterwards.

**Comment by Sebobo** [comment]
I meant build cache of the UI
