### ISSUE TITLE
BUG: Remove leading and tailing whitespace in LinkInput

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-ui#3859]
### Description

Editors often had the case that they copied links from an Excel list and then pasted them into e.g. LinkEditor fields.

If the people do not notice that a space at the end of the URL was copied or a tab at the beginning, the link immediately leads to a 404. 

### Steps to Reproduce

https://github.com/user-attachments/assets/06052606-d2d8-4383-bd24-1b0c6d57e989

#### Expected behavior

The links is trimmed so that we do not save the leading or tailing whitespace.

### Affected Versions

Neos: 8.3 (but guess it happens also in earlier versions)

UI: 8.3

**Comment by Jai-Marothiya** [comment]
Hello @markusguenther,

I am interested in solving this bug and I believed I can fix it. Please assign this issue to me.

**Comment by markusguenther** [comment]
Thank you for taking on this issue. However, we already have an open pull request for this. You are welcome to review it.

**Comment by Jai-Marothiya** [comment]
Cool, can you assign me 1-2 relevant issues similar to this or may be different on which I can work?

**Comment by Jai-Marothiya** [comment]
I reviewed your PR and it looks good.
