### ISSUE TITLE
Create git-hooks for a better development expirience

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#39]
The plan is, to create the following hooks: 
`prepare-commit-msg` -> Validates the commit message against the Neos commit guidelines 
`post-merge` -> updates npm dependencies after a rebase, merge, checkout and pull 
`pre-commit` -> lints all source files, currently I am not sure if we should also run karma as well (Boot time of karma is pretty long tbh)

**Comment by GerDner** [comment]
FYI 'check-dependencies' will check missing dependencies and will install them

**Comment by mstruebing** [comment]
This issue is solved see #356
