### ISSUE TITLE
Memorize the prop functions which get passed down into child-components

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#56]
Currently we often got a pattern like this:

``` js
<Button onClick={() => this.props.onClick()} />
```

which is insufficient since it breaks the component life-cycle, especially `shouldComponentUpdate()`. Instead we should memorize the passed functions to prevent unnecessary re-render calls and function creations.

**Comment by grebaldi** [comment]
Is this still relevant, since we avoid props of that fashion due to the `jsx-no-bind` linting rule anyway?

**Comment by Inkdpixels** [comment]
Yup :) :+1:
