### ISSUE TITLE
When selecting a page in the page tree, the loading indicator loads forever

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#568]
and the nodes are not editable.

Tested with Chrome on Mac at master / b4f0ec9974471284057d1d4949c4c526d27fff85.

When I reload the loaded page (CMD-R), editing is working. 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/642226/24172779/cbc393f2-0e89-11e7-953a-a5c3bee2cb43.gif)

**Comment by skurfuerst** [comment]
Weirdo, for me this worked... @daniellienert are you at the sprint so we can check this together in your instance?

**Comment by daniellienert** [comment]
For sure 😉

**Comment by dimaip** [comment]
Same stuff on my sites, on demo it's OK. I couldn't quickly figure out what's up, will spend time on the sprint to fix it.

**Comment by skurfuerst** [comment]
should be fixed now
