### ISSUE TITLE
Creating Content Dialog shows no elements for a new column element

### ISSUE THREAD

**Issue by mgoldbeck** [neos/neos-ui#578]
* created a new 2 column element in Demo
* wanted to add a new content element to the collection
* new content element dialog show no elements to select from

<img width="1288" alt="neos_cms" src="https://cloud.githubusercontent.com/assets/1336044/24361675/c654a728-130a-11e7-9ac5-702c5d73311b.png">

* after a reload the content elements are shown
* selecting is possible for old ones

<img width="1278" alt="neos_cms" src="https://cloud.githubusercontent.com/assets/1336044/24361719/e9318d56-130a-11e7-9425-83c01263680d.png">

**Comment by dfeyer** [comment]
You need to change the position, the second option work. Basically we need to improve this new UI currently it's not really easy to get
