### ISSUE TITLE
heading dropdown spanning full width

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#585]
old UI
![screen shot 2017-03-27 at 18 59 39](https://cloud.githubusercontent.com/assets/683773/24368125/92c82654-131f-11e7-8a1a-c39075475769.png)

vs. new UI

![screen shot 2017-03-27 at 18 58 48](https://cloud.githubusercontent.com/assets/683773/24368145/a335564c-131f-11e7-9c9e-aa9b69ec95e8.png)

**Comment by skurfuerst** [comment]
fixed now :=)
