### ISSUE TITLE
main menu is different to old version and changes when opening e.g. "Management" in new ui

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#589]
old UI
![screen shot 2017-03-27 at 19 17 05](https://cloud.githubusercontent.com/assets/683773/24368809/284e14e8-1322-11e7-901f-81c9ee038e89.png)

vs.

new UI
![screen shot 2017-03-27 at 19 16 37](https://cloud.githubusercontent.com/assets/683773/24368819/346e5d8c-1322-11e7-9bb3-50767be51a40.png)

and when opening management from within the new UI, the old UI is still used and therefore the old menu will be loaded and look like this:

![screen shot 2017-03-27 at 19 19 58](https://cloud.githubusercontent.com/assets/683773/24368863/67f20f3c-1322-11e7-8ac8-a6c1cb0aa198.png)

Should be consistent until all modules are implemented in the the UI

**Comment by skurfuerst** [comment]
fixed now!

**Comment by jonas-siegl** [comment]
I'm looking forward to fixing it. In consultation with @skurfuerst, the styling of the old ui should be used.

**Comment by dimaip** [comment]
Is this resolved?

**Comment by mstruebing** [comment]
I would think yes: https://github.com/neos/neos-ui/commit/1b52b135c5fcbdf4c6b552b84ad3358e99221e0c
