### ISSUE TITLE
old ui loading inside iframe when going to the old ui via a link and going back to the new ui using the browser back

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#591]
You can load the new ui inside the iframe by following these simple steps:

1. goto the new UI
2. open "Management"
3. open "Content" via the main menu
4. the old ui will be loaded
5. use the browser back button two time and you get the following behaviour

![mar-27-2017 19-26-47](https://cloud.githubusercontent.com/assets/683773/24369496/7cda86c0-1324-11e7-87fb-d711a17872d8.gif)

**Comment by skurfuerst** [comment]
fixed! see #590 and #603
