### ISSUE TITLE
breaks in the text of a headline NodeType do not show up after publishing

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#596]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

when publishing from within old UI
![screen shot 2017-03-27 at 20 39 45](https://cloud.githubusercontent.com/assets/683773/24372252/a52ba95c-132d-11e7-85ec-63bbb58bcb36.png)

when publishing from within the new UI
![screen shot 2017-03-27 at 20 41 40](https://cloud.githubusercontent.com/assets/683773/24372305/d35529d4-132d-11e7-909e-b88f43b55673.png)

This means i am not able to create manual breaks.

Seems to work for "Text" NodeType.

**Comment by skurfuerst** [comment]
to clarify / test in the demo site

**Comment by johannessteu** [comment]
Can't reproduce

**Comment by kitsunet** [comment]
can't reproduce, just tested again. The <br> ends up INSIDE of the H1, but that is just fine...
