### ISSUE TITLE
structure tree cannot be collapsed

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#599]
old UI
![screen shot 2017-03-27 at 20 56 06](https://cloud.githubusercontent.com/assets/683773/24372937/ef862962-132f-11e7-908d-9dcde6b021ee.png)

vs.

new UI
![screen shot 2017-03-27 at 20 55 57](https://cloud.githubusercontent.com/assets/683773/24372943/f69a51e2-132f-11e7-9915-1a40ff8bfd2e.png)

chevron down missing in the upper right corner

**Comment by mgoldbeck** [comment]
fixed by #780
