### ISSUE TITLE
using cut, copy or delete of content and document NodeTypes leads to strange behaviour of the publish button or breaks publishing completely

### ISSUE THREAD

**Issue by crazydrecksack** [neos/neos-ui#600]
example for cutting and inserting content NodeType
![mar-27-2017 21-07-10](https://cloud.githubusercontent.com/assets/683773/24373832/f8d2cc7a-1332-11e7-9f37-ed99f3121489.gif)

Publish button will pretend to save changes and then turn green. After a reload it turns orange and you now can press publish.

example for deleting a content NodeType
![mar-27-2017 21-13-12](https://cloud.githubusercontent.com/assets/683773/24373889/4ba35960-1333-11e7-8b48-e8127fb4f095.gif)

This completely breaks the publish button. It will stay orange no matter what. Even after a reload. Can only be fixed by using the workspace module in the old ui to discard or publish changes.

These problems seem to be the same for content and document NodeTypes

**Comment by dfeyer** [comment]
Can you please check again, I think nothing related to the clipboard, but https://github.com/neos/neos-ui/pull/651 should solve this issue

**Comment by dfeyer** [comment]
Tested work fine now.
