### ISSUE TITLE
Copy Pasting Content Collection should be disallowed is it's an auto created child

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#609]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

You can copy paste a content collection from a multi column element to somewhere else, who make non sense. Not sure how can handle this nicely.

https://dl.dropboxusercontent.com/s/9h6ro60z1zutq9r/2017-03-28%20at%2017.48.png

**Comment by skurfuerst** [comment]
If the node is auto created, disallow copy/move on it!
