### ISSUE TITLE
Hard to select a multi column element

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#611]
Selecting the content collection work fine, but with the structure tree it's nearly impossible to select the multi column element for my ex. adding an element after. As we don't even have the breadcrumb in the inspector it can make the life of editors a bit difficult

**Comment by dimaip** [comment]
I don't understand what's this about. Still relevant?

**Comment by grebaldi** [comment]
@dfeyer The breadcrumb is now available. Does this solve the issue?

**Comment by mstruebing** [comment]
As there is no reaction I close this for now
