### ISSUE TITLE
Dummy element on an emtpy content collection is not removed when adding a node 

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#613]
https://dl.dropboxusercontent.com/s/kmikmvyijjanep4/2017-03-28%20at%2017.32.png

When you add an element in an empty content collection, the dummy element (gray border on top) stay, if reload the page, everything OK

**Comment by skurfuerst** [comment]
should be fixed by https://github.com/neos/neos-ui/pull/632

**Comment by mstruebing** [comment]
This can also be closed, I tested it on the demo page
