### ISSUE TITLE
Freshly created content collection are invisible

### ISSUE THREAD

**Issue by dfeyer** [neos/neos-ui#646]
After the insertion:
![](https://dl.dropboxusercontent.com/s/0x52da7xdh6u85n/2017-03-30%20at%2012.24.png)

After a reload:
![](https://dl.dropboxusercontent.com/s/p0hc8urma6isphk/2017-03-30%20at%2012.21.png)

The gray box are only visible after a reload

**Comment by skurfuerst** [comment]
should be fixed by https://github.com/neos/neos-ui/pull/632

**Comment by mstruebing** [comment]
Iäve tested it on the demo page and it is working like expected so I think this issue can be closed.

**Comment by skurfuerst** [comment]
Thanks <3 Fixed by wilhelm's big refactoring :)
