### ISSUE TITLE
Do not send full serialized node info for UI updates

### ISSUE THREAD

**Issue by gerhard-boden** [neos/neos-ui#647]
We should only send the necessary tree and node information when providing data for updates. Otherwise we do a lot of recursive child node operations, but we should reduce it to the essential data needed for updating the UI (the initial information can stay stored on the client side).

Example: 
`Neos\Neos\Ui\Domain\Model\Feedback\Operations::serializeNodeRecursively()`

*on the other hand, we do not send all Content nodes of the page (if they are not included in the page output themselves) -- but we should (to make the structure tree work*

**Comment by skurfuerst** [comment]
This is a must-have for 1.0.0 final as it makes the UI unusable for larger trees

**Comment by skurfuerst** [comment]
Might be partially solved with https://github.com/neos/neos-ui/pull/768

**Comment by dimaip** [comment]
Removing from 1.0 for now.

**Comment by skurfuerst** [comment]
fixed for now.
