### ISSUE TITLE
Remove <p> <p/> in placeholder

### ISSUE THREAD

**Issue by SreyleakH** [neos/neos-ui#652]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

It comes with 'Text' and 'Text with Image' :

<img width="250" alt="1 place holder for text" src="https://cloud.githubusercontent.com/assets/23726789/24502479/3a1b2e6c-154e-11e7-89f7-95eec8dfbd71.png">

<img width="397" alt="screen shot 2017-03-30 at 13 39 51" src="https://cloud.githubusercontent.com/assets/23726789/24502509/61c36df8-154e-11e7-9e22-40b18e53ba7e.png">

**Comment by skurfuerst** [comment]
Marked as must have because it affects all users.
