### ISSUE TITLE
Editing Mode display in small screen

### ISSUE THREAD

**Issue by SreyleakH** [neos/neos-ui#653]
<img width="547" alt="editing modes" src="https://cloud.githubusercontent.com/assets/23726789/24502660/150039a0-154f-11e7-9571-591d9fee21b8.png">

**Comment by gerhard-boden** [comment]
Fixed in https://github.com/neos/neos-ui/pull/631

**Comment by mgoldbeck** [comment]
As it is fixed in https://github.com/neos/neos-ui/pull/631 I close this
