### ISSUE TITLE
Link editor doesn't work with external links

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#683]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**
**[<- Reference/Select Rewrite](https://github.com/neos/neos-ui/issues/649)**

Overall the link selectbox editor is really hard to work with due to how it is made: inheritance, complicated and rather weird config etc. I'd rather try to break it apart into smaller and simpler components.

**Comment by skurfuerst** [comment]
resolved by now!
