### ISSUE TITLE
CKeditor encodes quotes content looks "modified" in workspace review

### ISSUE THREAD

**Issue by sorenmalling** [neos/neos-ui#689]
**Issue**

From the Demo Site Package, in the memberarea, i changed the word `for` to `fir` in the first line.
Looking into the Workspace review (see picture below) that is not marked as changed. But all quotes from the Policy.yaml example i encoded.

Perhaps a CKeditor issue (when transporting to the Neos backend) perhaps not

![image](https://cloud.githubusercontent.com/assets/531918/25003833/9965fba0-2051-11e7-81fe-fe47b4f566f6.png)

**Comment by dimaip** [comment]
Actually this is a part of a bigger issue: CKeditor should not encode quotes at all! Closing in favor of #955
