### ISSUE TITLE
If more than one dimension - urls for preview and backend are wrong

### ISSUE THREAD

**Issue by peterbucher** [neos/neos-ui#697]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

Issue
The dimension values (if more than one) are wrongly concatenated.
This does affect the Uri wich is set on the iframe and also the url of the backend itself.

Currently Urls
Backend: https://www.site.dev/neos!?node=/sites/cms@user-bucher;country=int&amp;language=en
IFrame: https://www.site.dev/@user-bucher;country=int&amp;language=en

Correct Urls (I think they should be like this)
Backend: https://www.site.dev/neos!?node=/sites/cms@user-bucher;country=int&language=en
IFrame: https://www.site.dev/@user-bucher;country=int&language=en

Compare & amp ; versus &

Reproduce
Login to the Backend with site.dev/neos!
The Backend does endless reloading
In the preview iframe, there is a 404 error
Click some other node and check the Uri of the backend

Versions affected
Neos 3.0 / Flow 4.0
Beta and dev-master of neos/neos-ui

Browser
Google Chrome

**Comment by skurfuerst** [comment]
Hey Peter,

thanks for your feedback; it is very valuable to us! I've added the ticket to the 1.0 Must-Have Milestone.

All the best,
Sebastian

**Comment by dimaip** [comment]
@skurfuerst does this work now?

**Comment by kitsunet** [comment]
_Seems_ to work, just did a quick test. Although I *think* to be fully correct this `&` would need to be urlencoded => `%26`
Technically right now we are sending TWO arguments to the server. `node` and `country`. (Can be tested if you check the arguments displayed in a phpinfo() if you append that query string to it)

**Comment by mstruebing** [comment]
This fixed now, isn't it?
