### ISSUE TITLE
Collection of old UI suggestions/wishes

### ISSUE THREAD

**Issue by kitsunet** [neos/neos-ui#703]
These are all from the neos issues and mostly a bit older. Still could be good to have a look and transfer to this project if tackled.
Otherwise remove from list if you think it's irrelevant.

https://github.com/neos/neos-development-collection/issues/775
https://github.com/neos/neos-development-collection/issues/769
https://github.com/neos/neos-development-collection/issues/770
https://github.com/neos/neos-development-collection/issues/786
https://github.com/neos/neos-development-collection/issues/785
https://github.com/neos/neos-development-collection/issues/802
https://github.com/neos/neos-development-collection/issues/814
https://github.com/neos/neos-development-collection/issues/859
https://github.com/neos/neos-development-collection/issues/959
https://github.com/neos/neos-development-collection/issues/1048
https://github.com/neos/neos-development-collection/issues/788
https://github.com/neos/neos-development-collection/issues/880
https://github.com/neos/neos-development-collection/issues/922
https://github.com/neos/neos-development-collection/issues/832
https://github.com/neos/neos-development-collection/issues/985
https://github.com/neos/neos-development-collection/pull/709

more to come here...

**Comment by dimaip** [comment]
This collections has served us as an inspiration, some of these issues were already resolved, so I'll close this for now. Please re-open as separate issues things that you think still are relevant. Or better post them as RFCs on discuss.
