### ISSUE TITLE
Wrong escaping for title in document tree

### ISSUE THREAD

**Issue by robertlemke** [neos/neos-ui#719]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

Document titles which contain an ampersand "&" are wrongly escaped in the document tree when the UI is freshly loaded. Once the document with the "&" is loaded (for example by clicking on the title), the title will appear correct.

See screen recording for an example – after clicking both titles I reloaded the UI.

![documenttitle](https://cloud.githubusercontent.com/assets/95582/25887318/f1db02c4-3561-11e7-8bc1-159be58fe1b0.gif)

Tested on www.neos.io (Neos 3.0.x + UI package as of May 9th).

**Comment by skurfuerst** [comment]
Hey Robert,

thanks for your feedback; it is very valuable to us! I've added the ticket to the 1.0 Must-Have Milestone.

All the best,
Sebastian

**Comment by kitsunet** [comment]
This was not exactly a low hanging fruit... Fix incoming.
