### ISSUE TITLE
Implement Data Sources in Select Editor

### ISSUE THREAD

**Issue by DavidSporer** [neos/neos-ui#725]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

(old title: JavaScript error with custom data source)

Hi,

I've now tried to the new UI with [cvette/neos-code-block](https://github.com/cvette/neos-code-block) which is working fine in the old UI. If I use the new UI and add one of these NodeTypes that are using a [custom data source](https://github.com/cvette/neos-code-block/blob/master/Classes/DataSources/GeshiLanguagesDataSource.php) I get the following JavaScript error.
If you need more information, please ping me but that's not yet my field of knowledge to be honest.
The page is running on http://developer.passcreator.com and I can give you backend access if needed.

```
Uncaught TypeError: Cannot set property '/sites/support@user-davidsporer' of undefined
  at t.value (Host.js:47)
  at HTMLDivElement. (Host.js:41)
  at Object._renderSubtreeIntoContainer (Host.js:39)
  at Object.renderSubtreeIntoContainer [as unstable_renderSubtreeIntoContainer] (Host.js:39)
  at HTMLDocument.r.renderFrameContents (Host.js:41)
  at HTMLDocument. (/@user-davidsporer:24)
Host.js:47 Uncaught TypeError: Cannot set property '/sites/support/node-591948280494e@user-davidsporer' of undefined
  at t.value (Host.js:47)
  at HTMLDivElement. (Host.js:41)
  at Object._renderSubtreeIntoContainer (Host.js:39)
  at Object.renderSubtreeIntoContainer [as unstable_renderSubtreeIntoContainer] (Host.js:39)
  at HTMLDocument.r.renderFrameContents (Host.js:41)
  at HTMLDocument. (/pass-templates@user-davidsporer:24)
```

**Comment by skurfuerst** [comment]
Hey @DavidSporer,

the error looks a little strange to me; so I don't really get why the error happens. Are you sure that the error only happens when you have the package installed? To me it looks like the error would happen regardless of the package being installed or not; in which case we need to find the specifics of your website triggering the error.

Thus, could you try removing the package and seeing what happens?

All the best,
Sebastian

**Comment by DavidSporer** [comment]
@skurfuerst yes, pretty sure. It also doesn't occur if the package is installed itself. It occurs if I add a Node Type called "Code Block" that is shipped with the package. In that case the Inspector is broken and displays the page settings instead of the settings of the Code Block Node Type (which is basically the same as the HTML Element which is working plus another select editor).
Can't remove the package right now since I'm on the wrong machine but like I said it's working as long as I don't have a Code Block node type added to the page.
Would it help you if I give you backend-access to that Neos page?

**Comment by cvette** [comment]
The package uses the following editors:

editor: 'Neos.Neos/Inspector/Editors/CodeEditor'
editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'

**Comment by skurfuerst** [comment]
Hey @DavidSporer and @cvette - thanks for your feedback!

OK; so it might actually be related to the Select Editor or so... Strange nevertheless! I'll try out the package myself after I finished the rewrite, and then report back. This might take another two weeks...

All the best,
Sebastian

**Comment by skurfuerst** [comment]
FYI: I'll start looking into this now - was quite a bit delayed; but now finally...

I think we do not support DataProviders yet; so I'll start to implement them :)

**Comment by skurfuerst** [comment]
Resolved in https://github.com/neos/neos-ui/pull/764
