### ISSUE TITLE
Loading indicator should be shown after adding a new page

### ISSUE THREAD

**Issue by DavidSporer** [neos/neos-ui#727]
Currently, if I add a new page it takes a couple of seconds until the page is shown in the left sidebar/page-tree. There's no indication that the page is currently being created.
After a few seconds the page is shown but until then it looks like something went wrong.
IMHO the page should be displayed right away with a loading indicator like it is shown when expanding pages. The indicator should disappear after the page has actually been persisted.
Not sure if that's a known issue but I think it could improve the UX.
Here's a gif that shows how it looks on my Neos setup:
https://cloud.passcreator.com/index.php/s/S5VacktLtji6rgu

**Comment by akoenig** [comment]
Yeah, I think that the UX could be improved in this area. Maybe we could use the indicator which is also visible when the whole UI is bootstrapping. That could be extracted into an own component and hooked into the "Node creation" action flow.

I give it a shot.

**Comment by akoenig** [comment]
What do you think of that?

![3486c965-d0ab-42db-y4df-96a47807ccf4](https://user-images.githubusercontent.com/224910/28870822-041a7048-7782-11e7-8f5f-d686c86f2e49.gif)

**Comment by akoenig** [comment]
I did not implement the solution above. Had a quick chat with @mstruebing regarding this scenario. We came to the conclusion that it would lead to a different user experience which should be avoided at that stage of the rewrite. The PR shows the orange progress bar instead :)
