### ISSUE TITLE
If inspector tabs are empty and hidden they don't reappear

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#753]
If I click on a node without some inspector tabs they are not reappearing if I change to a node which should have inspector tabs like you can see when I click on the member area. If I click outsite the selected node the tabs are reappearing

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/12071529/27839809-938c4476-60f4-11e7-8e04-08c216a9ad3b.gif)

**Comment by skurfuerst** [comment]
Could it be that we do not change the "active" node correctly when selecting a node in the tree? :-)

**Comment by skurfuerst** [comment]
fixed with #759
