### ISSUE TITLE
Fire events to notify the guest frame of changes made in the UI

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#754]
We should fire the same events as in the Ember UI (on node creation, node removal etc.) as documented here:

http://neos.readthedocs.io/en/stable/ExtendingNeos/InteractionWithTheNeosBackend.html#javascript-events

Some events are obsolete due to the iframe solution. These would be imho:

* Neos.PageLoaded
* Neos.PreviewModeActivated
* Neos.PreviewModeDeactivated
* Neos.LayoutChanged
* Neos.NavigatePanelOpened
* Neos.NavigatePanelClosed
* Neos.InspectorPanelOpened
* Neos.InspectorPanelClosed
* Neos.EditPreviewPanelOpened
* Neos.EditPreviewPanelClosed
* Neos.MenuPanelOpened
* Neos.MenuPanelClosed
* Neos.FullScreenModeActivated
* Neos.FullScreenModeDeactivated

All of these would now be eual to `DOMContentLoaded` in the guest frame. But maybe we should fire them anyway to make it possible to distinguish between the different states they represent?

**Comment by skurfuerst** [comment]
I'd suggest if we have a website which makes use of these events, we can check whether we really need them (and which ones)

**Comment by jonnitto** [comment]
Not all of them makes sense. But `Neos.NodeCreated`, `Neos.NodeRemoved` and `Neos.NodeSelected` would be very useful and important

**Comment by DrillSergeant** [comment]
I need that in a current project. Especially I need to know when a content node is inserted into the DOM and I need to know the nodeType in the eventlistener.

If someone can implement this in the near future (next 3 weeks), I can offer some donation from my project budget. Currently I could give like 500 € for that.

**Comment by dimaip** [comment]
I had this on my todo list, but the tricky part is figuring out what events are really needed.
E.g. currently all of these things are already possible via our extensibillity API (by registering a custom Saga and listening for the right kind of Redux actions).
@DrillSergeant maybe we could have a call about what things you would want to achieve and what would be the best way to do it?

**Comment by DrillSergeant** [comment]
@dimaip yeah nice. We already chatted on slack about this. I would love to explain my need during a call.

**Comment by jonnitto** [comment]
@dimaip I think @grebaldi has there a good opinion: His list of events who are obsolete looks very good to me. At the end, there are this events left:

- `Neos.NodeCreated`
- `Neos.NodeRemoved`
- `Neos.NodeSelected`

The only I would recommend to have from the obsolete ist is `Neos.FullScreenModeActivated` and `Neos.FullScreenModeDeactivated`, because sometimes you want to use it as a "fast preview"
