### ISSUE TITLE
Pages can be added after main content collection

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#766]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

When selecting the main content collection in the content tree, press plus and select "insert after" the list of document nodes is shown.

This is technically correct but a bit confusing for editors. I would propose to disable the "insert after" mode there.

**Comment by skurfuerst** [comment]
Hey,

I think forbidding this completely might not be the right approach; as there might be cases where Document Nodes will be directly editable on the page -> then it would feel natural to be able to insert them directly in-place in the content area.

I could imagine the following: We make it configurable on a per-node-type basis whether it is shown in the "Add Content" dialog or not. For Content, we enable it by default; for Document, we disable it by default.

What do you think?

All the best, Sebastian

**Comment by daniellienert** [comment]
Hey Sebastian, 
that would be a good default behavior!

Cheers, 
Daniel

**Comment by skurfuerst** [comment]
Hey,

marking this as "Must have for 1.0" as it is a major usability issue for editors.

All the best, Sebastian

**Comment by dimaip** [comment]
Hey guys!
I don't think I'm in favor of adding another configuration option before 1.0.
I propose this behavior: when a document node is selectable inline, when you click an inline button, you'd get a dialog with only document nodes there, same as you would get from the document tree toolbar.
When you click add node button from content tree toolbar, you'd get just content nodes, consistent with the old UI.
Wdyt?

**Comment by skurfuerst** [comment]
Good idea <3 Let's do it your way
