### ISSUE TITLE
Remove quick fix for ContentElementWrapping

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#771]
When this is merged and in a stable release we could remove the quickfix from the neos-ui

see:
https://github.com/neos/neos-ui/commit/1fb4ac5f57a180f42bb06fed4391b430e0412e42
https://github.com/neos/neos-development-collection/pull/1635

**Comment by dimaip** [comment]
This is merged. Anyone took care already?

**Comment by skurfuerst** [comment]
I'd for now keep it, as it makes the React UI compatible with Neos 3.0 and up.

**Comment by markusguenther** [comment]
Is this still relevant. Mean the new UI works now on 3.3 and 4.0 ... so backwards compatibility is not needed anymore. Or what is the goal? Should the UI also work on 3.2

**Comment by dimaip** [comment]
I'd say let's go for it
