### ISSUE TITLE
Sortable multiselect/references editor

### ISSUE THREAD

**Issue by samuelhauser** [neos/neos-ui#774]
The multiselect and references component should be sortable

**Comment by mstruebing** [comment]
Just for reference: 
https://github.com/neos/neos-ui/pull/764

**Comment by samuelhauser** [comment]
@mstruebing why just for reference? i think it should be for both?

**Comment by mstruebing** [comment]
I mean maybe @skurfuerst is implementing it or is able to implement it as he goes but just to make sure that the connection is there

**Comment by skurfuerst** [comment]
Hey,

just a question: Is this possible in the old UI? I just want to understand if this is a (definitely cool/nice to have feature) or a must have for 1.0.

All the best,
Sebastian

**Comment by grebaldi** [comment]
It's definitely possible in the old UI and a very important Feature actually :)

**Comment by johannessteu** [comment]
I'll give it a try this weekend!

**Comment by dimaip** [comment]
Probably should use react-dnd for it, since we already use it.

**Comment by johannessteu** [comment]
Jip! I wanted to check the nodetree etc. to use the same lib

**Comment by dimaip** [comment]
react-dnd has some learning curve, got to read through a few tutorials to get it.
You'd need to add your drag type here: https://github.com/neos/neos-ui/blob/master/packages/neos-ui/src/Containers/dndTypes.js

**Comment by johannessteu** [comment]
I already implemented it in a dashboard we use internally, so guess i'll get id working. But thanks for the hint!!
