### ISSUE TITLE
Extract z-index variables into constants

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#793]
Currently, our usage of z-index is a jungle. Would be nice to extract those constants like we did in the old UI: https://github.com/neos/neos-development-collection/blob/30599d9a88aa537ab867b0a2b7c68690c6cfe00c/Neos.Neos/Resources/Private/Styles/Foundation/_variables.scss#L144

**Comment by Duske** [comment]
I'd like to take this issue, but I guess I need some guidance here first:
1) Since we are not using SASS for the components, we could CSS variables to store these values, right?
2) Afaik, the CSS vars which are currently used are either in `@neos-project/brand` or directly set in the shared [`webpack.config.js`](https://github.com/neos/neos-ui/blob/master/packages/build-essentials/src/webpack.config.js#L55). Where should we put things like z-indices?

**Comment by dimaip** [comment]
Thanks for the initiative to take care of it!
Needs some thinking through... My immediate thoughts are to extract css variables into a separate js file (for clarity), and put z-index constants there.
You may suggest better alternatives of course.

**Comment by Duske** [comment]
So kinda like it's done for [`@neos-project/brand`](https://github.com/neos/brand/blob/master/index.js)? 
We could put the existing variables which are set in the `webpack.config.js` there, too.
The next question which comes to my mind is, where we put such a separate js file solely for styling.

**Comment by dimaip** [comment]
Yes. But no, let's not put anything into brand, it's a separate package that is hard to manage, and these z-index constants are purely technical, they are not related to brand styles.
That's a good question where to put it. Probably most simple answer is just to put it alongside the webpack.config.js file in build-essentials, to avoid external dependencies.

**Comment by Duske** [comment]
Totally agree, I did not mean to put it in a separate package since I've seen a git submodule abyss at work :D 
I guess I just create a PR and then we can look what needs to be changed/improved.

**Comment by dimaip** [comment]
Yep, trust your intuition here :)

**Comment by Duske** [comment]
I've created a PR but I am not really happy with the result. It reveals some aspects which should be discussed like naming of the variables and structure of the configuration object.
