### ISSUE TITLE
Mark a new change in the page/content tree

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#806]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

If I made some changes to some nodes I expect that these nodes are marked with an orange indicator like in the old ui, which is currently not the case.

![screenshot_2017-08-04_10-16-54](https://user-images.githubusercontent.com/12071529/28960229-0e14407e-78fe-11e7-87e6-b2fabc043487.png)

**Comment by skurfuerst** [comment]
As that's an important UI concept from the old UI, we should replicate it!
