### ISSUE TITLE
When following external link, UI just navigates to that link without giving an error

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#811]

**Comment by akoenig** [comment]
@dimaip Just investigated it a little bit. My first thought was that when I click on an external link within the `ContentCanvas` it would load that external URL within the `iframe`, but this is not what happens :) Can you elaborate a little bit on that?

**Comment by dimaip** [comment]
@akoenig but that's exactly what happens with me!

See:
![peek 2017-09-01 09-48](https://user-images.githubusercontent.com/837032/29958324-e0f58a5e-8efa-11e7-95f3-aea9d6c970b7.gif)

**Comment by dimaip** [comment]
Should be fixed now.
