### ISSUE TITLE
When the canvas is reloaded after applying inspector, it doesn't scroll back to reveal the focused node

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#815]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

Steps to reproduce:

1. have an html nodetype somewhere down the page
2. edit its contents, click apply
3. after the canvas reloads, it stays on top, instead of revealing the focused node

**Comment by skurfuerst** [comment]
True! If we reload the current page in the iframe, we should beforehand store its scroll position and restore it.

**Comment by dimaip** [comment]
@skurfuerst just a thought. Maybe instead of saving the scroll position we could reuse our `requestScrollIntoView` mechanism to scroll to the focused node? That would be even a bit more reliable, e.g. when changes in inspector affect the amount of stuff rendered, and the given content node would have a new scroll position after the page reload... wdyt?

**Comment by skurfuerst** [comment]
Yeah, sounds good to me 👍 - very good idea!
