### ISSUE TITLE
When switching focused node, inspector becomes blank if the focused nodetype doesn't have that group

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#826]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

Steps to reproduce:
1. open in inspector some group that only this nodetype has, e.g. SEO group
2. focus a node that doesn't have such group, e.g. Text
3. contemplate inspector staying blank, instead of focusing to first available group in the new nodetype

![image](https://user-images.githubusercontent.com/837032/29366326-6b769ee4-82a2-11e7-9d8e-b522b077f95c.png)

**Comment by skurfuerst** [comment]
Major usability issue for editors; we need to fix this!
