### ISSUE TITLE
Move nodes without prompting for position

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#830]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)** 

When moving nodes now you are presented with a position selection dialog. I prefer how the move used to work in the old ui. Now every move requires a bunch of extra clicks and it's not easy to grasp the concept at first. Wdyt?

**Comment by dimaip** [comment]
Feedback from Daniel: "I noticed the same, and share your opinion. It’s more clear what is happening im the one hand but a lot more clicks on the other. Makes a quick resorting of the tree impossible."

**Comment by dimaip** [comment]
I would suggest to target this for 1.0, but only if we have time left. Still this is a big UX issue IMO.
@skurfuerst your thoughts?

**Comment by daniellienert** [comment]
@dimaip / @skurfuerst - after working with the UI as an author for some days now, I would like to push this issue again. Reordering nodes or moving them into container nodes is really painful now.

**Comment by dimaip** [comment]
Yep, we agreed to re-implement tree DND properly. Will take care.

**Comment by dimaip** [comment]
@daniellienert reviews are welcome
