### ISSUE TITLE
HTML code editor doesn't expand to full height before starting to scroll

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#832]
![peek 2017-08-23 11-20](https://user-images.githubusercontent.com/837032/29605927-4b44f4ba-87f5-11e7-8a7c-5fd2f4dd08f0.gif)

**Comment by skurfuerst** [comment]
For me, that's more Medium-Prio than High-Prio (as the HTML editor is probably not used that often in Projects). I am not sure how easy to fix it is. If it's a 30 minute thing, then let's go for it; if it is 1 day then I'd skip it for now.

**Comment by dimaip** [comment]
Agreed. It's super annoying actually, as you look at the editor and think that that's all code there is. Made me confused on real project and I was wondering for a while to what actually happened to my code...
Should be easy to fix.

**Comment by Duske** [comment]
I guess the problem was the way the height of the codemirror-component was set. In the PR I used the `setSize()`-method of codemirror, which seems to solve the problem.
