### ISSUE TITLE
After changing inspector property, you are not forced to apply changes

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#833]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

i.e. it's possible to navigate away to another node, and there's no dialog prompting you to apply changes.

**Comment by skurfuerst** [comment]
That's something I am quite unsure about -- the old behavior always felt kinda wrong (but ignoring it seems wrong as well); so maybe we have a clever idea how to change/fix this in a good way?

**Comment by dimaip** [comment]
I think the way to improve it would be to have auto-saving inspector editors, but that's definitely not smth for 1.0 and would require a lot of UX considerations. For now I propose to implement it just the way it was, should be easy.

**Comment by skurfuerst** [comment]
Totally agreed :)
