### ISSUE TITLE
Scrolling contentCanvas is a bit weird

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#835]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

See:
![peek 2017-08-24 16-15](https://user-images.githubusercontent.com/837032/29668099-a8188114-88e7-11e7-9b16-3ecf3b793fba.gif)

**Comment by skurfuerst** [comment]
Why does the content canvas scroll once you click the inline texts?

**Comment by dimaip** [comment]
It worked like this in the old UI, to bring edited node into view. We can change it ofc.

**Comment by skurfuerst** [comment]
Uhm, as far as I understand, behavior should have been the following:

* You click in the Content Tree -> Scrolling happens to move the element into view
* You click a content element in the content area -> no scrolling happens whatsoever.

Does the 2nd error occur? It looks like it in the video?

**Comment by dimaip** [comment]
Behavior in the old UI:
- You click in the Content Tree -> Scrolling happens to move the element into view
- You click a content element in the content area -> element scrolls into view, to reveal its handles + content tree scrolls to reveal that node.

Maybe it makes sense to drop that behavior and do as you have written.
But in addition to that the scrolling position now is chosen wrongly, so if you keep switching between two elements it keeps on moving down, till it reaches the bottom. That is very easy to fix.
