### ISSUE TITLE
Properly handle exceptions in API requests

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#841]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

If one of our API endpoints responds with a Flow exception (for whatever reason), the UI fails to parse the response as JSON: `Failed to discard SyntaxError: Unexpected token < in JSON at position 0`, and this is not visually reflected anywhere.

We should wrap it into try/catch and show big red message of death in case it happens.

**Comment by skurfuerst** [comment]
will fix alongside #901

**Comment by dimaip** [comment]
Should be fixed now, feel free to re-open if not.
