### ISSUE TITLE
Editing a property from another page causes browser tab to freeze and crash

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#842]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

Steps to reproduce:
1. On the demo site, go to some page _other than main_.
2. Click on the `Powered by Neos & Flow` text in the footer.
3. Contemplate the complete browser tab lock up with 100% CPU utilization
On the main page it just works.

Tested in Chrome on Ubuntu.

**Comment by dimaip** [comment]
@grebaldi probably you should know why it happens?

**Comment by skurfuerst** [comment]
I'll start working on this now!

**Comment by skurfuerst** [comment]
fixed, see PR!
