### ISSUE TITLE
Each CKE editable has weird tooltip

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#845]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

![image](https://user-images.githubusercontent.com/837032/29970267-94456cc4-8f2c-11e7-9d18-257ca6475174.png)

**Comment by grebaldi** [comment]
Can be configured: https://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-title

**Comment by dimaip** [comment]
So shall we just set it to false? Or configure it to show propertie's label?

**Comment by grebaldi** [comment]
Interesting idea. Let's give it a try and set the option to the property's label and to `false`, if no label is configured, so you can opt-out as an integrator.
