### ISSUE TITLE
CKE-Link target won't close on a click on a non content element

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#855]
Steps to reproduce:
1) Select a link in textbox, the link target will appear
2) click somewhere bot not another content-element, e.g. on a menu
3) the link is no longer focused bit the link target is still shown
 
http://recordit.co/QcoNjNgZrH

**Comment by dimaip** [comment]
Can't reproduce anymore. Feel free to reopen if it's still there for you.
