### ISSUE TITLE
Collect APIs/Configuration which are extended (related to the old UI); so that we know what docs to update on release

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#861]
* Settings.yaml
  * [ ] Preview Modes width and height
* NodeTypes.yaml
  * Creation dialog elements: https://github.com/neos/neos-ui/blob/master/Configuration/NodeTypes.yaml#L4 + node creation handlers (but that's a Flow change): https://github.com/neos/neos-ui/blob/master/Configuration/NodeTypes.yaml#L16

**Comment by dimaip** [comment]
Settings.yaml: loading user scripts. Passing settings to frontend.

**Comment by dimaip** [comment]
No longer relevant, right @skurfuerst?
Will close for now, feel free to reopen if needed.
