### ISSUE TITLE
Make Background Color in ContentCanvas configurable

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#863]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

Currently, the Content Canvas flickers to "white" when a page load occurs. We should be able to add a background color in configuration to prevent this.

Although this is actually "minor", it is needed by one of the Core Feature Sponsors.

**Comment by dimaip** [comment]
Let's make sponsors happy, makes sense :+1:

**Comment by skurfuerst** [comment]
#861
