### ISSUE TITLE
Make Dropdown menus (like workspace menu) scrollable if they contain lots of content

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#864]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

Currently, if your workspace menu contains a lot of content, the user cannot reach all of them (and it might break the design). So we should add a max height.

Although this is actually "minor", it is needed by one of the Core Feature Sponsors.

**Comment by dimaip** [comment]
:+1: 

P.S.: I would not consider it minor either, I think such small UX issues accumulate into poor overlall perception of the UI, we should locate and tackle as much of such "minor" as time allows, it will be very hard to solve later, when we switch back to spare-time development mode...
