### ISSUE TITLE
Allow to set extra styles on Span and Div elements

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#865]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

We should "officially" support to set additional classes to spans and/or divs. Not sure whether we want to do this though the extensibility; or just through NodeTypes.yaml - we need to think what is better for now.

This needs new config (#861), and is needed by one of the Core Feature Sponsors.

**Comment by dimaip** [comment]
We discussed it here at the sprint and suggest to leave it as is for now, i.e. via extensibility, and just provide a good example for it in the docs. Fine with you @skurfuerst?
