### ISSUE TITLE
Extract configuration, initialState and other data from html into external files

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#868]
Right now host html weights 1.2mb!
It takes 350ms to generate the page (TTFB), and then it takes a while to load and parse (think about slower devices). Also I often get `net::ERR_INCOMPLETE_CHUNKED_ENCODING` for some reason (probably nginx buffering stuff because of large html size).

I propose to load all of this stuff in extra requests.
We can cache them aggressively and add md5 cachebreaker for cache invalidation.
`initialState` can not be cached, as it needs to be generated each time, but if it is loaded in an additional request we can show the loader, start loading (and even parsing) of other assets.
This will greatly improve perceived responsiveness of initial load as well as speed it up overall.

It's a no-brainer to implement, but I don't propose to include it into must-have for 1.0, but if you agree on the general concept I'd implement it in my spare time, once the main work is done.

**I just need your feedback if you agree with this or not.**

**Comment by skurfuerst** [comment]
Makes sense to me, as long as we do not cache stuff client side in local storage (but let the browser handle it ;) ) - as you proposed makes total sense :)
