### ISSUE TITLE
Cleanup dependencies

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#877]
If somebody has some spare time, would be nice to resolve these warnings at some point:

![image](https://user-images.githubusercontent.com/837032/30053155-7c88377c-9230-11e7-87a5-a2b8bea6fc7a.png)

**Comment by markusguenther** [comment]
We have one warning actually regarding the react-codemirror and this could not be resolved. There is actually no new version. Otherwise I need to adjust this package and trigger Jet Wadson.

**Comment by markusguenther** [comment]
Created a PR for react-css-themr to be react 16 compatible. Then this warning will be also gone :)

https://github.com/javivelasco/react-css-themr/pull/88

**Comment by dimaip** [comment]
This issues is outdated

**Comment by markusguenther** [comment]
@Dmitri i guess the react-collapse warning is still there
