### ISSUE TITLE
Decouple URL handling from the website view

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#88]
As suggested by @aertmann in https://discuss.neos.io/t/rfc-rewriting-the-ui-as-a-separate-package-functional-prototype-included-using-react/775/50:

> URL handling should be decoupled from the website view. Instead of using the node URL, the identifier should be used to avoid making a website focused application. E.g. replace http://neos.dev/en/download@user-admin;language=en_US.html with http://neos.dev/?node=e5171e7f-8898-be7a-4c05-147ed00f7a00@user-admin;language=en_US.

**Comment by aertmann** [comment]
As a side note, the speaking URL could still be shown in the UI, just not in the address bar.

It will make it more robust as well and open the possibility to improve the URL handling for stuff like split view ``http://neos.dev/?node=e5171e7f-8898-be7a-4c05-147ed00f7a00@user-admin;language=en_US&node2=e5171e7f-8898-be7a-4c05-147ed00f7a00@user-admin;language=fr_FR``.

Also allows for handling multiple sites within one domain.
