### ISSUE TITLE
Implement Groups in SelectBox

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#892]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

the old UI supported a "groups" key in the Select Box; which we do not support in the new UI yet.

It should be implemented in react-ui-components/SelectBox; as it will then automatically work for Select/MultiSelect editors.

I personally think it would be fine to deliver this feature after 1.0.

This is a reminder / follow-up for https://github.com/neos/neos-ui/pull/764.

**Comment by dimaip** [comment]
I agree, but still let's try to squeeze it, if time would allow?
It would be so cool to have a feature-complete UI by 1.0!

**Comment by skurfuerst** [comment]
A colleague of mine just learning react will tackle this in the upcoming days :) (Leon)

**Comment by dimaip** [comment]
Also take notice of this issue when working on it: https://github.com/neos/neos-ui/issues/944

**Comment by klfman** [comment]
The issue does not comment on rules for sorting the options and/or groups in any particular order (e.g. alphabetically). Can anyone comment on this and tell me if I have to take care of sorting inside the component?

**Comment by skurfuerst** [comment]
@klfman sorting groups based on "first group in list is displayed first", leaving options in the order they were provided :)

**Comment by dimaip** [comment]
I'm adding this for 1.0, as we still have some time left, and this feature existed in the old UI, so would be sad if the new UI will not have it.

**Comment by dfeyer** [comment]
Check https://neos-project.slack.com/files/U4A2LD7QU/F7UV045EF/ui_select_box.mov the react UI as some kind of partial support of the grouping ;)

**Comment by skurfuerst** [comment]
I think the grouping is basically implemented, but the keyboard-accessibility-change broke it again. Correct @mstruebing - could this be? :-)

**Comment by dimaip** [comment]
Blocked by #1362
