### ISSUE TITLE
When a node has a missing childNode, discard returns an error

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#896]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

1. Create a document node of a nodetype X
2. Add some new childNodes to nodetype X in NodeTypes.yaml, but DO NOT run `./flow node:repair`
3. Edit some content on that page
4. Try to discard changes and see `Nodes in a in a workspace without a base workspace cannot be discarded.`
5. Reload the page. Then discard would work.

If you inspect the failing request, you'd the missing childNode's context path there, even though it doesn't exist.
`./flow node:repair` obviously solves the issue.

**Comment by dimaip** [comment]
@skurfuerst do we want to fix it for 1.0? `node:repair` solves the issue, but it's not easy to track down for editors/integrators....

**Comment by grebaldi** [comment]
I can reproduce the issue in another way:

1. Go to demo sites homepage
2. Edit the Title override and hit apply

(You'll notice 4 changes, all contentcollections on the homepage are marked as changed)

3. Try to discard all changes

You'll get the very same error message: `Nodes in a in a workspace without a base workspace cannot be discarded.`

Reloading the page helps as well (though only 2 changes are left then, so discard seems to work at least partially but doesn't update the number).

**Comment by grebaldi** [comment]
Update: This happens in the current UI as well, so it's not related to the UI package. It happens in `2.3` already. Seems more like a bug in Neos.Neos or Neos.ContentRepository. I'll have a look and open an issue in https://github.com/neos/neos-development-collection

**Comment by grebaldi** [comment]
Here we go:

https://github.com/neos/neos-development-collection/issues/1710
https://github.com/neos/neos-development-collection/pull/1711

**Comment by dimaip** [comment]
Thanks for investigating, closing it here.
