### ISSUE TITLE
Show Re-Login Dialog if Session Timed Out

### ISSUE THREAD

**Issue by skurfuerst** [neos/neos-ui#901]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

## Concept idea

wrap all endpoints internally in neos-ui-backend-connector such that once a request fails due to authnetication problems, we re-queue this request and all following requests to a queue.

Furthermore, we dispatch an action which in turn triggers the re-login dialog.

After re-login is successful, we will execute all requests serially.

## Related

I'd also add a callback if an error occured (in the same way); to display a message then (see #841)

**Comment by dimaip** [comment]
Sounds really cool!
