### ISSUE TITLE
Orange change indicator should be aligned left

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#911]
I would suggest to align all the indicators at the left inspector border.
![image](https://user-images.githubusercontent.com/642226/30181983-739329d8-9415-11e7-8dce-e5aa1ee1188d.png)

**Comment by dimaip** [comment]
It's not easy to do unfortunately, the way this tree is implemented.
Dunnot if we should include it into 1.0...

**Comment by skurfuerst** [comment]
I'll give it a try. have an idea how this might be fixed
