### ISSUE TITLE
The title edit field on document creation writes right-to-left

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#914]
Tested on Mac in Chrome and Firefox.
Other input fields are working correct.

![strange title edit behavior](https://user-images.githubusercontent.com/642226/30211507-909a6014-94a1-11e7-9f52-60c0a194f82b.gif)

**Comment by skurfuerst** [comment]
can reproduce it, will check

**Comment by dimaip** [comment]
I fixed it, please check.
