### ISSUE TITLE
Changing multiple properties will only persist one

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#916]
If you have a nodetype with several text properties, and you fill them out all and press apply, only the first text property is persisted. So it is not possible to set more than one property at once.

**Comment by dimaip** [comment]
Can't reproduce :(

**Comment by johannessteu** [comment]
I'll dig deeper into our setup and try to give an reproducable scenario. My collegue showd me the issue today and i had the same on that installation. Maybe it's something in between that is causing the issue

**Comment by johannessteu** [comment]
@dimaip just tried again. I actually can reproduce it right now. I'll try to reproduce it also in a fresh demo installation with a new nodetype. If i change 3 properties at the same time, press apply 3 chnage requests are send. One is ok, 2 are not and return a 403 status code. Looks like the difference ist the content-type. It's `application/json` for the requests that dies work. And `text/html` for those that does not work.
<img width="767" alt="bildschirmfoto 2017-09-08 um 22 09 52" src="https://user-images.githubusercontent.com/769789/30229620-f1a0fc88-94e2-11e7-8b58-153d35d06430.png">
<img width="778" alt="bildschirmfoto 2017-09-08 um 22 09 42" src="https://user-images.githubusercontent.com/769789/30229624-f4a1ef78-94e2-11e7-964a-380a6053b464.png">

**Comment by dimaip** [comment]
@skurfuerst how about we accumulate all property change requests in a saga and send them off in one request?
Looks really scary to send of so many requests at once! (will in 20 fields and the server may die...).

**Comment by skurfuerst** [comment]
yep we should do this!

**Comment by dimaip** [comment]
Ok, should be pretty easy, will take care

**Comment by dimaip** [comment]
@johannessteu please review if this PR fixes your issue!
