### ISSUE TITLE
Moving a content node is not reflected in the structure tree

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#918]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

When the node is moved the change is not shown.
Saving indicator right top corner is showing "saving" - when the page is reloaded it shows the moved state.

Tested with #afc631c on Chrome / Mac

![moving node is not shown in strcuture tree](https://user-images.githubusercontent.com/642226/30216151-5428bdae-94b2-11e7-9c57-2932b105d188.gif)

**Comment by dimaip** [comment]
Can not reproduce :(

**Comment by dimaip** [comment]
Actually I tried in Firefox, and there drag-n-drop doesn't work altogether... I plan to re-implement dnd without useing html5 dnd api next week.

**Comment by skurfuerst** [comment]
Might be related to / fixed by #969

**Comment by dimaip** [comment]
@daniellienert can you check if you still have this problem on master, with the new tree? I will close this for now, feel free to re-open if you still have this issue.
