### ISSUE TITLE
Node Constraints are not applied in the node creation screen for a content collection defined in the document node

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#932]
While the tested configuration works in the old UI and restrict the usable node types, they are not applied in the new UI.

Tested with: #931bb4f

**Comment by dimaip** [comment]
Can you please provide a minimum NodeTypes.yaml to reproduce it? Seems to work for me...

**Comment by skurfuerst** [comment]
could reproduce the issue, and was able tof ix :)
