### ISSUE TITLE
Changed Document-Node title is not reflected in the node tree

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#935]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

If you change a property that is used as a node label is changed the new calculated node label should be displayed. In this case i edited the title of a document. The Node itself is marked as dirty, but the title change is not shown. Even if i reload the tree the change is not there.
http://recordit.co/uB1wfoqtAw

**Comment by dimaip** [comment]
Can validate. Will fix.
