### ISSUE TITLE
Inline editing Link  - Setting a link  - dropdown not working 

### ISSUE THREAD

**Issue by cwurditsch** [neos/neos-ui#936]
If i want to set a link and use the dropdown list, i cannot scroll down until the end if it is longer list then the screen 
![bildschirmfoto 2017-09-11 um 12 52 03](https://user-images.githubusercontent.com/31848464/30271328-30103966-96f0-11e7-8fdc-68c088d9bb77.png)

**Comment by dimaip** [comment]
Hey, thanks a lot for the feedback! #922 should have fixed this issue. Are you sure you have latest code from master and that you have hard-reloaded the page (ctrl+f5)?

**Comment by dimaip** [comment]
Closing for now as I can not validate on latest master. Feel free to re-open if you have additional feedback.

**Comment by cwurditsch** [comment]
I am using Beta 3 Version

**Comment by dimaip** [comment]
Oh wow, it's like half a year old... you should be using master!
