### ISSUE TITLE
Inline editing - Bullets points are not displayed 

### ISSUE THREAD

**Issue by cwurditsch** [neos/neos-ui#937]
Bullet points are not displayed in the inline editing whereas in the published rendered site they are visible

![bildschirmfoto 2017-09-11 um 12 59 37](https://user-images.githubusercontent.com/31848464/30271597-376fc798-96f1-11e7-89cd-e8797b9e2e6e.png)
![bildschirmfoto 2017-09-11 um 12 59 49](https://user-images.githubusercontent.com/31848464/30271599-3797dcf6-96f1-11e7-94d2-a899fa904236.png)

**Comment by dimaip** [comment]
Can't reproduce it on any of my sites:
![image](https://user-images.githubusercontent.com/837032/31401613-1d776e50-adfc-11e7-8a6b-13fe84364b83.png)

**Comment by mstruebing** [comment]
Can't reproduce as well. I think Dmitri is right, if you(or someone else) think this is is a bug feel free to open again and provide further details.
