### ISSUE TITLE
SelectBox doesn't show additional information in LinkEditor and in references editor

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#944]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

In the old UI, if you searched the link editor or references editor you'd get additional information like url or node path, which was crucial to have if you had nodes with same names. Now you just get plain boring node titles.

Also the new selectbox is much more narrow, than the old one. Could make sense to give it as another option to the Dropdown, to allow for wider dropdown contents.

Old UI:
![image](https://user-images.githubusercontent.com/837032/30314116-608e3a62-97a8-11e7-9bfb-ce9d383456aa.png)

New UI:
![image](https://user-images.githubusercontent.com/837032/30314171-905a16e4-97a8-11e7-896b-4daf1b375dd9.png)

**Comment by skurfuerst** [comment]
would be important to do it in modular way. E.g. maybe extract renderer for select item into another component that you can pass to the select box

**Comment by skurfuerst** [comment]
https://github.com/neos/neos-ui/blob/master/packages/neos-ui-ckeditor-bindings/src/EditorToolbar/LinkIconButton.js

**Comment by klfman** [comment]
Finished with this issue. Will need some code review and a little more love in the CSS part (see pull request #968)

**Comment by skurfuerst** [comment]
Resolved for Reference Editor in https://github.com/neos/neos-ui/pull/1131 - still missing: References editor, Link Editor

**Comment by dimaip** [comment]
Link editor is done I think, References editor still missing.
