### ISSUE TITLE
Editor loading Problem after logging in 

### ISSUE THREAD

**Issue by cwurditsch** [neos/neos-ui#957]
I use chrome and after the logging in mask, the editor is loaded with another editor within and it is going into a indefinite circle 

After empty browser cache and reload it works. 

[Screen Recording_2017-09-13 11.59.25.mov.zip](https://github.com/neos/neos-ui/files/1299023/Screen.Recording_2017-09-13.11.59.25.mov.zip)

**Comment by johannessteu** [comment]
This is an cache/session issue. If you remove all cache/data you should be ok. Could you also try it in chromes incognito mode?

**Comment by dimaip** [comment]
Will close this for now, feel free to re-open.
