### ISSUE TITLE
Text Editor menu is NOT displayed

### ISSUE THREAD

**Issue by cwurditsch** [neos/neos-ui#958]
Text Editor menu (Bold, layout etc.)  is NOT displayed while editing a headline. It is only shown if i am editing a content section with text 
![bildschirmfoto 2017-09-13 um 12 17 06](https://user-images.githubusercontent.com/31848464/30372346-cddf05b2-987d-11e7-83b2-c2ff7c3e4dcb.png)
![bildschirmfoto 2017-09-13 um 12 17 16](https://user-images.githubusercontent.com/31848464/30372347-ce03618c-987d-11e7-90fa-14f5abe0b506.png)

**Comment by dimaip** [comment]
Hey, are you sure that the Headline nodetype is not configured to disable it? Does it show in the old UI/

**Comment by skurfuerst** [comment]
Closing because of missing feedback. Please re-open if you want to add new insights :)
