### ISSUE TITLE
Advanced inline editing

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#97]
It is our goal to allow for a variety of inline editors, not just rich text editing. @aertmann posted an interesting demo in slack today, that shows how other inline editors could look like.

So, I leave this issue just to keep a reminder for those examples.

Link: https://vitalets.github.io/x-editable/demo-bs3.html

**Comment by dimaip** [comment]
Just for reference, these guys also have nice structured editing: https://reactioncommerce.com/
