### ISSUE TITLE
Avoid overriding the constructor of React class extends by using class fields

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#979]
I just skimmed through the codebase a bit and found [a lot of usages of the typical `.bind(this)`](https://github.com/neos/neos-ui/search?utf8=%E2%9C%93&q=.bind%28this%29&type=) in the constructor's of React classes. To reduce the complexity and repetition we could just switch to [class fields](https://github.com/tc39/proposal-class-public-fields) in combination with arrow functions since they are automatically bound to the parent context :tada: 

In the same way I would also propose to assign the initial state to remove the usage custom constructors at all.

*before:*
```js
import React, {PureComponent} from 'react';

export default class Doge extends PureComponent {
    constructor(props) {
        super(props);

        this.handleWow = this.handleWow.bind(this);

        this.state = {isMuchCleaner: false};
    }

    render() {
        return (
            ...
        );
    }

    handleWow() {
        this.setState({isMuchCleaner: true});
    }
}
```

*after:*
```js
import React, {PureComponent} from 'react';

export default class Doge extends PureComponent {
    state = {isMuchCleaner: true};

    render() {
        return (
            ...
        );
    }

    handleWow = () => {
        this.setState({isMuchCleaner: true});
    }
}
```

**Comment by dimaip** [comment]
Sure, why not.

**Comment by dimaip** [comment]
I think we've resolved this issue by now. Thanks for the cool tip @Inkdpixels!
