### ISSUE TITLE
Status of "hide in menu" pages not correct in pagetree

### ISSUE THREAD

**Issue by akappler** [neos/neos-ui#994]
If a page is hidden in menu, the status is not correct represented in the tree.

Steps to reproduce:
--------------------

1. Set property of a page to "hide in menu" and publish
2. Make sure this page is not selected, select a different page
3. Reload the page

(All images are showing "hidden in menu" pages)

Result:
-------

The page in the tree is shown as a regular page which is not hidden in menu (the page name in the tree has a white color). 

![image1](https://user-images.githubusercontent.com/30337968/30635433-ab3413d4-9df2-11e7-9c27-5af5e8c4d96b.jpeg)

After selecting the page, the status get's updated and the page is correctly shown in grey. 
![image3](https://user-images.githubusercontent.com/30337968/30635586-23f21d16-9df3-11e7-9069-1631e43d2d02.jpeg)

This works till the browser gets reloaded

Expected:
----------

The page is shown as hidden with a grey font color in the page tree on load and reload of the browser

![image2](https://user-images.githubusercontent.com/30337968/30635523-f33e741c-9df2-11e7-92d8-29b7c832b78a.jpeg)

**Comment by dimaip** [comment]
Will take care, know what's up.

**Comment by dimaip** [comment]
@akappler hey so I gave a shot to reproduce it, but couldn't. Am I doing it correctly?
![peek 2017-09-06 17-02](https://user-images.githubusercontent.com/837032/30786324-e70817ce-a17c-11e7-89f6-2f4b19352cf6.gif)

**Comment by akappler** [comment]
Hi Dimitri,
yes, seems like I did it. I‘m currently on vacation and will check it when I‘m back.

**Comment by dimaip** [comment]
Will close for now. Feel free to re-open when you can validate.
